Repository cal-itp/benefits, pull requests merged in 2021-12, with the labels that each got.

#234 Refactor CSS: Reduce number of css file calls
  benefits/core/templates/core/base.html
  benefits/static/css/styles.css
Labels: deployment-dev

#235 Refactor JS
  benefits/core/templates/core/base.html
  benefits/settings.py
Labels: deployment-dev

#244 Cache headers for static files
  benefits/settings.py
  nginx.conf
Labels: deployment-dev

#245 Fix: AWS copy files matching CONFIG_FILE pattern
  .aws/ecs-task.json
Labels: deployment-dev

#247 Fix: list init path before loading
  bin/init.sh
Labels: deployment-dev

#248 Revert initialization changes
  .aws/ecs-task.json
  bin/init.sh
Labels: deployment-dev

#254 Fix: more error handling for duplicate enrollment
  benefits/enrollment/api.py
Labels: bug, deployment-dev

#257 Fix: enrollment flow for existing customers
  benefits/enrollment/api.py
Labels: bug, deployment-dev

#262 chore(deps): bump django from 3.2.9 to 3.2.10
  requirements.txt
Labels: deployment-dev

#267 Document steps to make a new release
  docs/deployment/release.md
Labels: documentation

#268 Fix: set CSRF_TRUSTED_ORIGINS
  .devcontainer/.env.sample
  .devcontainer/compose.yml
  benefits/settings.py
  tests/e2e/.env.tests
Labels: bug, deployment-dev

#270 Prepare release 2021.12.1
  benefits/__init__.py
Labels: deployment-dev
