Repository cal-itp/benefits, pull requests merged in 2021-11, with the labels that each got.

#172 Fix Linux devcontainer issue from file permissions
  Dockerfile
  bin/init.sh
  bin/start.sh
  localhost/Dockerfile.dev
Labels: deployment-dev

#174 Make sure locale directory is writable by calitp user
  Dockerfile
Labels: deployment-dev

#187 Add JavaScript/JSON/CSS linting
  .aws/ecs-task.json
  .pre-commit-config.yaml
  .vscode/launch.json
  .vscode/settings.json
  benefits/static/css/styles.css
  localhost/data/client.json
  tests/e2e/cypress.json
  tests/e2e/cypress/integration/eligibility.spec.js
  tests/e2e/cypress/integration/help.spec.js
  tests/e2e/cypress/integration/index.spec.js
  tests/e2e/cypress/integration/payment-options.spec.js
  tests/e2e/cypress/integration/spanish.spec.js
Labels: deployment-dev

#185 Refactor devcontainer and localhost files
  .devcontainer.json
  .devcontainer/.env.sample
  .devcontainer/Dockerfile
  .devcontainer/compose.yml
  .devcontainer/devcontainer.json
  .devcontainer/postAttach.sh
  .dockerignore
  .gitignore
  docs/deployment/README.md
  docs/getting-started/README.md
  docs/getting-started/development.md
  docs/getting-started/documentation.md
  docs/getting-started/localhost-directory.md
  docs/getting-started/testing.md
  fixtures/core.eligibilitytype.json
  fixtures/core.eligibilityverifier.json
  fixtures/core.paymentprocessor.json
  fixtures/core.pemdata.json
  fixtures/core.transitagency.json
  localhost/keys/README.md
  localhost/keys/client.key
  localhost/keys/client.pub
  localhost/keys/server.pub
  tests/e2e/cypress/fixtures/transit-agencies.js
  tests/e2e/cypress/fixtures/transit-agencies.json
  tests/e2e/cypress/integration/eligibility.spec.js
  tests/e2e/cypress/integration/help.spec.js
  tests/e2e/cypress/integration/index.spec.js
  tests/e2e/cypress/integration/spanish.spec.js
Labels: documentation

#194 Update links to new API docs
  docs/README.md
Labels: documentation

#191 Require confirmed eligibility for enrollment
  benefits/core/middleware.py
  benefits/enrollment/views.py
Labels: bug, deployment-dev

#190 Upgrade jQuery from 3.4.1 to 3.6.0
  benefits/core/templates/core/base.html
Labels: dependencies, deployment-dev

#209 Secure Django's language cookie
  benefits/settings.py
Labels: deployment-dev

#210 Secure critical Django cookies
  benefits/settings.py
Labels: deployment-dev

#211 Implement Content Security Policy
  benefits/settings.py
  requirements.txt
Labels: deployment-dev

#213 Configure X-XSS-Protection
  benefits/settings.py
Labels: deployment-dev

#216 Fix browser support in Content Security Policy
  benefits/settings.py
Labels: bug, deployment-dev

#219 Use minified JS and CSS files
  benefits/core/templates/core/base.html
Labels: deployment-dev

#222 Use`noopener noreferrer` for external links
  benefits/core/templates/core/base.html
  benefits/core/templates/core/help.html
  benefits/core/templates/core/includes/button.html
  benefits/core/viewmodels.py
Labels: deployment-dev

#225 Add meta description
  benefits/core/templates/core/base.html
Labels: deployment-dev

#227 Fix some logging and error noise
  benefits/core/urls.py
  benefits/settings.py
Labels: deployment-dev

#229 Delay acquisition of Enrollment access token
  benefits/core/viewmodels.py
  benefits/enrollment/templates/enrollment/index.html
  benefits/enrollment/urls.py
  benefits/enrollment/views.py
  tests/e2e/cypress/specs/integration/eligibility.spec.js
Labels: deployment-dev
