Repository cal-itp/benefits, pull requests merged in 2022-11, with the labels that each got.

#1107 Chore: Improve developer experience
  .github/dependabot.yml
  .pre-commit-config.yaml
Labels: chore, actions

#1108 Docs: link to GHCR images
  docs/deployment/README.md
Labels: documentation, infrastructure

#1097 Devcontainer: update sample server settings
  .devcontainer/server/settings.py
Labels: chore, docker

#1112 Fix: custom submitting event for form button effects
  benefits/core/templates/core/includes/form.html
Labels: deployment-dev, front-end

#1115 Copy: Spanish copy for Login.gov and CC
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, i18n

#1114 Fix: replace State Template JS with Bootstrap
  benefits/core/templates/core/base.html
  benefits/settings.py
Labels: deployment-dev, front-end, back-end

#1120 fix: missing accent
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, i18n

#1119 Help Page: New question for CC in English and Spanish, edit links
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_sample_data.py
  benefits/core/models.py
  benefits/core/templates/core/help.html
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, back-end, i18n

#1122 Chore: eligibility-server dev image and branch
  .devcontainer/server/settings.py
  .github/workflows/tests-feature.yml
  benefits/core/migrations/0002_sample_data.py
  compose.yml
Labels: deployment-dev, tests, back-end, docker

#1130 Prep release 2022.11.1
  benefits/__init__.py
Labels: deployment-dev, back-end

#1140 docs: update college discount information
  docs/use-cases/college.md
  docs/use-cases/students.md
  mkdocs.yml
Labels: documentation

#1146 faster deploy
  terraform/azure-pipelines.yml
Labels: infrastructure

#1145 chore(pipeline): don't wait for input to Terraform
  .vscode/settings.json
  terraform/azure-pipelines.yml
Labels: infrastructure
