Repository cal-itp/benefits, pull requests merged in 2022-05, with the labels that each got.

#534 fix(button):
  benefits/core/templates/core/includes/form.html
Labels: deployment-dev

#496 fix: remove deprecated Docker Compose volume option
  .devcontainer/compose.yml
Labels: chore, docker

#536 docs: expand on architecture docs
  docs/README.md
  docs/deployment/README.md
  tests/cypress/package-lock.json
Labels: documentation, tests

#553 chore: disable network requests in pytests
  tests/pytest/conftest.py
  tests/pytest/requirements.txt
Labels: tests

#573 CI: add issues and Dependabot PRs to Project Board
  .github/workflows/add-to-project-dependabot.yml
  .github/workflows/add-to-project-issues.yml
Labels: actions

#580 Devcontainer: add Git Graph extension
  .devcontainer/devcontainer.json
Labels: chore

#577 Desktop: Agency Index - Center the label over button on Agency Index page
  benefits/static/css/styles.css
Labels: deployment-dev

#579 Feat: redirect to agency's index if only one agency
  benefits/core/views.py
  tests/pytest/core/test_views.py
Labels: deployment-dev

#587 Feat: configure Azure deploy for dev env
  .github/workflows/deploy-dev.yml
Labels: deployment-dev, actions

#588 Fix: use the correct azure deploy step
  .github/workflows/deploy-dev.yml
Labels: deployment-dev, actions

#589 Fix: remove azure deploy steps
  .github/workflows/deploy-dev.yml
Labels: deployment-dev, actions

#544 Mobile: Image and Sign Out Link
  benefits/core/templates/core/page.html
  benefits/core/viewmodels.py
  benefits/static/css/styles.css
Labels: deployment-dev

#593 Fix: remove deploy to Azure web apps
  .github/workflows/deploy-dev.yml
  benefits/core/templates/core/base.html
Labels: deployment-dev, actions

#594 Chore: undo temp change in UI
  benefits/core/templates/core/base.html
Labels: deployment-dev

#578 Mobile/Tablet - Eligibility:Start - Link style, spacing
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#591 Fix: Add Spanish copy for all pages
  benefits/locale/es/LC_MESSAGES/django.po
  tests/cypress/specs/ui/enrollment.spec.js
Labels: deployment-dev

#601 Fix: Use 1st sentence of help page for meta description
  benefits/core/templates/core/base.html
Labels: deployment-dev

#602 Enrollment Success: Redesign page to have no image
  benefits/enrollment/views.py
  benefits/static/css/styles.css
Labels: deployment-dev

#607 Fix: typo in labels frontmatter in Epic issue template
  .github/ISSUE_TEMPLATE/epic-decision-record.md
Labels: bug

#606 Refactor: replace internal EV API code with eligibility-api package
  .devcontainer/Dockerfile
  Dockerfile
  benefits/eligibility/api.py
  benefits/eligibility/views.py
  requirements.txt
  tests/pytest/eligibility/test_views.py
Labels: deployment-dev, tests

#598 Refactor: simplify env file, better default settings
  .devcontainer/.env.sample
  .devcontainer/compose.yml
  .github/workflows/tests-pytest.yml
  .github/workflows/tests-ui.yml
  .vscode/launch.json
  benefits/core/middleware.py
  benefits/settings.py
  bin/init.sh
  docs/configuration/environment-variables.md
  docs/configuration/fixtures.md
  docs/configuration/oauth.md
  docs/configuration/recaptcha.md
  docs/deployment/README.md
  docs/getting-started/README.md
  tests/cypress/.env.tests
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/pytest/core/test_session.py
  tests/pytest/run.sh
Labels: documentation, deployment-dev, tests

#624 Refactor: remove jwcrypto
  benefits/core/models.py
  benefits/eligibility/views.py
  requirements.txt
  tests/pytest/eligibility/test_views.py
Labels: deployment-dev, tests
