Repository cal-itp/benefits, pull requests merged in 2022-08, with the labels that each got.

#841 Chore: remove fixtures volume mount
  compose.yml
Labels: chore, docker

#846 Fix: sample client private key
  benefits/core/migrations/0002_sample_data.py
Labels: deployment-dev, back-end

#849 Refactor: eligibility start view msgids
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, back-end, i18n

#847 Fix: configure and use latest test eligibility server
  .devcontainer/server/.env.server
  .devcontainer/server/data.csv
  compose.yml
Labels: docker

#851 Chore: move coverage config to pyproject.toml
  .coveragerc
  .pre-commit-config.yaml
  pyproject.toml
Labels: chore

#852 Feat: upgrade to Python 3.10
  .devcontainer/Dockerfile
  .devcontainer/requirements.txt
  .dockerignore
  .github/workflows/.python-version
  appcontainer/Dockerfile
  pyproject.toml
Labels: docker, actions

#787 Refactor: separate msgids for Eligibility Start
  benefits/eligibility/templates/eligibility/start.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: front-end, i18n

#854 Deploy to test
  .coveragerc
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/requirements.txt
  .devcontainer/server/.env.server
  .devcontainer/server/data.csv
  .dockerignore
  .github/workflows/.python-version
  .github/workflows/pre-commit.yml
  .gitignore
  .pre-commit-config.yaml
  .vscode/settings.json
  appcontainer/Dockerfile
  appcontainer/requirements.txt
  benefits/core/migrations/0002_sample_data.py
  benefits/core/migrations/0003_data_migration_order.py
  benefits/eligibility/templates/eligibility/start.html
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/settings.py
  bin/build.sh
  bin/init.sh
  bin/makemessages.sh
  bin/makemigrations.sh
  bin/start.sh
  compose.yml
  docs/configuration/.pages
  docs/configuration/README.md
  docs/configuration/data.md
  docs/configuration/environment-variables.md
  docs/configuration/fixtures.md
  docs/configuration/oauth.md
  docs/deployment/README.md
  docs/deployment/infrastructure.md
  docs/development/models-migrations.md
  docs/getting-started/README.md
  fixtures/00_eligibilitytype.json
  fixtures/01_pemdata.json
  fixtures/02_authprovider.json
  fixtures/03_eligibilityverifier.json
  fixtures/04_paymentprocessor.json
  fixtures/05_transitagency.json
  pyproject.toml
  terraform/app_service.tf
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/pytest/core/test_models.py
  tests/pytest/run.sh
Labels: tests, front-end, i18n, docker, actions

#858 Feat: terraform production configuration
  terraform/app_service.tf
Labels: infrastructure

#860 Release: prepare 2022.08.1
  benefits/__init__.py
Labels: deployment-dev, back-end

#864 Fix: auth scope check when userinfo is present, but claim is not
  benefits/oauth/views.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev, tests, back-end

#866 Feat: issue template for managing a release
  .github/ISSUE_TEMPLATE/release.yml
  docs/deployment/release.md
Labels: documentation, chore, infrastructure, release

#876 chore(pipeline): wait for Terraform lock to be released
  terraform/azure-pipelines.yml
Labels: infrastructure

#873 Analytics - Send event when user successfully completes payment processor enrollment
  benefits/enrollment/analytics.py
  benefits/enrollment/views.py
  tests/pytest/enrollment/test_views.py
Labels: back-end

#883 Deploy to Test
  .github/ISSUE_TEMPLATE/release.yml
  .pre-commit-config.yaml
  benefits/enrollment/analytics.py
  benefits/enrollment/views.py
  benefits/oauth/views.py
  docs/deployment/release.md
  terraform/azure-pipelines.yml
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/cypress/specs/feature/eligibility.cy.js
  tests/cypress/specs/feature/rate-limit.cy.js
  tests/cypress/specs/ui/eligibility-auth.cy.js
  tests/cypress/specs/ui/eligibility-no-auth.cy.js
  tests/cypress/specs/ui/enrollment.cy.js
  tests/pytest/enrollment/test_views.py
  tests/pytest/oauth/test_views.py
Labels: tests, back-end

#886 Prep Release 2022.08.2
  benefits/__init__.py
  benefits/enrollment/views.py
  tests/pytest/enrollment/test_views.py
Labels: deployment-dev, back-end, release

#887 Deploy 2022.08.2 to test
  benefits/__init__.py
  benefits/enrollment/views.py
  tests/pytest/enrollment/test_views.py
Labels: tests, back-end

#884 Release 2022.08.2
  .github/ISSUE_TEMPLATE/release.yml
  .pre-commit-config.yaml
  benefits/__init__.py
  benefits/enrollment/analytics.py
  benefits/enrollment/views.py
  benefits/oauth/views.py
  docs/deployment/release.md
  terraform/azure-pipelines.yml
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/cypress/specs/feature/eligibility.cy.js
  tests/cypress/specs/feature/rate-limit.cy.js
  tests/cypress/specs/ui/eligibility-auth.cy.js
  tests/cypress/specs/ui/eligibility-no-auth.cy.js
  tests/cypress/specs/ui/enrollment.cy.js
  tests/pytest/enrollment/test_views.py
  tests/pytest/oauth/test_views.py
Labels: tests, back-end
