Repository cal-itp/benefits, pull requests merged in 2022-01, with the labels that each got.

#275 Chore: reorganize Cypress tests
  .devcontainer/postAttach.sh
  .github/dependabot.yml
  .github/workflows/tests-ui.yml
  docs/getting-started/testing.md
  tests/cypress/.env.tests
  tests/cypress/.gitignore
  tests/cypress/cypress.json
  tests/cypress/fixtures/transit-agencies.js
  tests/cypress/fixtures/users.json
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/cypress/specs/integration/eligibility.spec.js
  tests/cypress/specs/ui/eligibility.spec.js
  tests/cypress/specs/ui/help.spec.js
  tests/cypress/specs/ui/index.spec.js
  tests/cypress/specs/ui/payment-options.spec.js
  tests/cypress/specs/ui/spanish.spec.js
  tests/e2e/cypress.json
  tests/e2e/cypress/fixtures/transit-agencies.js
Labels: documentation

#278 Fix: payment options content
  benefits/core/templates/core/payment-options.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev

#277 Feat: Add provider_name to analytics user props
  benefits/core/analytics.py
Labels: deployment-dev

#281 Tokenize response only for expected statuses
  benefits/eligibility/api.py
Labels: deployment-dev

#285 fix(deps): revert django from 4.0.1 to 3.2.10
  requirements.txt
Labels: deployment-dev

#288 Prepare release 2022.01.1
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  benefits/__init__.py
  docs/deployment/release.md
Labels: deployment-dev

#292 Refactor: read custom Content Security Policy config from env
  .devcontainer/.env.sample
  .devcontainer/compose.yml
  benefits/settings.py
  tests/cypress/.env.tests
Labels: deployment-dev

#298 Fix: Reset rate limit only for new sessions
  benefits/core/session.py
Labels: bug, deployment-dev

#300 Prepare release 2022.01.2
  benefits/__init__.py
Labels: deployment-dev
