Repository cal-itp/benefits, pull requests merged in 2022-10, with the labels that each got.

#984 Refactor: CSS Variables - Paragraph style and links
  benefits/core/templates/core/base.html
  benefits/core/templates/core/widgets/radio_select_option.html
  benefits/static/css/styles.css
Labels: front-end

#990 link to Style Guide
  docs/development/.pages
Labels: documentation

#967 Refactor: enrollment connect card copy
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_sample_data.py
  benefits/core/models.py
  benefits/core/templates/core/includes/media-list.html
  benefits/core/templates/core/page.html
  benefits/enrollment/templates/enrollment/success.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/enrollment/test_views.py
Labels: front-end, back-end, i18n

#999 Refactor: remove agency index pass-thru
  benefits/core/views.py
  tests/pytest/core/test_views.py
Labels: deployment-dev, tests, back-end

#997 Refactor: enrollment success copy
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_sample_data.py
  benefits/core/models.py
  benefits/core/templates/core/includes/media-list.html
  benefits/core/templates/core/page.html
  benefits/core/viewmodels.py
  benefits/enrollment/templates/enrollment/success.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/img/icon/calendarcheck.svg
Labels: front-end, back-end, i18n, migrations

#991 CSS Variables: Responsive headlines
  benefits/core/templates/core/agency_index.html
  benefits/core/templates/core/includes/form.html
  benefits/core/templates/core/widgets/radio_select_option.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/static/css/styles.css
Labels: deployment-dev, front-end, i18n

#1018 Chore: only run CodeQL for javascript/python
  .github/workflows/codeql.yml
Labels: actions

#1019 Chore: only run CodeQL for .js/.py on pull_request
  .github/workflows/codeql.yml
Labels: chore, actions

#1014 CSS Variables: Refactor footer sizing and alignment
  benefits/core/templates/core/base.html
  benefits/static/css/styles.css
Labels: front-end

#1020 Refactor: Media List on Mobile & Desktop
  benefits/core/templates/core/agency_index.html
  benefits/core/templates/core/includes/media-list.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1022 Fix: Remove unused form error-handling; add new placeholder + regex
  benefits/core/migrations/0002_sample_data.py
  benefits/core/templates/core/includes/form.html
  benefits/eligibility/forms.py
  benefits/eligibility/verify.py
  benefits/static/css/styles.css
  tests/pytest/eligibility/test_verify.py
Labels: deployment-dev, tests, front-end, back-end

#1003 Refactor: base grid
  benefits/core/templates/core/base.html
Labels: deployment-dev, front-end

#1024 add Use Case around Courtesy Cards
  docs/use-cases/courtesy-cards.md
Labels: documentation

#1025 Feat: Previous Page include
  benefits/core/templates/core/includes/previous-page-link.html
  benefits/core/viewmodels.py
  benefits/eligibility/templates/eligibility/confirm.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
  benefits/static/img/left-arrow.svg
Labels: deployment-dev, front-end, back-end, i18n

#1026 reduce size of senior success flow GIF
  docs/use-cases/seniors.md
Labels: documentation

#1029 Fix: remove previous button hover background
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1030 Fix: Sign out row bug
  benefits/core/templates/core/includes/previous-page-link.html
  benefits/core/templates/core/includes/sign-out-link.html
  benefits/enrollment/views.py
  benefits/static/css/styles.css
Labels: deployment-dev

#1041 Fixes: Media List spacing
  benefits/core/templates/core/includes/media-list.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1035 Agency Index
  benefits/core/templates/core/agency_index.html
  benefits/static/css/styles.css
  benefits/static/img/benefits-bg-desktop.jpg
  benefits/static/img/benefits-bg-mobile.jpg
Labels: deployment-dev, front-end

#1044 Fix: previous page button hover style
  benefits/core/templates/core/includes/previous-page-link.html
  benefits/core/viewmodels.py
  benefits/eligibility/templates/eligibility/start.html
  benefits/static/css/styles.css
  benefits/static/img/left-arrow.svg
Labels: deployment-dev, front-end, back-end

#1048 Fix: Allow margin-bottom for media-list
  benefits/core/templates/core/includes/media-list.html
Labels: deployment-dev, front-end

#1051 Fix: Eligibility Start - Mobile: Add padding top between help text and button
  benefits/eligibility/templates/eligibility/start.html
Labels: front-end

#1052 Fix: Enrollment Index - Add H1 padding
  benefits/enrollment/templates/enrollment/index.html
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1055 Fix: Sign Out link on Enrollment Index
  benefits/core/templates/core/base.html
  benefits/core/templates/core/includes/previous-page-link.html
  benefits/enrollment/templates/enrollment/index.html
Labels: deployment-dev, front-end

#1027 add workaround for BuildKit issue on Apple M1 hardware
  bin/build.sh
Labels: deployment-dev

#1058 Fix: Radio button positioning, elements
  benefits/core/templates/core/widgets/verifier_radio_select.html
  benefits/core/templates/core/widgets/verifier_radio_select_option.html
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1056 Style: enrollment success
  benefits/core/templates/core/base.html
  benefits/core/templates/core/includes/icon.html
  benefits/core/templates/core/logged_out.html
  benefits/core/views.py
  benefits/enrollment/templates/enrollment/success.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
Labels: deployment-dev, front-end, i18n

#1067 Fix: overwrite frame-src when needed
  benefits/settings.py
Labels: deployment-dev, back-end

#1042 Fixes: Buttons on Help, 200, 400, 404, 500, Unverified, Retry
  benefits/core/templates/core/help.html
  benefits/core/templates/core/includes/agency-links.html
  benefits/core/templates/core/includes/icon-title.html
  benefits/core/templates/core/page.html
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/eligibility/views.py
  benefits/enrollment/templates/enrollment/retry.html
  benefits/static/css/styles.css
  benefits/templates/200_user_error.html
  benefits/templates/400.html
  benefits/templates/404.html
  benefits/templates/500.html
Labels: deployment-dev, front-end, back-end

#1070 Chore: rename start item
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_sample_data.py
  benefits/core/models.py
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/conftest.py
Labels: tests, back-end, i18n, migrations

#1071 Fix: reCAPTCHA + HTML5 form validation
  benefits/core/context_processors.py
  benefits/core/middleware.py
  benefits/core/recaptcha.py
  benefits/core/templates/core/base.html
  benefits/core/templates/core/includes/form.html
  benefits/eligibility/forms.py
  benefits/eligibility/views.py
  benefits/enrollment/forms.py
  benefits/settings.py
  tests/pytest/eligibility/test_views.py
Labels: deployment-dev, tests, front-end, back-end

#1062 Fix: Use rem calculation for 18px font
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1065 Feat: Add numeric keyboard/maxlength 5 to sub input
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_sample_data.py
  benefits/core/models.py
  benefits/eligibility/forms.py
Labels: deployment-dev, back-end, migrations

#1064 Audit: Run the site through Lighthouse, HTML5 Validator
  benefits/core/templates/core/base.html
  benefits/core/templates/core/help.html
  pyproject.toml
Labels: deployment-dev, front-end

#1081 fix(css): use rem for 12px font size
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1057 Improvements to Eligibility events
  benefits/core/analytics.py
  benefits/core/models.py
  benefits/eligibility/analytics.py
  benefits/eligibility/verify.py
  benefits/eligibility/views.py
  tests/pytest/core/test_analytics.py
  tests/pytest/core/test_models.py
  tests/pytest/eligibility/test_analytics.py
  tests/pytest/eligibility/test_verify.py
  tests/pytest/eligibility/test_views.py
Labels: deployment-dev, tests, back-end, analytics

#1084 upgrade Azure provider
  terraform/.terraform.lock.hcl
  terraform/main.tf
Labels: infrastructure

#1083 rename the email resource
  terraform/monitor.tf
  terraform/uptime.tf
Labels: infrastructure

#1085 prevent destruction of Terraform resources containing secrets
  docs/deployment/infrastructure.md
  terraform/app_service.tf
  terraform/key_vault.tf
  terraform/storage.tf
Labels: documentation, infrastructure

#1089 Chore(terraform): allow configuring recaptcha for separate slots
  terraform/app_service.tf
Labels: infrastructure

#1087 chore(Terraform): sort app service settings
  terraform/app_service.tf
Labels: infrastructure

#1086 manage production storage account binding in Terraform
  terraform/app_service.tf
Labels: infrastructure

#1092 Fix: title whitespace
  benefits/core/templates/core/base.html
  benefits/core/templates/core/page.html
  benefits/core/viewmodels.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/core/test_viewmodels.py
Labels: deployment-dev, back-end, i18n

#1088 Feat: spinner on Check Status button
  benefits/core/templates/core/includes/form.html
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1069 Agency Index: Mobile edit from Design
  benefits/static/css/styles.css
Labels: deployment-dev, front-end, ON HOLD

#1098 Docs: update Courtesy Card diagram
  docs/use-cases/courtesy-cards.md
Labels: documentation

#1096 chore: document DevSecOps Azure naming conventions
  docs/deployment/infrastructure.md
Labels: documentation, infrastructure

#1082 Make the app work at 200% zoom/double the font size
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1093 Copy: English for Login.gov and CC flows
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_sample_data.py
  benefits/core/models.py
  benefits/eligibility/views.py
  benefits/enrollment/templates/enrollment/index.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/conftest.py
Labels: deployment-dev, i18n
