Repository cal-itp/benefits, pull requests merged in 2022-04, with the labels that each got.

#386 Docs: improve development docs, new section
  docs/.pages
  docs/deployment/workflows.md
  docs/development/README.md
  docs/development/commits-branches-merging.md
  docs/development/docker-dynamic-ports.md
  docs/development/img/docker-desktop-open-in-browser.png
  docs/development/img/ports-local-address.png
  docs/development/linting-pre-commit.md
  docs/development/test-server.md
  docs/getting-started/.pages
  docs/getting-started/README.md
  docs/getting-started/development.md
  docs/getting-started/documentation.md
  docs/getting-started/testing.md
  docs/requirements.txt
  mkdocs.yml
Labels: documentation

#387 Fix: gitattributes to force LF
  .gitattributes
Labels: chore

#388 Feat: add CODEOWNERS file
  .github/CODEOWNERS
Labels: chore

#389 Fix: add realistic CSP settings to sample env
  .devcontainer/.env.sample
Labels: chore

#345 Feat: custom RadioSelect widget
  benefits/core/templates/core/widgets/radio_select.html
  benefits/core/templates/core/widgets/radio_select_option.html
  benefits/core/widgets.py
  benefits/eligibility/forms.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
  fixtures/02_eligibilityverifier.json
Labels: deployment-dev

#390 Feat: re-introduce static Docker port config
  .devcontainer/.env.sample
  .devcontainer/compose.yml
Labels: chore, docker

#391 Feat: create template for eligibility start page
  benefits/eligibility/templates/eligibility/start.html
  benefits/eligibility/views.py
Labels: deployment-dev

#394 Fix: explicit blocks in start template
  benefits/eligibility/templates/eligibility/start.html
Labels: deployment-dev

#396 Track sign in status in user session
  benefits/core/session.py
Labels: deployment-dev

#399 Fix: add SRI attributes for jQuery
  benefits/core/templates/core/base.html
Labels: deployment-dev, chore, front-end

#401 Fix: add missing third-party domains to CSP settings
  .devcontainer/.env.sample
  tests/cypress/.env.tests
Labels: chore

#392 Feat: AuthProvider model
  benefits/core/migrations/0001_initial.py
  benefits/core/models.py
  fixtures/02_eligibilityverifier.json
Labels: deployment-dev

#397 feat(styles): styles to match mockup
  benefits/static/css/styles.css
  benefits/static/img/logo-lg.svg
  benefits/static/img/logo-sm.svg
Labels: deployment-dev

#402 Feat: add auth button to Eligibility start page
  benefits/core/templates/core/includes/button.html
  benefits/core/viewmodels.py
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
  benefits/static/img/icon/rightarrow-hover.svg
  benefits/static/img/icon/rightarrow.svg
  fixtures/02_authprovider.json
  fixtures/03_eligibilityverifier.json
  fixtures/04_paymentprocessor.json
  fixtures/05_transitagency.json
  tests/cypress/fixtures/transit-agencies.js
  tests/cypress/specs/ui/eligibility.spec.js
Labels: deployment-dev

#403 Refactor: Help page
  benefits/core/templates/core/base.html
  benefits/core/templates/core/help.html
  benefits/core/templates/core/payment-options.html
  benefits/core/urls.py
  benefits/core/views.py
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
  tests/cypress/specs/ui/help.spec.js
  tests/cypress/specs/ui/index.spec.js
  tests/cypress/specs/ui/payment-options.spec.js
Labels: deployment-dev

#427 fix(visual bug): better align footer text #412
  benefits/static/css/styles.css
Labels: deployment-dev

#424 fix: override entrypoint in the Docker Compose config
  .devcontainer/compose.yml
Labels: chore, docker

#430 Refactor: agency index
  benefits/core/templates/core/agency_index.html
  benefits/core/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/cypress/specs/feature/eligibility.spec.js
  tests/cypress/specs/ui/eligibility.spec.js
  tests/cypress/specs/ui/index.spec.js
Labels: deployment-dev

#425 refactor: speed up Docker image rebuild times
  Dockerfile
  docs/getting-started/README.md
Labels: documentation, deployment-dev, chore, docker

#426 Docs: configuration, environment variables, fixtures
  docs/.pages
  docs/configuration/.pages
  docs/configuration/README.md
  docs/configuration/content-security-policy.md
  docs/configuration/environment-variables.md
  docs/configuration/fixtures.md
  docs/configuration/oauth.md
  docs/configuration/rate-limit.md
  docs/configuration/recaptcha.md
Labels: documentation

#437 feat: updates content title
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev

#395 Refactor: Redesign media list on Eligibility Start page
  .github/workflows/tests-ui.yml
  benefits/core/templates/core/includes/button.html
  benefits/core/templates/core/includes/media-item.html
  benefits/core/templates/core/includes/media-list.html
  benefits/core/templates/core/page.html
  benefits/core/viewmodels.py
  benefits/eligibility/templates/eligibility/start.html
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
  benefits/static/img/icon/idscreencheck.svg
  tests/cypress/package-lock.json
  tests/cypress/specs/ui/eligibility-auth.spec.js
  tests/cypress/specs/ui/eligibility-no-auth.spec.js
Labels: deployment-dev

#414 Feat: implement OAuth/OIDC sign on with Authlib
  .devcontainer/.env.sample
  benefits/core/__init__.py
  benefits/core/migrations/0001_initial.py
  benefits/core/models.py
  benefits/eligibility/__init__.py
  benefits/eligibility/views.py
  benefits/enrollment/__init__.py
  benefits/oauth/__init__.py
  benefits/oauth/urls.py
  benefits/oauth/views.py
  benefits/settings.py
  benefits/urls.py
  fixtures/02_authprovider.json
  requirements.txt
  tests/cypress/.env.tests
Labels: deployment-dev

#441 Chore: add log statements for OAuth flow
  benefits/oauth/views.py
Labels: deployment-dev

#444 Style: agency index
  benefits/core/templates/core/agency_index.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
Labels: deployment-dev

#450 fix(header): move debug bar out of <header>, remove header height css
  benefits/core/templates/core/base.html
  benefits/static/css/styles.css
Labels: deployment-dev

#443 Fix: simplify context creation for Eligibility start
  benefits/eligibility/views.py
Labels: deployment-dev

#451 Refactor: remove paragraphs from index
  benefits/core/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
Labels: deployment-dev

#453 Fix index content title to match Figma mockup
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, chore

#447 Fix: add SECURE_PROXY_SSL_HEADER for nginx
  benefits/settings.py
Labels: deployment-dev

#429 Refactor: Update copy/logic to Enrollment success page
  benefits/core/templates/core/includes/debug.html
  benefits/enrollment/templates/enrollment/success.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
  tests/cypress/.env.tests
  tests/cypress/specs/ui/enrollment.spec.js
Labels: deployment-dev

#454 Chore: run pytest in CI
  .github/workflows/tests-pytest.yml
  tests/pytest/conftest.py
  tests/pytest/test_views.py
Labels: deployment-dev, tests, actions

#463 Style: Help page button width
  benefits/static/css/styles.css
Labels: deployment-dev

#461 Button: Large Button centering/height fixes
  benefits/static/css/styles.css
Labels: deployment-dev

#469 Test: test admin route is not registered
  tests/pytest/test_settings.py
Labels: tests

#472 Fix: Spanish copy on agency index
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev

#471 Fix: use recommended settings import approach
  benefits/core/admin.py
  benefits/core/analytics.py
  benefits/core/context_processors.py
  benefits/core/middleware.py
  benefits/core/recaptcha.py
  benefits/core/session.py
  benefits/eligibility/api.py
  benefits/eligibility/views.py
  benefits/oauth/views.py
  benefits/urls.py
  docs/configuration/README.md
Labels: documentation, deployment-dev, chore

#436 Feat: Implement OAuth/OIDC and app sign out
  benefits/core/session.py
  benefits/eligibility/views.py
  benefits/enrollment/views.py
  benefits/oauth/urls.py
  benefits/oauth/views.py
  tests/pytest/conftest.py
  tests/pytest/oauth/__init__.py
  tests/pytest/oauth/test_views.py
  tests/pytest/requirements.txt
Labels: deployment-dev

#478 feat: set up test coverage
  .github/workflows/tests-pytest.yml
  .gitignore
  docs/getting-started/testing.md
  tests/pytest/requirements.txt
Labels: documentation

#462 Fix: Align Desktop Header/Container/Footer heights
  benefits/core/templates/core/page.html
  benefits/static/css/styles.css
  tests/cypress/cypress.json
Labels: deployment-dev

#482 Feat: CI workflow to label PRs that touch tests
  .github/workflows/labeler-tests.yml
Labels: tests, actions

#483 Feat: workflow to label PRs that touch actions
  .github/workflows/labeler-actions.yml
Labels: actions

#490 fix: ignore migrations from test coverage report
  .coveragerc
Labels: tests

#491 fix: clean out old test coverage results
  tests/pytest/run.sh
Labels: tests

#492 fix: replace deprecated logger warning calls
  benefits/core/middleware.py
  benefits/enrollment/views.py
Labels: deployment-dev, chore

#497 refactor(tests): make more explicit that the default app_request path is arbitrary
  tests/pytest/conftest.py
Labels: tests

#487 Test: add tests for middleware
  benefits/core/middleware.py
  tests/pytest/conftest.py
  tests/pytest/core/test_middleware_healthcheck.py
  tests/pytest/core/test_middleware_login_required.py
  tests/pytest/core/test_middleware_loginrequired.py
  tests/pytest/eligibility/__init__.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/enrollment/__init__.py
  tests/pytest/enrollment/test_views.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev, tests

#452 Feat: add analytics for auth flows
  benefits/core/analytics.py
  benefits/eligibility/analytics.py
  benefits/oauth/analytics.py
  benefits/oauth/views.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev

#500 Docs: publish the coverage report with docs site
  .github/workflows/mkdocs.yml
  docs/.pages
  docs/getting-started/.pages
  docs/tests/.pages
  docs/tests/README.md
Labels: documentation, tests, actions

#486 Test: default user session values
  benefits/core/analytics.py
  benefits/core/session.py
  tests/pytest/core/test_session.py
Labels: tests

#470 Redesign: Sign in with Login.gov button + Eligibility Start page alignment
  benefits/core/templates/core/includes/button.html
  benefits/core/viewmodels.py
  benefits/eligibility/templates/eligibility/start.html
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
  benefits/static/img/login-gov-logo-rev.svg
  tests/cypress/specs/ui/eligibility-auth.spec.js
  tests/cypress/specs/ui/enrollment.spec.js
Labels: deployment-dev

#505 Feat: anchor link analytics
  benefits/core/templates/core/base.html
Labels: deployment-dev, analytics

#480 Refactor: Agency link style/template for Help page, Enrollment Unverified page
  benefits/core/templates/core/help.html
  benefits/core/templates/core/includes/agency-links.html
  benefits/core/templates/core/page.html
  benefits/core/viewmodels.py
  benefits/core/views.py
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
Labels: deployment-dev

#514 fix(css): right-align continue button on eligibility start
  benefits/static/css/styles.css
Labels: deployment-dev

#515 Fix: mkdocs runs after Pytest
  .github/workflows/mkdocs.yml
Labels: documentation, actions

#519 Fix: point to working server image
  .devcontainer/compose.yml
Labels: chore, docker

#516 Feat: sign out link
  benefits/core/context_processors.py
  benefits/core/templates/core/includes/sign-out-link.html
  benefits/eligibility/templates/eligibility/confirm.html
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/eligibility/views.py
  benefits/enrollment/templates/enrollment/index.html
  benefits/enrollment/templates/enrollment/retry.html
  benefits/enrollment/views.py
  benefits/settings.py
  benefits/static/css/styles.css
Labels: deployment-dev

#520 Fix: enrollment retry button msgid
  benefits/enrollment/views.py
Labels: deployment-dev

#525 Fix: help copy - minor punctuation fixes in About
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev

#523 fix(copy): update copy on eligibility start
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/cypress/specs/ui/eligibility-auth.spec.js
Labels: deployment-dev

#526 Fix/copy: Enrollment Index & Success
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev

#529 Fix: help copy - update Littlepay punctuation and link text
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev

#528 Fix: help copy - update Login.gov section/links
  benefits/core/templates/core/help.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev

#531 Fix: link to coverage report in docs
  docs/.pages
  docs/tests/.pages
Labels: documentation

#524 Update English copy: core
  benefits/core/templates/core/agency_index.html
  benefits/core/viewmodels.py
  benefits/core/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/cypress/specs/ui/index.spec.js
Labels: deployment-dev, tests

#527 Fix: help copy - update Payment Options
  benefits/core/templates/core/help.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev

#532 Fix: signout link on Eligibility Confirm resubmission page
  benefits/eligibility/views.py
Labels: deployment-dev
