Repository cal-itp/benefits, pull requests merged in 2022-06, with the labels that each got.

#649 Fix(ci): use importlib as import mode
  tests/pytest/run.sh
Labels: bug, chore, tests

#639 Refactor: bring back eligibility API helper module
  benefits/eligibility/api.py
  benefits/eligibility/views.py
  tests/pytest/conftest.py
  tests/pytest/eligibility/test_api.py
  tests/pytest/eligibility/test_views.py
Labels: deployment-dev, tests

#638 Add Azure page
  docs/deployment/azure.md
  mkdocs.yml
Labels: documentation

#651 Mobile: All action buttons on mobile are now 72px height.
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#629 Mobile: New footer design
  benefits/core/templates/core/base.html
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#603 Chore: remove AWS deployment
  .aws/ecs-task.json
  .aws/set-env.sh
  .devcontainer/compose.yml
  .dockerignore
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy-test.yml
  .github/workflows/labeler-deploy-dev.yml
  docs/configuration/environment-variables.md
  docs/deployment/README.md
  docs/deployment/workflows.md
Labels: documentation, deployment-dev, actions, infrastructure

#657 Chore: init deletes existing db
  bin/init.sh
  docs/configuration/fixtures.md
Labels: documentation, deployment-dev, chore, docker

#670 chore: better integrate infrastructure documentation
  docs/deployment/README.md
  docs/deployment/infrastructure.md
  mkdocs.yml
Labels: documentation

#661 IAL2 Login.gov Flow: Redirect users to Eligibility Start
  .vscode/settings.json
  benefits/core/views.py
  tests/cypress/specs/ui/eligibility-no-auth.cy.js
  tests/cypress/specs/ui/enrollment.cy.js
  tests/pytest/core/test_views.py
Labels: deployment-dev

#673 Link to CDT privacy policy
  benefits/core/templates/core/base.html
Labels: deployment-dev

#671 Chore: Faster devcontainer start
  .devcontainer/Dockerfile
  .devcontainer/postAttach.sh
  .pre-commit-config.yaml
  docs/tests/README.md
Labels: documentation

#677 Chore: remove node/npm installation steps in devcontainer
  .devcontainer/Dockerfile
  .vscode/launch.json
Labels: chore, docker

#679 Feat: verifier oauth fields
  benefits/core/migrations/0001_initial.py
  benefits/core/models.py
  fixtures/03_eligibilityverifier.json
Labels: deployment-dev

#668 Views: cleanup and testing
  benefits/core/views.py
  benefits/eligibility/views.py
  benefits/enrollment/api.py
  benefits/enrollment/views.py
  benefits/oauth/client.py
  benefits/oauth/redirects.py
  benefits/oauth/views.py
  tests/pytest/conftest.py
  tests/pytest/core/test_middleware_login_required.py
  tests/pytest/core/test_session.py
  tests/pytest/core/test_views.py
  tests/pytest/eligibility/conftest.py
  tests/pytest/eligibility/keys/README.md
  tests/pytest/eligibility/keys/client.pub
  tests/pytest/eligibility/keys/server.key
  tests/pytest/eligibility/test_api.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/enrollment/test_views.py
  tests/pytest/oauth/conftest.py
  tests/pytest/oauth/test_client.py
  tests/pytest/oauth/test_redirects.py
  tests/pytest/oauth/test_views.py
  tests/pytest/requirements.txt
Labels: deployment-dev, tests, back-end

#688 New Login.gov button design
  benefits/settings.py
  benefits/static/css/styles.css
  benefits/static/fonts/PublicSans-Bold.woff
  benefits/static/fonts/PublicSans-Bold.woff2
Labels: deployment-dev

#690 Chore: add test slot and domains to Terraform
  docs/deployment/infrastructure.md
  terraform/.terraform.lock.hcl
  terraform/app_service.tf
  terraform/main.tf
  terraform/monitor.tf
Labels: documentation, infrastructure

#691 chore: document the two Azure subscriptions
  docs/deployment/infrastructure.md
Labels: documentation, infrastructure

#696 Fix: New footer link color is #73B3E7
  benefits/static/css/styles.css
Labels: deployment-dev

#697 Fix: Eligibility Start - Links
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
Labels: deployment-dev

#693 chore: reflect the sticky settings in Terraform
  terraform/app_service.tf
Labels: infrastructure

#699 CI: add a few more PR labelers
  .github/workflows/labeler-back-end.yml
  .github/workflows/labeler-docker.yml
  .github/workflows/labeler-front-end.yml
  .github/workflows/labeler-i18n.yml
Labels: actions

#700 Docs: improve readme description
  README.md
Labels: documentation

#698 Feat: dynamic OAuth scope from verifier
  benefits/oauth/client.py
  benefits/oauth/views.py
  benefits/settings.py
  tests/pytest/oauth/conftest.py
  tests/pytest/oauth/test_client.py
  tests/pytest/oauth/test_redirects.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev, tests

#685 Mobile: One column layout for certain mobile pages
  benefits/enrollment/views.py
  benefits/static/css/styles.css
Labels: deployment-dev

#708 Feat: IAL2 help copy
  benefits/core/templates/core/help.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/cypress/specs/ui/help.cy.js
Labels: deployment-dev, front-end, i18n

#710 Refactor: models and migrations
  benefits/core/migrations/0001_initial.py
  benefits/core/models.py
  bin/makemigrations.sh
  docs/development/models-migrations.md
Labels: documentation, deployment-dev, back-end

#712 Refactor: oauth client config
  benefits/core/__init__.py
  benefits/core/apps.py
  benefits/core/migrations/0001_initial.py
  benefits/core/models.py
  benefits/eligibility/__init__.py
  benefits/eligibility/apps.py
  benefits/eligibility/verify.py
  benefits/eligibility/views.py
  benefits/enrollment/__init__.py
  benefits/enrollment/apps.py
  benefits/enrollment/views.py
  benefits/oauth/__init__.py
  benefits/oauth/analytics.py
  benefits/oauth/apps.py
  benefits/oauth/client.py
  benefits/oauth/redirects.py
  benefits/oauth/views.py
  benefits/settings.py
  benefits/urls.py
  docs/configuration/oauth.md
  fixtures/02_authprovider.json
  fixtures/03_eligibilityverifier.json
  tests/pytest/eligibility/test_verify.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/enrollment/test_views.py
  tests/pytest/oauth/conftest.py
  tests/pytest/oauth/test_app.py
  tests/pytest/oauth/test_client.py
  tests/pytest/oauth/test_redirects.py
  tests/pytest/oauth/test_views.py
Labels: documentation, tests, back-end

#715 Chore: remove unused language file entries
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: i18n

#722 Fix: Fixes for Eligibility Start Link Style, Debug Bar-related improvements
  benefits/core/templates/core/includes/debug.html
  benefits/static/css/styles.css
Labels: deployment-dev

#721 Chore: don't run Cypress tests in CI
  .github/workflows/tests-ui.yml
Labels: chore, tests, front-end, actions

#725 New Copy for Enrollment Start, Enrollment Success, Help, 404, 500
  benefits/core/templates/core/help.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: i18n

#731 Spanish language links
  benefits/core/templates/core/help.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end, i18n

#719 Send logs to Azure Monitor
  benefits/logging.py
  benefits/settings.py
  docs/configuration/environment-variables.md
  docs/deployment/infrastructure.md
  requirements.txt
  tests/pytest/test_logging.py
Labels: documentation, deployment-dev, back-end, infrastructure

#734 Set up test instance of Azure Insights
  terraform/monitor.tf
Labels: infrastructure

#732 Send exceptions to Azure Monitor
  benefits/core/middleware.py
  benefits/settings.py
  docs/deployment/infrastructure.md
Labels: back-end

#736 document the deployment slot settings
  terraform/app_service.tf
Labels: infrastructure

#737 update list of deployment slot settings
  terraform/app_service.tf
Labels: infrastructure

#741 feat: deploy dev on all pushes
  .github/workflows/deploy-dev.yml
Labels: deployment-dev, actions

#740 chore: re-add auto-instrumented variables to deployment slot settings
  terraform/app_service.tf
Labels: infrastructure

#742 chore: add debugging messages around Azure configuration
  benefits/logging.py
  benefits/settings.py
Labels: deployment-dev, back-end

#744 allow the SHA of the deployed image to be viewed
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  .github/workflows/deploy.yml
  .gitignore
  docs/deployment/README.md
Labels: documentation, actions, infrastructure

#750 fix: Eligibility Start - Add h1, h2, h3
  benefits/eligibility/templates/eligibility/start.html
  benefits/static/css/styles.css
Labels: deployment-dev

#746 chore: improve formatting behavior
  .devcontainer/devcontainer.json
  .vscode/settings.json
Labels: docker

#743 add documentation on where logs can be found
  docs/deployment/infrastructure.md
Labels: documentation, infrastructure
