Repository cal-itp/benefits, pull requests merged in 2022-07, with the labels that each got.

#764 add Mermaid syntax highlighting plugin
  .devcontainer/devcontainer.json
Labels: docker

#763 Copy: remove second paragraph, update button text, fix default arg bug
  benefits/core/viewmodels.py
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: back-end, i18n

#762 Fix: Unverified page copy and design
  benefits/core/viewmodels.py
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
Labels: front-end, back-end, i18n

#755 Feat: analytics for IAL2
  benefits/oauth/analytics.py
  benefits/oauth/views.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev, tests

#770 deploy latest changes to test
  .devcontainer/devcontainer.json
  .pre-commit-config.yaml
  .vscode/settings.json
  benefits/core/templates/core/agency_index.html
  benefits/core/templates/core/base.html
  benefits/core/templates/core/includes/alert-bar.html
  benefits/core/templates/core/includes/alert.html
  benefits/core/templates/core/includes/analytics.html
  benefits/core/templates/core/includes/debug.html
  benefits/core/templates/core/includes/form.html
  benefits/core/templates/core/includes/icon.html
  benefits/core/templates/core/includes/lang-selector.html
  benefits/core/templates/core/includes/nocookies.html
  benefits/core/templates/core/includes/noscript.html
  benefits/core/templates/core/page.html
  benefits/core/templates/core/widgets/radio_select.html
  benefits/core/templates/core/widgets/radio_select_option.html
  benefits/core/viewmodels.py
  benefits/eligibility/templates/eligibility/start.html
  benefits/eligibility/views.py
  benefits/enrollment/templates/enrollment/index.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/oauth/analytics.py
  benefits/oauth/views.py
  benefits/static/css/styles.css
  docs/README.md
  docs/deployment/infrastructure.md
  docs/deployment/release.md
  docs/deployment/workflows.md
  requirements.txt
  terraform/.terraform.lock.hcl
  terraform/app_service.tf
  terraform/storage.tf
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/pytest/oauth/test_views.py
Labels: tests, front-end, i18n, docker

#791 Fix: format on save in devcontainer
  .vscode/settings.json
Labels: chore, docker

#788 Fix database setup for pytests
  tests/pytest/conftest.py
  tests/pytest/core/test_middleware_login_required.py
  tests/pytest/core/test_models.py
  tests/pytest/core/test_session.py
  tests/pytest/core/test_views.py
  tests/pytest/eligibility/test_verify.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/enrollment/test_api_Client.py
Labels: tests

#793 Fix: enrollment overlay in Django 4.0.x
  benefits/settings.py
  requirements.txt
Labels: deployment-dev, back-end

#796 Docs: update links to Django documentation from 3.2 to 4.0
  benefits/settings.py
  benefits/urls.py
  docs/README.md
  docs/configuration/README.md
  docs/configuration/environment-variables.md
  docs/configuration/fixtures.md
  docs/configuration/rate-limit.md
Labels: documentation, deployment-dev, back-end

#795 chore: fix Docker build
  Dockerfile
Labels: deployment-dev, docker

#794 apply Terraform changes from dev branch
  docs/deployment/infrastructure.md
  terraform/azure-pipelines.yml
Labels: documentation, infrastructure

#804 upgrade Azure Terraform provider
  terraform/.terraform.lock.hcl
  terraform/app_service.tf
  terraform/main.tf
  terraform/network.tf
Labels: infrastructure

#805 chore: test change to slot
  terraform/app_service.tf
Labels: infrastructure

#806 Fix: local docs site build
  docs/requirements.txt
  mkdocs.yml
Labels: documentation

#800 add page on student discount use case
  docs/.pages
  docs/students.md
Labels: documentation

#808 chore: remove extraneous loading of Mermaid
  mkdocs.yml
Labels: documentation

#810 Docs Use Cases section, cleanup
  docs/.pages
  docs/README.md
  docs/configuration/.pages
  docs/configuration/content-security-policy.md
  docs/configuration/oauth.md
  docs/development/commits-branches-merging.md
  docs/getting-started/.pages
  docs/getting-started/README.md
  docs/tests/.pages
  docs/tests/README.md
  docs/use-cases/README.md
  docs/use-cases/students.md
  mkdocs.yml
Labels: documentation

#792 Terraform: override App Service Cipher Suite
  terraform/.terraform.lock.hcl
  terraform/app_service.tf
  terraform/network.tf
Labels: infrastructure

#802 Reorganize container files
  .devcontainer/devcontainer.json
  .github/dependabot.yml
  .github/workflows/deploy.yml
  .github/workflows/labeler-docker.yml
  .github/workflows/tests-feature.yml
  .github/workflows/tests-pytest.yml
  .github/workflows/tests-ui.yml
  appcontainer/Dockerfile
  appcontainer/gunicorn.conf.py
  appcontainer/nginx.conf
  appcontainer/requirements.txt
  bin/build.sh
  compose.yml
  docs/development/README.md
  docs/getting-started/README.md
Labels: documentation, chore, tests, docker, actions

#817 chore(deps): bump conventional-pre-commit from v1.2.0 to v1.4.0
  .pre-commit-config.yaml
Labels: dependencies

#816 Fix: Django template formatting
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .pre-commit-config.yaml
  .vscode/settings.json
  benefits/core/templates/core/agency_index.html
  benefits/core/templates/core/base.html
  benefits/core/templates/core/help.html
  benefits/core/templates/core/includes/agency-links.html
  benefits/core/templates/core/includes/alert-bar.html
  benefits/core/templates/core/includes/alert.html
  benefits/core/templates/core/includes/button.html
  benefits/core/templates/core/includes/debug.html
  benefits/core/templates/core/includes/form.html
  benefits/core/templates/core/includes/icon-title.html
  benefits/core/templates/core/includes/icon.html
  benefits/core/templates/core/includes/lang-selector.html
  benefits/core/templates/core/includes/nocookies.html
  benefits/core/templates/core/includes/noscript.html
  benefits/core/templates/core/includes/sign-out-link.html
  benefits/core/templates/core/page.html
  benefits/core/templates/core/widgets/radio_select.html
  benefits/core/templates/core/widgets/radio_select_option.html
  benefits/eligibility/templates/eligibility/confirm.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/enrollment/templates/enrollment/index.html
  benefits/enrollment/templates/enrollment/retry.html
  benefits/enrollment/templates/enrollment/success.html
  pyproject.toml
Labels: deployment-dev, front-end, docker

#818 chore: switch to new subnet
  terraform/network.tf
Labels: infrastructure

#819 Revert "chore: switch to new subnet"
  terraform/app_service.tf
  terraform/network.tf
Labels: infrastructure

#821 Terraform: add slot storage mounts
  terraform/app_service.tf
Labels: infrastructure

#823 Devcontainer: add terraform extension
  .devcontainer/devcontainer.json
  .vscode/settings.json
Labels: docker

#822 Terraform: add container registry/image to slots
  terraform/app_service.tf
Labels: infrastructure

#812 Model tests
  tests/pytest/core/test_models.py
Labels: tests

#831 chore(docs): list manual infrastructure setup steps
  docs/configuration/environment-variables.md
  docs/deployment/infrastructure.md
  terraform/app_service.tf
Labels: documentation, infrastructure

#814 Refactor: load data with migration, add helper script for PO files
  .devcontainer/devcontainer.json
  benefits/core/migrations/0002_sample_data.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  bin/init.sh
  bin/makemessages.sh
  bin/makemigrations.sh
  docs/configuration/.pages
  docs/configuration/README.md
  docs/configuration/data.md
  docs/configuration/environment-variables.md
  docs/configuration/oauth.md
  docs/deployment/README.md
  docs/development/models-migrations.md
  docs/getting-started/README.md
  fixtures/00_eligibilitytype.json
  fixtures/01_pemdata.json
  fixtures/02_authprovider.json
  fixtures/03_eligibilityverifier.json
  fixtures/04_paymentprocessor.json
  fixtures/05_transitagency.json
  terraform/app_service.tf
Labels: back-end, i18n

#827 Feat: support for optional sample data and additional data migrations
  .gitignore
  benefits/core/migrations/0002_sample_data.py
  benefits/core/migrations/0003_data_migration_order.py
  benefits/settings.py
  bin/init.sh
  docs/configuration/data.md
  docs/configuration/environment-variables.md
Labels: back-end

#840 Fix: Docker migrations permissions
  appcontainer/Dockerfile
Labels: docker
