Repository cal-itp/benefits, pull requests merged in 2022-12, with the labels that each got.

#1147 fix(Terraform): add missing sticky settings
  terraform/app_service.tf
Labels: infrastructure

#1109 chore(Terraform): manage production certitificate binding in code
  terraform/app_service.tf
  terraform/key_vault.tf
  terraform/variables.tf
Labels: infrastructure

#1144 docs(infrastructure): document missing environment setup steps
  docs/deployment/infrastructure.md
  terraform/monitor.tf
Labels: documentation, infrastructure

#1152 chore(terraform): remove certificate binding
  docs/deployment/infrastructure.md
  terraform/app_service.tf
  terraform/key_vault.tf
Labels: documentation, infrastructure

#1154 docs: elaborate on what is managed by DevSecOps team
  docs/deployment/infrastructure.md
Labels: documentation, infrastructure

#1157 Feat: add sqlite-viewer extension to devcontainer
  .devcontainer/devcontainer.json
  .vscode/settings.json
Labels: chore, docker

#1160 Docs: attaching with DEBUG=False
  docs/development/README.md
  docs/development/docker-dynamic-ports.md
  docs/development/img/vscode-debugger-launch-config.png
Labels: documentation

#1156 docs(Terraform): add information about locking
  docs/configuration/environment-variables.md
  docs/deployment/infrastructure.md
  docs/deployment/troubleshooting.md
Labels: documentation, infrastructure

#1162 Docs: workflow for Django message files
  docs/development/.pages
  docs/development/i18n.md
Labels: documentation

#1074 separate infrastructure environments
  .gitignore
  docs/deployment/infrastructure.md
  docs/deployment/troubleshooting.md
  docs/deployment/workflows.md
  terraform/README.md
  terraform/app_service.tf
  terraform/azure-pipelines.yml
  terraform/environment.tf
  terraform/init.sh
  terraform/key_vault.tf
  terraform/main.tf
  terraform/monitor.tf
  terraform/network.tf
  terraform/pipeline/deploy.yml
  terraform/pipeline/workspace.py
  terraform/storage.tf
  terraform/uptime.tf
Labels: infrastructure

#1168 Prep 2022.12.1 release
  benefits/__init__.py
Labels: deployment-dev, back-end

#1169 Deploy 2022.12.1 to test
  .devcontainer/devcontainer.json
  .github/workflows/tests-ui.yml
  .gitignore
  .pre-commit-config.yaml
  .vscode/settings.json
  appcontainer/requirements.txt
  benefits/__init__.py
  docs/configuration/environment-variables.md
  docs/deployment/infrastructure.md
  docs/deployment/troubleshooting.md
  docs/deployment/workflows.md
  docs/development/.pages
  docs/development/README.md
  docs/development/docker-dynamic-ports.md
  docs/development/i18n.md
  docs/development/img/vscode-debugger-launch-config.png
  docs/use-cases/college.md
  docs/use-cases/students.md
  mkdocs.yml
  terraform/README.md
  terraform/app_service.tf
  terraform/azure-pipelines.yml
  terraform/environment.tf
  terraform/init.sh
  terraform/key_vault.tf
  terraform/main.tf
  terraform/monitor.tf
  terraform/network.tf
  terraform/pipeline/deploy.yml
  terraform/pipeline/workspace.py
  terraform/storage.tf
  terraform/uptime.tf
  terraform/variables.tf
Labels: tests, back-end, docker, actions

#1172 chore(Terraform): output the outbound IP ranges
  docs/deployment/troubleshooting.md
  terraform/output.tf
Labels: infrastructure
