Repository cal-itp/benefits, pull requests merged in 2023-01, with the labels that each got.

#1177 Prep release 2023.01.1
  benefits/__init__.py
Labels: deployment-dev, back-end

#1178 Deploy 2023.01.1 to test
  .pre-commit-config.yaml
  appcontainer/requirements.txt
  benefits/__init__.py
  docs/deployment/troubleshooting.md
  terraform/output.tf
Labels: back-end

#1170 Release 2023.01.1
  .devcontainer/devcontainer.json
  .github/workflows/tests-ui.yml
  .gitignore
  .pre-commit-config.yaml
  .vscode/settings.json
  appcontainer/requirements.txt
  benefits/__init__.py
  docs/configuration/environment-variables.md
  docs/deployment/infrastructure.md
  docs/deployment/troubleshooting.md
  docs/deployment/workflows.md
  docs/development/.pages
  docs/development/README.md
  docs/development/docker-dynamic-ports.md
  docs/development/i18n.md
  docs/development/img/vscode-debugger-launch-config.png
  docs/use-cases/college.md
  docs/use-cases/students.md
  mkdocs.yml
  terraform/README.md
  terraform/app_service.tf
  terraform/azure-pipelines.yml
  terraform/environment.tf
  terraform/init.sh
  terraform/key_vault.tf
  terraform/main.tf
  terraform/monitor.tf
  terraform/network.tf
  terraform/output.tf
  terraform/pipeline/deploy.yml
  terraform/pipeline/workspace.py
  terraform/storage.tf
  terraform/uptime.tf
  terraform/variables.tf
Labels: back-end, actions

#1171 fix(Terraform): downgrade App Service plan
  terraform/app_service.tf
Labels: infrastructure

#1180 Chore: add pull_request trigger to pytest workflow
  .github/workflows/tests-pytest.yml
Labels: tests, actions

#1181 chore: upgrade Terraform and provider
  docs/deployment/infrastructure.md
  terraform/.terraform.lock.hcl
  terraform/main.tf
  terraform/pipeline/deploy.yml
Labels: documentation, infrastructure

#1182 Chore: use eligibility-api package from PyPI
  appcontainer/requirements.txt
Labels: docker

#1184 fix(CI): send API check failure notifications to Slack
  .github/workflows/check-api.yml
Labels: actions

#1195 Refactor: msgids for common messages
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_sample_data.py
  benefits/core/models.py
  benefits/eligibility/views.py
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/conftest.py
Labels: deployment-dev, back-end, i18n, migrations

#1196 Refactor: parameterize messages with agency-specific content
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_sample_data.py
  benefits/core/models.py
  benefits/eligibility/views.py
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/conftest.py
Labels: deployment-dev, back-end, i18n, migrations

#1201 Chore: always show the user the eligibility index
  benefits/eligibility/views.py
  tests/pytest/eligibility/test_views.py
Labels: deployment-dev, tests, back-end

#1198 Refactor: add support for env variables in data migration
  benefits/core/migrations/0002_sample_data.py
Labels: deployment-dev, back-end, migrations

#1204 Refactor: agency selection backend
  benefits/core/migrations/0002_sample_data.py
  benefits/core/models.py
  benefits/core/views.py
  benefits/eligibility/urls.py
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, back-end, i18n, migrations

#1218 Fix: missing Spanish translations
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, i18n

#1206 Refactor: agency selection frontend
  benefits/core/templates/core/agency_index.html
  benefits/core/templates/core/includes/agency-selector.html
  benefits/core/templates/core/includes/modal.html
  benefits/core/templates/core/index.html
  benefits/core/templates/core/landing.html
  benefits/core/templates/core/page.html
  benefits/core/viewmodels.py
  benefits/core/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/settings.py
  benefits/static/css/styles.css
  benefits/static/img/agencies/mst-lg.svg
  benefits/static/img/agencies/mst-sm.svg
  benefits/static/img/agencies/sacrt-lg.svg
  benefits/static/img/agencies/sacrt-sm.svg
  tests/pytest/core/test_views.py
Labels: deployment-dev, front-end, back-end, i18n

#1212 Update SacRT copy, and add Spanish translations
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: i18n

#1215 Refactor: agency index msgid
  benefits/core/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: back-end, i18n

#1221 Prep release 2023.01.2
  benefits/__init__.py
Labels: deployment-dev, back-end

#1222 Deploy 2023.01.2 to test
  .github/workflows/check-api.yml
  .github/workflows/tests-pytest.yml
  .pre-commit-config.yaml
  appcontainer/requirements.txt
  benefits/__init__.py
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_sample_data.py
  benefits/core/models.py
  benefits/core/templates/core/agency_index.html
  benefits/core/templates/core/includes/agency-selector.html
  benefits/core/templates/core/includes/modal.html
  benefits/core/templates/core/index.html
  benefits/core/templates/core/landing.html
  benefits/core/templates/core/page.html
  benefits/core/viewmodels.py
  benefits/core/views.py
  benefits/eligibility/templates/eligibility/index.html
  benefits/eligibility/urls.py
  benefits/eligibility/views.py
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/settings.py
  benefits/static/css/styles.css
  benefits/static/img/agencies/mst-lg.svg
  benefits/static/img/agencies/mst-sm.svg
  benefits/static/img/agencies/sacrt-lg.svg
  benefits/static/img/agencies/sacrt-sm.svg
  docs/deployment/infrastructure.md
  docs/deployment/troubleshooting.md
  docs/development/docker-dynamic-ports.md
  docs/use-cases/seniors.md
  terraform/.terraform.lock.hcl
  terraform/app_service.tf
  terraform/key_vault.tf
  terraform/main.tf
  terraform/pipeline/deploy.yml
  terraform/variables.tf
  tests/pytest/conftest.py
  tests/pytest/core/test_views.py
  tests/pytest/eligibility/test_views.py
Labels: tests, front-end, back-end, i18n, actions, migrations

#1223 Fix: agency selector with n cards
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1225 Deploy to test
  benefits/static/css/styles.css
Labels: front-end

#1229 Fix: eligibility types in events
  benefits/eligibility/analytics.py
  tests/pytest/eligibility/test_analytics.py
Labels: deployment-dev, tests, back-end

#1230 Deploy to test
  .github/workflows/deploy.yml
  .github/workflows/tests-feature.yml
  .github/workflows/tests-ui.yml
  .pre-commit-config.yaml
  benefits/eligibility/analytics.py
  tests/pytest/eligibility/test_analytics.py
Labels: tests, back-end, actions
