Repository cal-itp/benefits, pull requests merged in 2023-06, with the labels that each got.

#1434 Chore: update to latest eligibility-api
  pyproject.toml
Labels: deployment-dev

#1438 Fix: migrations formatting
  bin/makemigrations.sh
Labels: deployment-dev

#1433 Feat: AuthProvider scheme
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/oauth/client.py
  tests/pytest/oauth/test_client.py
Labels: deployment-dev, tests, back-end, migrations

#1436 Veterans - Eligibility Verifier + Eligibility Type
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/core/templates/core/includes/media-list.html
  benefits/core/viewmodels.py
  benefits/eligibility/forms.py
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  terraform/app_service.tf
  tests/cypress/plugins/helpers.js
  tests/cypress/specs/benefit-select.cy.js
  tests/pytest/conftest.py
Labels: deployment-dev, back-end

#1439 Feat: veterans auth provider
  benefits/core/migrations/0002_data.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  terraform/app_service.tf
Labels: deployment-dev, back-end

#1464 Fix: Veterans - Enrollment Success: Add msgid for Veterans copy
  benefits/core/migrations/0002_data.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, i18n, migrations

#1462 Refactor: AuthProvider supports_sign_out
  benefits/core/context_processors.py
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/core/templates/core/includes/sign-out-link.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/conftest.py
  tests/pytest/core/test_models.py
Labels: deployment-dev, migrations

#1459 Eligibility Start: Show Veteran-flow specific bullet copy
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, back-end

#1467 Feat: reset OAuth for new flows
  benefits/core/session.py
  benefits/eligibility/views.py
  benefits/oauth/client.py
  tests/pytest/core/test_session.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/oauth/test_client.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev, tests, back-end

#1470 Fix: add terraform env vars for auth provider scheme
  terraform/app_service.tf
Labels: infrastructure

#1468 Deploy initial Veterans integration to Test
  .github/ISSUE_TEMPLATE/release.yml
  .github/workflows/tests-ui.yml
  .gitignore
  .pre-commit-config.yaml
  .vscode/launch.json
  benefits/core/context_processors.py
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/core/session.py
  benefits/core/templates/core/help.html
  benefits/core/templates/core/includes/agency-links.html
  benefits/core/templates/core/includes/media-list.html
  benefits/core/templates/core/includes/sign-out-link.html
  benefits/core/viewmodels.py
  benefits/core/views.py
  benefits/eligibility/forms.py
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/eligibility/views.py
  benefits/enrollment/templates/enrollment/retry.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/oauth/client.py
  benefits/sentry.py
  benefits/static/css/styles.css
  bin/makemigrations.sh
  docs/deployment/release.md
  pyproject.toml
  terraform/app_service.tf
  terraform/storage.tf
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/cypress/plugins/helpers.js
  tests/cypress/specs/benefit-select.cy.js
  tests/pytest/conftest.py
  tests/pytest/core/test_models.py
  tests/pytest/core/test_session.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/oauth/test_client.py
  tests/pytest/oauth/test_views.py
Labels: tests, back-end, i18n, actions, migrations
