Repository cal-itp/benefits, pull requests merged in 2023-12, with the labels that each got.

#1801 Fix: attempt db rename during reset
  .gitignore
  bin/init.sh
Labels: bug, deployment-dev, chore, infrastructure

#1804 Fix: Re-enrollment
  benefits/enrollment/api.py
  tests/pytest/enrollment/test_api_GroupResponse.py
Labels: tests, back-end

#1805 Prepare 2023.12.1 release
  pyproject.toml
Labels: deployment-dev

#1806 Deploy 2023.12.1 to test
  benefits/enrollment/api.py
  pyproject.toml
  tests/pytest/enrollment/test_api_GroupResponse.py
Labels: back-end

#1807 Release 2023.12.1
  .devcontainer/devcontainer.json
  .github/workflows/deploy.yml
  .github/workflows/tests-pytest.yml
  .gitignore
  .pre-commit-config.yaml
  .vscode/settings.json
  appcontainer/nginx.conf
  benefits/core/migrations/0002_data.py
  benefits/core/templates/core/includes/help--sbmtd.html
  benefits/eligibility/forms.py
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--sbmtd-mobility-pass.html
  benefits/eligibility/templates/eligibility/includes/selection-label--sbmtd-mobility-pass.html
  benefits/eligibility/templates/eligibility/start--sbmtd-mobility-pass.html
  benefits/enrollment/api.py
  benefits/enrollment/templates/enrollment/retry.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/settings.py
  benefits/static/css/styles.css
  bin/init.sh
  compose.yml
  docs/configuration/environment-variables.md
  docs/requirements.txt
  docs/use-cases/Veterans.md
  mkdocs.yml
  pyproject.toml
  terraform/app_service.tf
  terraform/restart-app.sh
  terraform/secrets/file.sh
  terraform/secrets/read.sh
  terraform/secrets/value.sh
  terraform/storage.tf
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/pytest/core/test_models.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/enrollment/test_api_GroupResponse.py
  tests/pytest/run.sh
Labels: deployment, tests, front-end, back-end, i18n, actions, migrations

#1818 Docs: Analytics
  docs/product-and-design/.pages
  docs/product-and-design/analytics.md
Labels: documentation

#1798 Docs: add system use case with retry as alternate flow
  benefits/enrollment/templates/enrollment/index.html
  docs/use-cases/system-use-cases.md
Labels: documentation

#1815 Docs: supported agencies, enrollment pathways
  docs/.pages
  docs/README.md
  docs/enrollment-pathways/README.md
  docs/enrollment-pathways/agency-cards.md
  docs/enrollment-pathways/img/senior-success.gif
  docs/enrollment-pathways/older-adults.md
  docs/enrollment-pathways/veterans.md
  docs/use-cases/college.md
Labels: documentation

#1827 Fix: Fix NIST typo in English.
  benefits/core/templates/core/help.html
  benefits/eligibility/templates/eligibility/includes/modal--login-gov-help.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end, i18n

#1824 Docs: add manual qa instructions
  docs/tests/.pages
  docs/tests/automated-tests.md
  docs/tests/manual-tests.md
Labels: documentation

#1828 Docs: Various small fixes
  docs/product-and-design/.pages
  docs/product-and-design/use-cases/enrollment-use-cases.md
  mkdocs.yml
Labels: documentation

#1836 Fix(server): remove unnecessary configuration of FLASK_APP
  .devcontainer/server/.env.server
Labels: bug, docker

#1832 Docs: Copy terms & style guide
  docs/product-and-design/.pages
  docs/product-and-design/copy-style.md
Labels: documentation
