Repository cal-itp/benefits, pull requests merged in 2023-02, with the labels that each got.

#1238 Chore: bump version
  benefits/__init__.py
Labels: deployment-dev, back-end

#1231 fix(docs): add missing system interconnections to architecture diagram
  docs/deployment/infrastructure.md
Labels: documentation

#1236 Docs: configuring a new transit agency
  docs/configuration/.pages
  docs/configuration/data.md
  docs/configuration/transit-agency.md
Labels: documentation

#1254 chore(docs): show what data is exchanged/stored where
  docs/deployment/infrastructure.md
Labels: documentation, infrastructure

#1257 fix(devcontainer): use new VSCode settings/extensions configuration format
  .devcontainer/devcontainer.json
Labels: docker

#1262 copy in information that came up in the failure screnarios
  docs/configuration/environment-variables.md
  docs/deployment/infrastructure.md
  docs/deployment/troubleshooting.md
Labels: documentation, infrastructure

#1260 fix Azure exception handling
  appcontainer/requirements.txt
  benefits/core/middleware.py
  benefits/settings.py
Labels: deployment-dev

#1272 Fix: Landing Page - Decrease main container height on mobile
  benefits/static/css/styles.css
Labels: front-end

#1259 chore: set up Sentry
  appcontainer/requirements.txt
  benefits/sentry.py
  benefits/settings.py
  benefits/urls.py
  docs/configuration/environment-variables.md
  docs/deployment/troubleshooting.md
Labels: documentation, deployment-dev, back-end, docker, infrastructure

#1275 fix(Sentry): handle cases where Git is available but we're not in a repository
  benefits/sentry.py
Labels: deployment-dev, back-end

#1279 chore(CI): simplify starting client for UI tests
  .github/workflows/tests-ui.yml
Labels: tests, actions

#1280 docs: add security overview
  docs/README.md
Labels: documentation

#1281 add tests for Sentry revision code
  .gitignore
  benefits/sentry.py
  tests/pytest/test_sentry.py
Labels: deployment-dev, tests

#1263 fix feature tests
  .github/dependabot.yml
  .github/workflows/tests-feature.yml
  benefits/core/migrations/0002_sample_data.py
  benefits/core/migrations/sample_agency.json
  benefits/settings.py
  docs/tests/README.md
  tests/cypress/fixtures/README.md
  tests/cypress/fixtures/transit-agencies.js
  tests/cypress/fixtures/users.json
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/cypress/specs/feature/eligibility.cy.js
  tests/cypress/specs/feature/rate-limit.cy.js
Labels: deployment-dev, tests, back-end, actions, migrations

#1277 fix: UI tests
  .github/workflows/tests-cypress.yml
  tests/cypress/package.json
  tests/cypress/specs/benefit-select.cy.js
  tests/cypress/specs/courtesy-cards.cy.js
  tests/cypress/specs/help.cy.js
  tests/cypress/specs/helpers.js
  tests/cypress/specs/rate-limit.cy.js
  tests/cypress/specs/spanish.cy.js
  tests/cypress/specs/ui/eligibility-auth.cy.js
  tests/cypress/specs/ui/eligibility-no-auth.cy.js
  tests/cypress/specs/ui/enrollment.cy.js
  tests/cypress/specs/ui/help.cy.js
  tests/cypress/specs/ui/index.cy.js
Labels: tests

#1261 chore(Azure): remove app-level logging to Azure Monitor
  appcontainer/requirements.txt
  benefits/core/middleware.py
  benefits/logging.py
  benefits/settings.py
  docs/configuration/environment-variables.md
  docs/deployment/troubleshooting.md
  tests/pytest/test_logging.py
Labels: back-end

#1285 Fix: healthcheck user agents
  benefits/__init__.py
  benefits/core/middleware.py
  benefits/settings.py
  docs/configuration/environment-variables.md
  tests/pytest/core/test_middleware_healthcheck_user_agent.py
Labels: tests

#1287 Fix: adapt test for healthcheck user agents
  benefits/core/middleware.py
  benefits/settings.py
  docs/configuration/environment-variables.md
  tests/pytest/core/test_middleware_healthcheck_user_agent.py
Labels: documentation, deployment-dev, tests, back-end

#1292 Deploy 2023.02.1 to test
  .devcontainer/devcontainer.json
  .github/dependabot.yml
  .github/workflows/tests-cypress.yml
  .github/workflows/tests-feature.yml
  .github/workflows/tests-ui.yml
  .gitignore
  .pre-commit-config.yaml
  appcontainer/requirements.txt
  benefits/__init__.py
  benefits/core/middleware.py
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_sample_data.py
  benefits/core/migrations/0003_data_migration_order.py
  benefits/core/migrations/sample_agency.json
  benefits/logging.py
  benefits/sentry.py
  benefits/settings.py
  benefits/static/css/styles.css
  benefits/urls.py
  docs/README.md
  docs/configuration/.pages
  docs/configuration/data.md
  docs/configuration/environment-variables.md
  docs/configuration/transit-agency.md
  docs/deployment/infrastructure.md
  docs/deployment/troubleshooting.md
  docs/tests/README.md
  docs/use-cases/courtesy-cards.md
  docs/use-cases/seniors.md
  tests/cypress/fixtures/README.md
  tests/cypress/fixtures/transit-agencies.js
  tests/cypress/fixtures/users.json
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/cypress/specs/benefit-select.cy.js
  tests/cypress/specs/courtesy-cards.cy.js
  tests/cypress/specs/feature/eligibility.cy.js
  tests/cypress/specs/help.cy.js
  tests/cypress/specs/helpers.js
  tests/cypress/specs/rate-limit.cy.js
  tests/cypress/specs/spanish.cy.js
  tests/cypress/specs/ui/eligibility-auth.cy.js
  tests/cypress/specs/ui/eligibility-no-auth.cy.js
  tests/cypress/specs/ui/enrollment.cy.js
  tests/cypress/specs/ui/help.cy.js
  tests/cypress/specs/ui/index.cy.js
  tests/pytest/core/test_middleware_healthcheck_user_agent.py
  tests/pytest/test_logging.py
  tests/pytest/test_sentry.py
Labels: back-end, docker, actions, migrations

#1291 Fix: small issues on environment variable docs
  docs/configuration/environment-variables.md
Labels: documentation

#1299 Fix Cypress setup instructions
  docs/tests/README.md
Labels: documentation
