Repository cal-itp/benefits, pull requests merged in 2023-03, with the labels that each got.

#1293 Feat: set Key Vault values
  benefits/core/migrations/0002_sample_data.py
  docs/deployment/.pages
  docs/deployment/secrets.md
  terraform/secrets/README.md
  terraform/secrets/file.sh
  terraform/secrets/value.sh
Labels: documentation, deployment-dev, back-end, infrastructure, migrations

#1301 Fix: represent Key Vault purge protection in Terraform
  terraform/.terraform.lock.hcl
  terraform/key_vault.tf
Labels: bug, infrastructure

#1294 Feat: specify app settings as code
  docs/deployment/infrastructure.md
  docs/deployment/secrets.md
  docs/getting-started/README.md
  terraform/app_service.tf
  terraform/environment.tf
  terraform/secrets/read.sh
Labels: documentation, deployment-dev, back-end, infrastructure, migrations

#1305 Prepare Release 2023.03.1
  benefits/__init__.py
Labels: deployment-dev, back-end, release

#1306 Deploy 2023.03.1 to test
  .github/ISSUE_TEMPLATE/incident-response.md
  .pre-commit-config.yaml
  appcontainer/requirements.txt
  benefits/__init__.py
  benefits/core/migrations/0002_sample_data.py
  docs/configuration/environment-variables.md
  docs/deployment/.pages
  docs/deployment/infrastructure.md
  docs/deployment/secrets.md
  docs/getting-started/README.md
  docs/tests/README.md
  terraform/.terraform.lock.hcl
  terraform/app_service.tf
  terraform/environment.tf
  terraform/key_vault.tf
  terraform/secrets/README.md
  terraform/secrets/file.sh
  terraform/secrets/read.sh
  terraform/secrets/value.sh
  tests/cypress/package-lock.json
  tests/cypress/package.json
Labels: tests, back-end, release, migrations

#1308 Docs: update steps for pushing tags
  docs/deployment/release.md
Labels: documentation, infrastructure

#1328 Refactor: delete now unneeded Azure file mount
  terraform/app_service.tf
Labels: infrastructure

#1329 Docs: configuration data uses env vars/secrets
  docs/configuration/README.md
Labels: documentation

#1332 Deploy 2023.03.2 to test
  .github/workflows/tests-ui.yml
  .gitignore
  .pre-commit-config.yaml
  appcontainer/Dockerfile
  appcontainer/requirements.txt
  benefits/__init__.py
  benefits/core/analytics.py
  benefits/core/migrations/0002_data.py
  benefits/core/migrations/0003_data_migration_order.py
  benefits/core/models.py
  benefits/core/recaptcha.py
  benefits/enrollment/api.py
  benefits/settings.py
  bin/init.sh
  docs/configuration/README.md
  docs/configuration/data.md
  docs/configuration/environment-variables.md
  docs/configuration/oauth.md
  docs/deployment/README.md
  docs/deployment/infrastructure.md
  docs/deployment/release.md
  docs/development/models-migrations.md
  docs/getting-started/README.md
  terraform/app_service.tf
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/pytest/core/test_models.py
Labels: tests, docker, actions, migrations

#1339 Deploy to test
  benefits/core/migrations/0002_data.py
  terraform/app_service.tf
Labels: back-end, migrations

#1341 Release 2023.03.2
  .github/workflows/tests-ui.yml
  .gitignore
  .pre-commit-config.yaml
  appcontainer/Dockerfile
  appcontainer/requirements.txt
  benefits/__init__.py
  benefits/core/analytics.py
  benefits/core/migrations/0002_data.py
  benefits/core/migrations/0003_data_migration_order.py
  benefits/core/models.py
  benefits/core/recaptcha.py
  benefits/enrollment/api.py
  benefits/settings.py
  bin/init.sh
  docs/configuration/README.md
  docs/configuration/data.md
  docs/configuration/environment-variables.md
  docs/configuration/oauth.md
  docs/deployment/README.md
  docs/deployment/infrastructure.md
  docs/deployment/release.md
  docs/development/models-migrations.md
  docs/getting-started/README.md
  terraform/app_service.tf
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/pytest/core/test_models.py
Labels: tests, docker, actions, migrations

#1342 Fix: read timeout
  benefits/settings.py
Labels: bug, deployment-dev, back-end

#1343 Fix: configure Sentry denylist
  benefits/sentry.py
Labels: back-end
