Repository cal-itp/benefits, pull requests merged in 2023-08, with the labels that each got.

#1594 Index/Agency-Index: Add rounded corners to mobile box
  benefits/static/css/styles.css
Labels: deployment-dev

#1597 Footer: Fix type (letter-spacing, font-weight)
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1598 Fix: Desktop - Login.gov modal alignment
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--senior.html
  benefits/eligibility/templates/eligibility/includes/modal--senior-help.html
  benefits/eligibility/templates/eligibility/includes/modal--senior-start-help.html
  benefits/eligibility/templates/eligibility/includes/selection-label--senior.html
Labels: deployment-dev, front-end

#1595 Add new primary color, hover color, footer hover color, footer visited color
  benefits/static/css/styles.css
Labels: front-end

#1596 Help: Align desktop width to 8-col
  benefits/core/templates/core/help.html
Labels: deployment-dev, front-end

#1599 Modals: Mobile - Get alignment right
  benefits/core/templates/core/includes/modal-info.html
  benefits/eligibility/templates/eligibility/includes/modal--contactless.html
  benefits/eligibility/templates/eligibility/includes/modal--senior-help.html
  benefits/eligibility/templates/eligibility/includes/modal--senior-start-help.html
  benefits/enrollment/templates/enrollment/includes/modal--littlepay.html
  benefits/static/css/styles.css
Labels: front-end

#1608 Fix: Login.gov button width on Tablet
  benefits/eligibility/templates/eligibility/start--mst-courtesy-card.html
  benefits/eligibility/templates/eligibility/start--senior.html
  benefits/eligibility/templates/eligibility/start--veteran.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1611 Fix: language event middleware
  benefits/core/middleware.py
  tests/pytest/core/test_middleware_changed_language_event.py
Labels: deployment-dev, tests, back-end

#1610 Fix: Line-height across the app for H1, H2, H3, H4
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1620 Feat: define an enrollment success template for agencies
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/enrollment/templates/enrollment/success--mst.html
  benefits/enrollment/templates/enrollment/success--sacrt.html
  benefits/enrollment/templates/enrollment/success.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  tests/pytest/conftest.py
  tests/pytest/enrollment/test_views.py
Labels: deployment-dev, tests, front-end, back-end, i18n, migrations

#1622 Agency Selector Modal: Fix padding regression
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1621 Chore: update English agency-specific copy
  benefits/locale/en/LC_MESSAGES/django.po
Labels: i18n

#1614 Landing Pages: Fix text padding
  benefits/core/templates/core/landing.html
Labels: deployment-dev

#1623 Help: Mobile - Type fixes
  benefits/core/templates/core/help.html
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1626 Refactor: app strings into msgid
  benefits/core/migrations/0002_data.py
  benefits/core/templates/core/agency-index.html
  benefits/core/templates/core/base.html
  benefits/core/templates/core/help.html
  benefits/core/templates/core/includes/button--origin.html
  benefits/core/templates/core/includes/button--previous-page.html
  benefits/core/templates/core/includes/help--mst.html
  benefits/core/templates/core/includes/link--sign-out--senior.html
  benefits/core/templates/core/includes/modal--agency-selector.html
  benefits/core/templates/core/includes/nocookies.html
  benefits/core/templates/core/includes/noscript.html
  benefits/core/templates/core/index--mst.html
  benefits/core/templates/core/index--sacrt.html
  benefits/core/templates/core/index.html
  benefits/core/templates/core/landing.html
  benefits/core/templates/core/logged-out.html
  benefits/core/templates/core/widgets/verifier-radio-select.html
  benefits/eligibility/forms.py
  benefits/eligibility/templates/eligibility/includes/media-item--bankcardcheck--start.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--mst-courtesy-card.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--senior.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--veteran.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck.html
  benefits/eligibility/templates/eligibility/includes/modal--contactless.html
  benefits/eligibility/templates/eligibility/includes/modal--senior-help.html
  benefits/eligibility/templates/eligibility/includes/modal--senior-start-help.html
  benefits/eligibility/templates/eligibility/includes/selection-label--mst-courtesy-card.html
  benefits/eligibility/templates/eligibility/includes/selection-label--senior.html
  benefits/eligibility/templates/eligibility/includes/selection-label--veteran.html
  benefits/eligibility/templates/eligibility/index--mst.html
  benefits/eligibility/templates/eligibility/index--sacrt.html
  benefits/eligibility/templates/eligibility/index.html
  benefits/eligibility/templates/eligibility/start--mst-courtesy-card.html
  benefits/eligibility/templates/eligibility/start--senior.html
  benefits/eligibility/templates/eligibility/start--veteran.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
  benefits/enrollment/templates/enrollment/includes/modal--littlepay.html
  benefits/enrollment/templates/enrollment/index.html
  benefits/enrollment/templates/enrollment/retry.html
  benefits/enrollment/templates/enrollment/success--mst.html
  benefits/enrollment/templates/enrollment/success--sacrt.html
  benefits/enrollment/templates/enrollment/success.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/templates/200-user-error.html
  benefits/templates/400.html
  benefits/templates/404.html
  benefits/templates/500.html
  benefits/templates/error.html
Labels: deployment-dev, front-end, i18n, migrations

#1627 Refactor: All modal triggers are now links, not buttons
  benefits/core/templates/core/includes/modal-trigger-link.html
  benefits/core/templates/core/includes/modal-trigger.html
  benefits/core/templates/core/index.html
  benefits/eligibility/templates/eligibility/includes/media-item--bankcardcheck--start.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--senior.html
  benefits/eligibility/templates/eligibility/includes/selection-label--senior.html
  benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
Labels: deployment-dev, front-end

#1613 Letter-spacing
  benefits/core/templates/core/includes/modal--agency-selector.html
  benefits/core/templates/core/landing.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/static/css/styles.css
Labels: front-end

#1632 Refactor: agency logo width and height
  benefits/core/templates/core/includes/modal--agency-selector.html
  benefits/static/img/agencies/mst-lg.svg
  benefits/static/img/agencies/mst-sm.svg
  benefits/static/img/agencies/sacrt-lg.svg
  benefits/static/img/agencies/sacrt-sm.svg
Labels: deployment-dev, front-end

#1629 Spanish copy + small copy fixes
  benefits/core/migrations/0002_data.py
  benefits/core/templates/core/agency-index.html
  benefits/core/templates/core/includes/help--mst.html
  benefits/core/templates/core/index.html
  benefits/eligibility/templates/eligibility/start--mst-courtesy-card.html
  benefits/eligibility/templates/eligibility/start--senior.html
  benefits/eligibility/templates/eligibility/start--veteran.html
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
  benefits/enrollment/templates/enrollment/index.html
  benefits/enrollment/templates/enrollment/retry.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/templates/200-user-error.html
  benefits/templates/400.html
  benefits/templates/500.html
Labels: deployment-dev, front-end, back-end, i18n, migrations

#1633 Feat: Focus rings
  benefits/core/templates/core/base.html
  benefits/core/templates/core/includes/form.html
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1641 Landing Page: Desktop - Add 72px extra padding/margin top
  benefits/core/templates/core/landing.html
Labels: deployment-dev, front-end

#1640 Enrollment Success: Desktop - Bring text/img closer together
  benefits/enrollment/templates/enrollment/success.html
Labels: deployment-dev, front-end

#1639 Fix: Button uses primary-color for background
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1644 Enrollment Index: Ensure header is always 2 lines.
  benefits/enrollment/templates/enrollment/index.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: front-end, i18n

#1649 Fix: Agency Selector h4 bug
  benefits/core/templates/core/includes/modal--agency-selector.html
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1642 Refactor: Footer - Re-do mobile footer alignment
  benefits/core/templates/core/base.html
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1645 Feat: Skip Nav
  benefits/core/templates/core/base.html
  benefits/static/css/styles.css
Labels: front-end

#1447 Document copy/translation/i18n/PO file process
  docs/.pages
  docs/development/.pages
  docs/development/i18n.md
  docs/product-and-design/.pages
  docs/product-and-design/copy-delivery.md
Labels: documentation, deployment-dev, i18n

#1631 Feat: configure SBMTD senior flow
  benefits/core/migrations/0002_data.py
  benefits/core/templates/core/index--sbmtd.html
  benefits/eligibility/templates/eligibility/index--sbmtd.html
  benefits/enrollment/templates/enrollment/success--sbmtd.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/img/agencies/sbmtd-lg.svg
  benefits/static/img/agencies/sbmtd-sm.svg
  terraform/app_service.tf
Labels: front-end, back-end, migrations

#1655 Fix: return home button
  benefits/core/templates/core/includes/button--index.html
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/templates/200-user-error.html
  benefits/templates/400.html
  benefits/templates/500.html
  benefits/templates/error.html
Labels: deployment-dev, front-end, i18n

#1646 Agency Modal: New design
  benefits/core/templates/core/includes/modal--agency-selector.html
  benefits/core/templates/core/includes/modal-info.html
  benefits/core/templates/core/includes/modal.html
  benefits/core/templates/core/index.html
  benefits/eligibility/templates/eligibility/includes/media-item--bankcardcheck--start.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--senior.html
  benefits/eligibility/templates/eligibility/includes/modal--contactless.html
  benefits/eligibility/templates/eligibility/includes/modal--senior-help.html
  benefits/eligibility/templates/eligibility/includes/modal--senior-start-help.html
  benefits/eligibility/templates/eligibility/includes/selection-label--senior.html
  benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
  benefits/enrollment/templates/enrollment/includes/modal--littlepay.html
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1658 Fix: Focus ring on Card on Google Chrome
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1654 Fix: Remove alt tag from decorative icons
  benefits/core/templates/core/includes/icon.html
  benefits/core/templates/core/logged-out.html
  benefits/eligibility/templates/eligibility/includes/media-item--bankcardcheck--start.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck.html
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
  benefits/enrollment/templates/enrollment/retry.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/templates/error.html
Labels: deployment-dev, front-end, i18n

#1663 Fix: Skip Nav - Remove skip nav page jank
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1657 Refactor: eligibility forms
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/eligibility/forms.py
  benefits/eligibility/templates/eligibility/confirm.html
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/conftest.py
  tests/pytest/core/test_models.py
  tests/pytest/eligibility/test_views.py
Labels: deployment-dev, tests, back-end, migrations

#1665 Feat: EligibilityVerifier active flag
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/eligibility/forms.py
  terraform/app_service.tf
  tests/pytest/conftest.py
  tests/pytest/eligibility/test_views.py
Labels: deployment-dev, back-end, infrastructure, migrations

#1667 Refactor Cypress helper
  tests/cypress/plugins/helpers.js
Labels: tests

#1670 Fix: verifier secret name
  benefits/core/migrations/0002_data.py
  terraform/app_service.tf
Labels: back-end, infrastructure, migrations

#1671 Deploy to test
  benefits/core/migrations/0002_data.py
  terraform/app_service.tf
Labels: back-end, migrations

#1674 Refactor: Remove unnecessary template code
  benefits/core/templates/core/base.html
  benefits/core/templates/core/includes/form.html
Labels: deployment-dev, front-end
