Repository cal-itp/benefits, pull requests merged in 2023-09, with the labels that each got.

#1705 Eligibility Start: Veterans - Use Older Adult copy
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--senior.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--veteran.html
  benefits/eligibility/templates/eligibility/includes/modal--login-gov-start-help.html
  benefits/eligibility/templates/eligibility/start--veteran.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end, i18n

#1708 fix(copy): Seguro Social, not seguro social
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, i18n

#1711 Fix: Add one S
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, i18n

#1712 Fix: Update Spanish tense for Login.gov modal
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, i18n

#1706 Eligibility Index: Veterans - Use Older Adult copy
  benefits/core/templates/core/includes/button--sign-out--senior.html
  benefits/core/templates/core/includes/modal-trigger.html
  benefits/eligibility/templates/eligibility/includes/modal--login-gov-help.html
  benefits/eligibility/templates/eligibility/includes/selection-label--senior.html
  benefits/eligibility/templates/eligibility/includes/selection-label--veteran.html
  benefits/eligibility/templates/eligibility/start--senior.html
  benefits/eligibility/templates/eligibility/start--veteran.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
Labels: front-end, i18n

#1713 Veterans: add Sign Out link for Veterans/Login.gov flow
  benefits/core/migrations/0002_data.py
  benefits/core/templates/core/includes/button--sign-out--login-gov.html
  benefits/core/templates/core/includes/link--sign-out--login-gov.html
Labels: front-end, back-end, migrations

#1725 Chore: bump version ahead of release
  benefits/__init__.py
Labels: back-end

#1729 Chore: version management
  benefits/__init__.py
  pyproject.toml
  tests/pytest/test_version.py
Labels: deployment-dev, back-end

#1734 Chore: update to Python 3.11
  .github/workflows/.python-version
  pyproject.toml
Labels: actions

#1726 Deploy to test
  .github/workflows/.python-version
  .github/workflows/codeql.yml
  .github/workflows/deploy.yml
  .github/workflows/mkdocs.yml
  .github/workflows/tests-cypress.yml
  .github/workflows/tests-pytest.yml
  .github/workflows/tests-ui.yml
  .pre-commit-config.yaml
  benefits/__init__.py
  benefits/core/migrations/0002_data.py
  benefits/core/templates/core/base.html
  benefits/core/templates/core/includes/button--sign-out--login-gov.html
  benefits/core/templates/core/includes/form.html
  benefits/core/templates/core/includes/link--sign-out--login-gov.html
  benefits/core/templates/core/includes/modal-trigger.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--senior.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--veteran.html
  benefits/eligibility/templates/eligibility/includes/modal--login-gov-help.html
  benefits/eligibility/templates/eligibility/includes/modal--login-gov-start-help.html
  benefits/eligibility/templates/eligibility/includes/selection-label--senior.html
  benefits/eligibility/templates/eligibility/includes/selection-label--veteran.html
  benefits/eligibility/templates/eligibility/start--senior.html
  benefits/eligibility/templates/eligibility/start--veteran.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
  pyproject.toml
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/pytest/test_version.py
Labels: tests, front-end, back-end, i18n, migrations

#1738 Fix: configure API Client to use our requests timeout settings
  benefits/eligibility/verify.py
  terraform/app_service.tf
Labels: deployment-dev, back-end

#1739 Deploy to test
  benefits/eligibility/verify.py
  terraform/app_service.tf
Labels: back-end

#1741 Deploy to prod
  benefits/eligibility/verify.py
  terraform/app_service.tf
Labels: back-end

#1743 Docker: Revert platform change
  compose.yml
Labels: docker

#1748 Docs: adding veterans use case
  docs/use-cases/Veterans.md
Labels: documentation

#1745 Tests: add coverage comments to PRs
  .github/workflows/tests-pytest.yml
  pyproject.toml
  tests/pytest/core/test_models.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/run.sh
Labels: deployment-dev, tests, actions

#1733 Chore: add pip metadata file to app container
  .github/workflows/deploy.yml
Labels: chore, actions
