Repository cal-itp/benefits, pull requests merged in 2023-11, with the labels that each got.

#1769 Chore: clean up devcontainer
  .devcontainer/devcontainer.json
  .vscode/settings.json
  tests/pytest/core/test_models.py
  tests/pytest/run.sh
Labels: chore, docker

#1770 Feat: parameterize Django database path/deletion
  benefits/settings.py
  bin/init.sh
  docs/configuration/environment-variables.md
  terraform/app_service.tf
Labels: documentation, back-end

#1775 Feat: create and mount Azure file share
  terraform/app_service.tf
  terraform/storage.tf
Labels: infrastructure

#1771 Feat: Add SBTMD Mobility Pass configuration
  benefits/core/migrations/0002_data.py
  benefits/core/templates/core/includes/help--sbmtd.html
  benefits/eligibility/forms.py
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--sbmtd-mobility-pass.html
  benefits/eligibility/templates/eligibility/includes/selection-label--sbmtd-mobility-pass.html
  benefits/eligibility/templates/eligibility/start--sbmtd-mobility-pass.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  terraform/app_service.tf
Labels: deployment-dev, front-end, i18n, migrations

#1778 Feat: Unattended superuser creation
  bin/init.sh
  docs/configuration/environment-variables.md
  terraform/app_service.tf
Labels: documentation, deployment-dev, infrastructure

#1781 Chore: block Sqlite scraper patterns
  appcontainer/nginx.conf
Labels: docker, security

#1779 Add SBMTD Mobility Pass vars to Terraform
  terraform/app_service.tf
Labels: infrastructure

#1787 Show retry button on enrollment/retry page
  benefits/enrollment/templates/enrollment/retry.html
Labels: deployment-dev, back-end

#1788 Fix: typo in secret name
  terraform/app_service.tf
Labels: infrastructure

#1793 Fix: back of card, not both front and back
  benefits/eligibility/forms.py
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--sbmtd-mobility-pass.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, back-end, i18n

#1790 Deploy to test
  .devcontainer/devcontainer.json
  .github/workflows/deploy.yml
  .github/workflows/tests-pytest.yml
  .pre-commit-config.yaml
  .vscode/settings.json
  appcontainer/nginx.conf
  benefits/core/migrations/0002_data.py
  benefits/core/templates/core/includes/help--sbmtd.html
  benefits/eligibility/forms.py
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--sbmtd-mobility-pass.html
  benefits/eligibility/templates/eligibility/includes/selection-label--sbmtd-mobility-pass.html
  benefits/eligibility/templates/eligibility/start--sbmtd-mobility-pass.html
  benefits/enrollment/templates/enrollment/retry.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/settings.py
  benefits/static/css/styles.css
  bin/init.sh
  compose.yml
  docs/configuration/environment-variables.md
  docs/use-cases/Veterans.md
  pyproject.toml
  terraform/app_service.tf
  terraform/restart-app.sh
  terraform/secrets/file.sh
  terraform/secrets/read.sh
  terraform/secrets/value.sh
  terraform/storage.tf
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/pytest/core/test_models.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/run.sh
Labels: tests, front-end, back-end, i18n, docker

#1800 Docs: add extension to make nested lists work
  docs/requirements.txt
  mkdocs.yml
Labels: documentation
