Repository cal-itp/benefits, pull requests merged in 2023-07, with the labels that each got.

#1489 Refactor: verifier radio template
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/core/templates/core/includes/selection_label__login_gov.html
  benefits/core/templates/core/includes/selection_label__mst_courtesy_card.html
  benefits/core/templates/core/includes/selection_label__mst_veteran.html
  benefits/core/templates/core/includes/verifier_radio_select_label.html
  benefits/core/templates/core/widgets/verifier_radio_select_option.html
  benefits/core/widgets.py
  benefits/eligibility/forms.py
  tests/pytest/conftest.py
Labels: deployment-dev, front-end, back-end, migrations

#1501 Buttons: Use copy for button capitalization, not CSS
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
  tests/cypress/plugins/helpers.js
  tests/cypress/specs/help.cy.js
Labels: deployment-dev, front-end, i18n

#1499 Home, Agency Index: Use new EN/ES copy with 1 new agency variable
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/core/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, back-end, i18n, migrations

#1498 Refactor: Eligibility start page
  benefits/core/context_processors.py
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/core/templates/core/includes/button__previous_page.html
  benefits/core/templates/core/includes/icon__direct_args.html
  benefits/core/templates/core/includes/media-list.html
  benefits/core/templates/core/includes/media_item.html
  benefits/core/viewmodels.py
  benefits/eligibility/templates/eligibility/includes/media_item__bankcardcheck__start.html
  benefits/eligibility/templates/eligibility/includes/media_item__idcardcheck.html
  benefits/eligibility/templates/eligibility/includes/media_item__idcardcheck__start__login_gov.html
  benefits/eligibility/templates/eligibility/includes/media_item__idcardcheck__start__mst_courtesy_card.html
  benefits/eligibility/templates/eligibility/includes/media_item__idcardcheck__start__veteran.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/eligibility/templates/eligibility/start__login_gov.html
  benefits/eligibility/templates/eligibility/start__mst_courtesy_card.html
  benefits/eligibility/templates/eligibility/start__veteran.html
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/conftest.py
  tests/pytest/eligibility/test_views.py
Labels: deployment-dev, tests, front-end, i18n, migrations

#1504 Refactor: remove Modal viewmodel
  benefits/core/templates/core/includes/modal--agency-selector.html
  benefits/core/templates/core/includes/modal-trigger.html
  benefits/core/templates/core/includes/modal.html
  benefits/core/templates/core/index.html
  benefits/core/viewmodels.py
  benefits/core/views.py
Labels: deployment-dev, front-end, back-end

#1502 Refactor: Enrollment index
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/core/viewmodels.py
  benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
  benefits/enrollment/templates/enrollment/index.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/enrollment/test_views.py
Labels: tests, front-end, back-end, i18n

#1506 Copy: Eligibility Confirm - Courtesy Card flow form
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, i18n

#1513 Chore: Older Adult selection label copy
  benefits/core/migrations/0002_data.py
  benefits/core/templates/core/includes/selection-label--mst-courtesy-card.html
  benefits/core/templates/core/includes/selection-label--senior.html
  benefits/core/templates/core/includes/selection-label--veteran.html
  benefits/core/templates/core/includes/selection-label.html
  benefits/core/templates/core/includes/selection_label__login_gov.html
  benefits/core/templates/core/includes/selection_label__mst_courtesy_card.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/conftest.py
Labels: deployment-dev, tests, front-end, back-end, i18n

#1516 LittlePay Modal
  benefits/core/templates/core/includes/modal-info.html
  benefits/core/templates/core/includes/modal-trigger.html
  benefits/core/templates/core/index.html
  benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
  benefits/enrollment/templates/enrollment/includes/modal--littlepay.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
  benefits/static/img/modal-trigger--hover.svg
  benefits/static/img/modal-trigger--selected.svg
  benefits/static/img/modal-trigger.svg
Labels: front-end, i18n

#1508 Enrollment Success: Copy, illo, redesign
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/eligibility/templates/eligibility/start__login_gov.html
  benefits/enrollment/templates/enrollment/success.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
  benefits/static/img/enrollment-success-illustration.png
  benefits/static/img/login-gov-logo.svg
Labels: deployment-dev, back-end, i18n, migrations

#1515 Fix: Remove extra asterisks
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, i18n

#1517 Refactor: Eligibility index
  .vscode/settings.json
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/core/templates/core/includes/button--previous-page.html
  benefits/eligibility/templates/eligibility/index--mst.html
  benefits/eligibility/templates/eligibility/index--sacrt.html
  benefits/eligibility/templates/eligibility/index.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/conftest.py
  tests/pytest/eligibility/test_views.py
Labels: deployment-dev, front-end, back-end, i18n

#1522 Refactor: home button
  benefits/core/context_processors.py
  benefits/core/middleware.py
  benefits/core/templates/core/help.html
  benefits/core/templates/core/includes/button--home.html
  benefits/core/viewmodels.py
  benefits/core/views.py
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/settings.py
  benefits/templates/200_user_error.html
  benefits/templates/400.html
  benefits/templates/404.html
  benefits/templates/500.html
Labels: front-end, back-end

#1521 Refactor: agency links
  benefits/core/context_processors.py
  benefits/core/templates/core/help.html
  benefits/core/templates/core/includes/agency-links.html
  benefits/core/viewmodels.py
  benefits/core/views.py
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/eligibility/views.py
  benefits/enrollment/templates/enrollment/retry.html
  benefits/enrollment/views.py
  benefits/settings.py
  tests/pytest/core/test_views.py
Labels: tests, front-end, back-end, migrations

#1529 Chore: eligibility start copy
  benefits/eligibility/templates/eligibility/start.html
  benefits/eligibility/templates/eligibility/start__login_gov.html
  benefits/eligibility/templates/eligibility/start__mst_courtesy_card.html
  benefits/eligibility/templates/eligibility/start__veteran.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end, i18n

#1530 Feat: Eligibility Start senior modal
  benefits/eligibility/templates/eligibility/includes/media_item__idcardcheck__start__login_gov.html
  benefits/eligibility/templates/eligibility/includes/modal--senior-start-help.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end

#1534 Refactor: sign out button
  benefits/core/context_processors.py
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/core/templates/core/includes/sign-out-button--senior.html
  benefits/core/templates/core/includes/sign-out-link--senior.html
  benefits/core/templates/core/includes/sign-out-link.html
  benefits/core/viewmodels.py
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/enrollment/templates/enrollment/index.html
  benefits/enrollment/templates/enrollment/retry.html
  benefits/enrollment/templates/enrollment/success.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/conftest.py
  tests/pytest/core/test_models.py
  tests/pytest/enrollment/test_views.py
Labels: deployment-dev, front-end, back-end, i18n, migrations

#1531 Refactor: Eligibility unverified page
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/conftest.py
Labels: deployment-dev, back-end, i18n, migrations

#1536 Refactor: error pages
  benefits/core/middleware.py
  benefits/core/session.py
  benefits/core/viewmodels.py
  benefits/core/views.py
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/templates/200-user-error.html
  benefits/templates/400.html
  benefits/templates/404.html
  benefits/templates/500.html
  benefits/templates/error.html
  tests/pytest/core/test_middleware_healthcheck_user_agent.py
  tests/pytest/core/test_session.py
  tests/pytest/core/test_viewmodels.py
  tests/pytest/core/test_views.py
  tests/pytest/oauth/test_views.py
Labels: tests, front-end, back-end

#1540 Feat: external link icon
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
  benefits/static/img/external-link.svg
Labels: deployment-dev, front-end

#1541 Refactor: remove Transit Agency viewmodel
  benefits/core/context_processors.py
  benefits/core/templates/core/includes/modal--agency-selector.html
  benefits/core/templates/core/index.html
  benefits/core/viewmodels.py
  benefits/core/views.py
Labels: front-end, back-end

#1523 Eligibility Start: Contactless Pay Modal
  benefits/core/templates/core/includes/modal-trigger-link.html
  benefits/eligibility/templates/eligibility/includes/media-item--bankcardcheck--start.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--senior.html
  benefits/eligibility/templates/eligibility/includes/modal--contactless.html
  benefits/eligibility/templates/eligibility/includes/modal--senior-help.html
  benefits/eligibility/templates/eligibility/includes/modal--senior-start-help.html
  benefits/eligibility/templates/eligibility/includes/selection-label--senior.html
  benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
  benefits/enrollment/templates/enrollment/includes/modal--littlepay.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
Labels: deployment-dev, front-end, i18n

#1537 Fix: OAuth session checks and events
  benefits/enrollment/templates/enrollment/success.html
  benefits/oauth/analytics.py
  benefits/oauth/middleware.py
  benefits/oauth/views.py
  tests/pytest/core/test_middleware_login_required.py
  tests/pytest/core/test_middleware_verifier_required.py
  tests/pytest/oauth/test_analytics.py
  tests/pytest/oauth/test_middleware_authverifier_required.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev, tests, back-end, security

#1549 Elig Index: Remove required asterisks
  benefits/core/templates/core/widgets/verifier-radio-select.html
Labels: deployment-dev, front-end

#1550 Fixes: CSS column alignment
  benefits/core/templates/core/base.html
  benefits/core/templates/core/includes/form.html
  benefits/eligibility/forms.py
  benefits/eligibility/templates/eligibility/index.html
  benefits/eligibility/templates/eligibility/start--mst-courtesy-card.html
  benefits/eligibility/templates/eligibility/start--senior.html
  benefits/eligibility/templates/eligibility/start--veteran.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/enrollment/templates/enrollment/index.html
  benefits/static/css/styles.css
Labels: deployment-dev, front-end, back-end

#1547 Chore: Help page copy - About section
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, i18n

#1557 Fix: add missing sentence to contactless cards modal
  benefits/eligibility/templates/eligibility/includes/modal--contactless.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end

#1542 Refactor: remove icon/media item view models
  benefits/core/templates/core/includes/icon--direct-args.html
  benefits/core/templates/core/includes/icon-title.html
  benefits/core/templates/core/includes/icon.html
  benefits/core/templates/core/includes/media-list.html
  benefits/core/templates/core/logged-out.html
  benefits/core/viewmodels.py
  benefits/core/views.py
  benefits/eligibility/templates/eligibility/includes/media-item--bankcardcheck--start.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck.html
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/eligibility/views.py
  benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
  benefits/enrollment/templates/enrollment/retry.html
  benefits/enrollment/views.py
  benefits/templates/error.html
Labels: front-end, back-end

#1554 Fix: Question mark and color Login.gov sizing alignment
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1552 Fix: Eligibility Index - Radio button alignment
  benefits/core/templates/core/widgets/verifier-radio-select.html
Labels: deployment-dev, front-end

#1558 Chore: Help page - contactless cards section
  benefits/core/templates/core/help.html
  benefits/eligibility/templates/eligibility/includes/modal--contactless.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end, i18n

#1562 Refactor: buttons
  benefits/core/migrations/0002_data.py
  benefits/core/templates/core/agency-index.html
  benefits/core/templates/core/help.html
  benefits/core/templates/core/includes/button--origin.html
  benefits/core/templates/core/includes/button--sign-out--senior.html
  benefits/core/templates/core/includes/button.html
  benefits/core/templates/core/includes/link--sign-out--senior.html
  benefits/core/templates/core/includes/link--sign-out.html
  benefits/core/templates/core/includes/previous-page-link.html
  benefits/core/viewmodels.py
  benefits/core/views.py
  benefits/eligibility/templates/eligibility/confirm.html
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/eligibility/views.py
  benefits/enrollment/templates/enrollment/retry.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/templates/error.html
  tests/pytest/conftest.py
Labels: deployment-dev, tests, front-end, back-end, i18n, migrations

#1560 Chore: Help copy - agency card
  benefits/core/context_processors.py
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/core/templates/core/help.html
  benefits/core/templates/core/includes/help--mst.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end, i18n

#1569 Fix: Add alt text to index, agency index background image
  benefits/core/templates/core/landing.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#1561 Chore: Help copy - Littlepay
  benefits/core/templates/core/help.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end, i18n

#1570 Chore: punctuation for links
  benefits/core/templates/core/includes/modal-trigger-link.html
  benefits/eligibility/templates/eligibility/includes/selection-label--senior.html
  benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: i18n

#1563 Refactor: remove Page viewmodel
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/core/templates/core/agency-index.html
  benefits/core/templates/core/base.html
  benefits/core/templates/core/help.html
  benefits/core/templates/core/index--mst.html
  benefits/core/templates/core/index--sacrt.html
  benefits/core/templates/core/index.html
  benefits/core/templates/core/landing.html
  benefits/core/templates/core/logged-out.html
  benefits/core/viewmodels.py
  benefits/core/views.py
  benefits/eligibility/templates/eligibility/confirm.html
  benefits/eligibility/templates/eligibility/index.html
  benefits/eligibility/templates/eligibility/start--mst-courtesy-card.html
  benefits/eligibility/templates/eligibility/start--senior.html
  benefits/eligibility/templates/eligibility/start--veteran.html
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/eligibility/views.py
  benefits/enrollment/templates/enrollment/index.html
  benefits/enrollment/templates/enrollment/retry.html
  benefits/enrollment/templates/enrollment/success.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/templates/error.html
  tests/pytest/conftest.py
  tests/pytest/core/test_views.py
  tests/pytest/eligibility/test_views.py
Labels: tests, front-end, back-end, i18n, migrations
