Repository cal-itp/benefits, pull requests merged in 2024-03, with the labels that each got.

#1923 Docs: pin key requirements, fix extension syntax
  .github/dependabot.yml
  docs/requirements.txt
  mkdocs.yml
Labels: documentation, actions

#1909 Deploy to test
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .env.sample
  .github/dependabot.yml
  .github/workflows/check-api.yml
  .github/workflows/mkdocs.yml
  .github/workflows/tests-cypress.yml
  .github/workflows/tests-ui.yml
  .gitignore
  .pre-commit-config.yaml
  benefits/core/admin.py
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/migrations/sample_agency.json
  benefits/core/models.py
  benefits/secrets.py
  benefits/sentry.py
  benefits/settings.py
  benefits/static/img/icon/google_sso_logo.svg
  benefits/urls.py
  bin/init.sh
  bin/makemigrations.sh
  bin/reset_db.sh
  bin/test_start.sh
  docs/README.md
  docs/configuration/README.md
  docs/configuration/data.md
  docs/configuration/environment-variables.md
  docs/deployment/README.md
  docs/deployment/infrastructure.md
  docs/development/i18n.md
  docs/development/models-migrations.md
  docs/enrollment-pathways/README.md
  docs/enrollment-pathways/img/roadmap.png
  docs/enrollment-pathways/low-income.md
  docs/getting-started/README.md
  docs/product-and-design/.pages
  docs/product-and-design/copy-delivery.md
  docs/requirements.txt
  docs/tests/automated-tests.md
  mkdocs.yml
  pyproject.toml
  terraform/.terraform.lock.hcl
  terraform/app_service.tf
  terraform/storage.tf
  terraform/terraform.tfvars.sample
  tests/cypress/fixtures/README.md
  tests/cypress/fixtures/transit-agencies.js
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/pytest/conftest.py
  tests/pytest/core/test_admin.py
  tests/pytest/core/test_models.py
  tests/pytest/core/test_settings.py
  tests/pytest/test_secrets.py
  tests/pytest/test_settings.py
Labels: front-end, back-end, docker, actions, infrastructure, migrations

#1927 chore(release): update version to 2024.03.1
  pyproject.toml
Labels: deployment-dev

#1929 Release 2024.03.1
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .env.sample
  .github/dependabot.yml
  .github/workflows/check-api.yml
  .github/workflows/mkdocs.yml
  .github/workflows/tests-cypress.yml
  .github/workflows/tests-ui.yml
  .gitignore
  .pre-commit-config.yaml
  benefits/core/admin.py
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/migrations/sample_agency.json
  benefits/core/models.py
  benefits/secrets.py
  benefits/sentry.py
  benefits/settings.py
  benefits/static/img/icon/google_sso_logo.svg
  benefits/urls.py
  bin/init.sh
  bin/makemigrations.sh
  bin/reset_db.sh
  bin/test_start.sh
  docs/README.md
  docs/configuration/README.md
  docs/configuration/data.md
  docs/configuration/environment-variables.md
  docs/deployment/README.md
  docs/deployment/infrastructure.md
  docs/development/i18n.md
  docs/development/models-migrations.md
  docs/enrollment-pathways/README.md
  docs/enrollment-pathways/img/roadmap.png
  docs/enrollment-pathways/low-income.md
  docs/getting-started/README.md
  docs/product-and-design/.pages
  docs/product-and-design/copy-delivery.md
  docs/requirements.txt
  docs/tests/automated-tests.md
  mkdocs.yml
  pyproject.toml
  terraform/.terraform.lock.hcl
  terraform/app_service.tf
  terraform/storage.tf
  terraform/terraform.tfvars.sample
  tests/cypress/fixtures/README.md
  tests/cypress/fixtures/transit-agencies.js
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/pytest/conftest.py
  tests/pytest/core/test_admin.py
  tests/pytest/core/test_models.py
  tests/pytest/core/test_settings.py
  tests/pytest/test_secrets.py
  tests/pytest/test_settings.py
Labels: tests, front-end, back-end, docker

#1924 Docs: Add YouTube videos for enrollment pathways
  docs/enrollment-pathways/agency-cards.md
  docs/enrollment-pathways/img/senior-success.gif
  docs/enrollment-pathways/older-adults.md
  docs/enrollment-pathways/veterans.md
Labels: documentation

#1905 Refactor: enrollment with Backoffice API
  .env.sample
  benefits/core/migrations/0002_paymentprocessor_backoffice_api.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  benefits/enrollment/api.py
  benefits/enrollment/views.py
  pyproject.toml
  tests/pytest/conftest.py
  tests/pytest/enrollment/test_api_AccessTokenResponse.py
  tests/pytest/enrollment/test_api_Client.py
  tests/pytest/enrollment/test_api_CustomerResponse.py
  tests/pytest/enrollment/test_api_GroupResponse.py
  tests/pytest/enrollment/test_views.py
Labels: deployment-dev, tests, back-end, migrations

#1944 Chore: use calitp-littlepay from PyPI
  pyproject.toml
Labels: deployment-dev

#1945 Chore: bump version for 2024.03.2
  pyproject.toml
Labels: deployment-dev

#1947 Release 2024.03.2
  .env.sample
  .github/dependabot.yml
  .pre-commit-config.yaml
  benefits/core/migrations/0002_paymentprocessor_backoffice_api.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  benefits/enrollment/api.py
  benefits/enrollment/views.py
  benefits/sentry.py
  docs/enrollment-pathways/agency-cards.md
  docs/enrollment-pathways/img/senior-success.gif
  docs/enrollment-pathways/older-adults.md
  docs/enrollment-pathways/veterans.md
  docs/requirements.txt
  pyproject.toml
  tests/pytest/conftest.py
  tests/pytest/enrollment/test_api_AccessTokenResponse.py
  tests/pytest/enrollment/test_api_Client.py
  tests/pytest/enrollment/test_api_CustomerResponse.py
  tests/pytest/enrollment/test_api_GroupResponse.py
  tests/pytest/enrollment/test_views.py
Labels: tests, back-end, actions, migrations

#1960 Deploy SBMTD Agency card name updates to test
  .github/ISSUE_TEMPLATE/release.yml
  benefits/core/templates/core/includes/help--sbmtd.html
  benefits/eligibility/forms.py
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--sbmtd-mobility-pass.html
  benefits/eligibility/templates/eligibility/includes/selection-label--sbmtd-mobility-pass.html
  benefits/eligibility/templates/eligibility/start--sbmtd-mobility-pass.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  docs/tests/manual-tests.md
  pyproject.toml
Labels: front-end, i18n

#1961 Release SBMTD Agency card name updates
  .github/ISSUE_TEMPLATE/release.yml
  benefits/core/templates/core/includes/help--sbmtd.html
  benefits/eligibility/forms.py
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--sbmtd-mobility-pass.html
  benefits/eligibility/templates/eligibility/includes/selection-label--sbmtd-mobility-pass.html
  benefits/eligibility/templates/eligibility/start--sbmtd-mobility-pass.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  docs/tests/manual-tests.md
  pyproject.toml
Labels: front-end, back-end, i18n

#1957 Feat: EligibilityType model fields for expiration - validation on model
  benefits/core/migrations/0003_eligibilitytype_expiration.py
  benefits/core/models.py
  tests/pytest/core/test_models.py
Labels: deployment-dev, tests, back-end, migrations

#1958 Feat: add CalFresh option
  benefits/core/admin.py
  benefits/core/migrations/0004_alter_eligibilityverifier_display_order.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  benefits/eligibility/templates/eligibility/includes/modal--calfresh.html
  benefits/eligibility/templates/eligibility/includes/selection-label--calfresh.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/settings.py
  pyproject.toml
  tests/cypress/specs/benefit-select.cy.js
Labels: deployment-dev, front-end, migrations

#1962 Feat: CalFresh eligibility start
  benefits/core/migrations/local_fixtures.json
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--calfresh.html
  benefits/eligibility/templates/eligibility/start--calfresh.html
Labels: deployment-dev, front-end, migrations

#1974 Fix: path to coverage report
  docs/tests/automated-tests.md
Labels: documentation

#1976 Fix: allow custom media-item--heading tag
  benefits/core/templates/core/includes/media-item.html
  benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
Labels: bug, deployment-dev, front-end

#1970 Feat: CalFresh help info
  benefits/core/context_processors.py
  benefits/core/migrations/0005_move_help_template_to_eligibilityverifier.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  benefits/core/templates/core/help.html
  benefits/core/templates/core/includes/help--calfresh.html
  benefits/core/templates/core/includes/help--mst-courtesy-card.html
  benefits/core/templates/core/includes/help--sbmtd-mobility-pass.html
  benefits/eligibility/forms.py
  tests/pytest/conftest.py
  tests/pytest/core/test_context_processors.py
  tests/pytest/core/test_models.py
  tests/pytest/core/test_views.py
  tests/pytest/eligibility/test_views.py
Labels: deployment-dev, front-end, back-end

#1979 Fix(models): allow blank
  benefits/core/admin.py
  benefits/core/migrations/0006_alter_allow_blank.py
  benefits/core/models.py
Labels: bug, deployment-dev, back-end, migrations

#1985 Feat: store/retrieve enrollment expiry in session
  benefits/core/context_processors.py
  benefits/core/session.py
  tests/pytest/core/test_context_processors.py
  tests/pytest/core/test_session.py
Labels: deployment-dev, back-end

#1987 Fix: enrollment expiry session
  benefits/core/session.py
  benefits/settings.py
  tests/pytest/core/test_session.py
Labels: bug, deployment-dev, tests, back-end

#1984 Added Mermaid code to replace image of product roadmap
  docs/enrollment-pathways/README.md
  docs/enrollment-pathways/img/roadmap.png
Labels: documentation

#1991 Fix: catch grep failure so reset script doesn't die
  bin/reset_db.sh
Labels: bug, deployment-dev, chore
