Repository cal-itp/benefits, pull requests merged in 2024-11, with the labels that each got.

#2501 Updated status for SacRT
  docs/README.md
Labels: documentation

#2497 Fix: show favicon on the Superuser's admin
  benefits/templates/admin/base_site.html
Labels: front-end

#2507 Chore: change SacRT copy to say "bus" instead of "light rail"
  benefits/core/templates/core/index--sacrt.html
  benefits/eligibility/templates/eligibility/index--sacrt.html
  benefits/enrollment/templates/enrollment/success--sacrt.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: i18n

#2518 Chore: update copy on Eligiblity Index for SacRT
  benefits/eligibility/templates/eligibility/index--sacrt.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end, i18n

#2522 Feat: add webp CLI to devcontainer
  .devcontainer/Dockerfile
Labels: docker

#2524 Feat: fallback background color
  benefits/static/css/styles.css
Labels: front-end

#2523 Feat: use pre-loaded WebP background image on homepage
  benefits/core/templates/core/base.html
  benefits/core/templates/core/landing.html
  benefits/static/css/styles.css
  benefits/static/img/benefits-bg-desktop.jpg
  benefits/static/img/benefits-bg-desktop.webp
  benefits/static/img/benefits-bg-mobile.jpg
  benefits/static/img/benefits-bg-mobile.webp
Labels: deployment-dev, front-end

#2535 Refactor: remove Cypress
  .github/dependabot.yml
  .github/workflows/deploy.yml
  .github/workflows/tests-cypress.yml
  bin/test_start.sh
  docs/configuration/environment-variables.md
  docs/tests/automated-tests.md
  tests/cypress/.gitignore
  tests/cypress/cypress.config.js
  tests/cypress/fixtures/README.md
  tests/cypress/fixtures/transit-agencies.js
  tests/cypress/fixtures/users.json
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/cypress/plugins/eligibility.js
  tests/cypress/plugins/helpers.js
  tests/cypress/plugins/index.js
  tests/cypress/specs/agency-cards.cy.js
  tests/cypress/specs/benefit-select.cy.js
  tests/cypress/specs/help.cy.js
  tests/cypress/specs/rate-limit.cy.js
  tests/cypress/specs/scrapers.cy.js
  tests/cypress/specs/spanish.cy.js
Labels: documentation, deployment-dev, tests, actions

#2516 Fix: modal for 4 or more agencies
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#2526 Refactor: Remove CA State Web Template
  benefits/core/templates/core/base.html
  benefits/core/templates/core/includes/lang-selector.html
  benefits/core/templates/core/includes/nocookies.html
  benefits/core/templates/core/includes/noscript.html
  benefits/core/templates/core/landing.html
  benefits/in_person/templates/error-base.html
  benefits/in_person/templates/in_person/eligibility.html
  benefits/in_person/templates/in_person/enrollment/index.html
  benefits/in_person/templates/in_person/enrollment/success.html
  benefits/settings.py
  benefits/static/css/styles.css
  benefits/templates/admin/agency-dashboard-index.html
Labels: deployment-dev, front-end, back-end

#2548 Adding link to November update
  docs/product-and-design/newsletter-archive.md
Labels: documentation
