Repository cal-itp/benefits, pull requests merged in 2024-12, with the labels that each got.

#2557 Adding video walkthrough to Medicare cardholder use case
  docs/enrollment-pathways/medicare-cardholders.md
Labels: documentation

#2563 Chore: add back values for CST local fixture
  benefits/core/migrations/local_fixtures.json
Labels: deployment-dev, migrations

#2555 Fix: Use same Bootstrap version for both Admin and Benefits
  benefits/core/templates/core/base.html
  benefits/core/templates/core/includes/bootstrap-css.html
  benefits/templates/admin/agency-base.html
  benefits/templates/admin/includes/bootstrap.html
  benefits/templates/admin/login.html
Labels: deployment-dev, front-end

#2564 Refactor(reCAPTCHA): remove icons
  benefits/core/templates/core/includes/media-item.html
  benefits/eligibility/templates/eligibility/includes/media-item--contactless-card--start.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck.html
  benefits/eligibility/templates/eligibility/includes/media-item--identification--start--cst-agency-card.html
  benefits/eligibility/templates/eligibility/includes/media-item--identification--start--login-gov.html
  benefits/eligibility/templates/eligibility/includes/media-item--identification--start--medicare.html
  benefits/eligibility/templates/eligibility/includes/media-item--identification--start--mst-agency-card.html
  benefits/eligibility/templates/eligibility/includes/media-item--identification--start--sbmtd-agency-card.html
  benefits/eligibility/templates/eligibility/start--calfresh.html
  benefits/eligibility/templates/eligibility/start--cst-agency-card.html
  benefits/eligibility/templates/eligibility/start--medicare.html
  benefits/eligibility/templates/eligibility/start--mst-agency-card.html
  benefits/eligibility/templates/eligibility/start--sbmtd-agency-card.html
  benefits/eligibility/templates/eligibility/start--senior.html
  benefits/eligibility/templates/eligibility/start--veteran.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/enrollment/templates/enrollment/includes/media-item--contactless-card--index--calfresh.html
  benefits/enrollment/templates/enrollment/includes/media-item--contactless-card--index.html
  benefits/enrollment/templates/enrollment/index--calfresh.html
  benefits/enrollment/templates/enrollment/index.html
  benefits/static/css/styles.css
  benefits/static/img/icon/bankcardcheck.svg
  benefits/static/img/icon/idcardcheck.svg
Labels: deployment-dev, front-end

#2573 reCAPTCHA: Eligibility Start
  benefits/core/templates/core/includes/media-item.html
  benefits/eligibility/templates/eligibility/includes/media-item--contactless-card--start.html
  benefits/eligibility/templates/eligibility/includes/media-item--identification--start--cst-agency-card.html
  benefits/eligibility/templates/eligibility/includes/media-item--identification--start--login-gov.html
  benefits/eligibility/templates/eligibility/includes/media-item--identification--start--medicare.html
  benefits/eligibility/templates/eligibility/includes/media-item--identification--start--mst-agency-card.html
  benefits/eligibility/templates/eligibility/includes/media-item--identification--start--sbmtd-agency-card.html
  benefits/eligibility/templates/eligibility/start--calfresh.html
  benefits/eligibility/templates/eligibility/start--cst-agency-card.html
  benefits/eligibility/templates/eligibility/start--medicare.html
  benefits/eligibility/templates/eligibility/start--senior.html
  benefits/eligibility/templates/eligibility/start--veteran.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/enrollment/templates/enrollment/includes/media-item--contactless-card--index.html
  benefits/enrollment/templates/enrollment/index--calfresh.html
  benefits/enrollment/templates/enrollment/index.html
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#2575 reCAPTCHA: Enrollment index
  benefits/core/templates/core/base.html
  benefits/enrollment/templates/enrollment/includes/alert-box--warning--calfresh.html
  benefits/enrollment/templates/enrollment/includes/media-item--contactless-card--index--calfresh.html
  benefits/enrollment/templates/enrollment/includes/media-item--contactless-card--index.html
  benefits/enrollment/templates/enrollment/index--agency-card.html
  benefits/enrollment/templates/enrollment/index--calfresh.html
  benefits/enrollment/templates/enrollment/index.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
Labels: i18n

#2583 Fix/Refactor: Eligibility Start
  benefits/core/templates/core/includes/eligibility-item.html
  benefits/eligibility/templates/eligibility/includes/eligibility-item--contactless-card--start.html
  benefits/eligibility/templates/eligibility/includes/eligibility-item--identification--start--cst-agency-card.html
  benefits/eligibility/templates/eligibility/includes/eligibility-item--identification--start--login-gov.html
  benefits/eligibility/templates/eligibility/includes/eligibility-item--identification--start--medicare.html
  benefits/eligibility/templates/eligibility/includes/eligibility-item--identification--start--mst-agency-card.html
  benefits/eligibility/templates/eligibility/includes/eligibility-item--identification--start--sbmtd-agency-card.html
  benefits/eligibility/templates/eligibility/start--calfresh.html
  benefits/eligibility/templates/eligibility/start--cst-agency-card.html
  benefits/eligibility/templates/eligibility/start--medicare.html
  benefits/eligibility/templates/eligibility/start--mst-agency-card.html
  benefits/eligibility/templates/eligibility/start--sbmtd-agency-card.html
  benefits/eligibility/templates/eligibility/start--senior.html
  benefits/eligibility/templates/eligibility/start--veteran.html
  benefits/eligibility/templates/eligibility/start.html
Labels: front-end

#2579 reCAPTCHA: Enrollment Success, Logged Out
  benefits/core/templates/core/logged-out.html
  benefits/enrollment/templates/enrollment/success.html
Labels: front-end

#2587 Product roadmap updates
  benefits/static/css/variables.css
  docs/enrollment-pathways/README.md
Labels: documentation

#2589 chore(pre-commit): run autofix
  benefits/static/css/variables.css
Labels: front-end

#2592 Updating agency adoption table
  docs/README.md
Labels: documentation

#2584 reCAPTCHA: Help page
  benefits/core/templates/core/help.html
Labels: front-end

#2585 reCAPTCHA: Error pages
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/enrollment/templates/enrollment/reenrollment-error--calfresh.html
  benefits/enrollment/templates/enrollment/reenrollment-error-base.html
  benefits/enrollment/templates/enrollment/retry.html
  benefits/enrollment/templates/enrollment/system_error.html
  benefits/oauth/templates/oauth/system_error.html
  benefits/static/css/styles.css
  benefits/templates/200-user-error.html
  benefits/templates/400.html
  benefits/templates/404.html
  benefits/templates/500.html
  benefits/templates/error-base.html
  benefits/templates/error.html
  tests/pytest/core/test_models.py
Labels: front-end

#2594 Roadmap adjustments
  docs/enrollment-pathways/README.md
Labels: documentation

#2595 Fix: Docs site theme and Roadmap style
  docs/enrollment-pathways/README.md
  docs/styles/theme.css
  mkdocs.yml
Labels: documentation
