Repository cal-itp/benefits, pull requests merged in 2024-02, with the labels that each got.

#1871 docs: README.md > SBMTD Mobility Pass status
  docs/README.md
Labels: documentation

#1855 Admin: Add Google SSO for Compiler users
  benefits/core/admin.py
  benefits/settings.py
  benefits/static/img/icon/google_sso_logo.svg
  benefits/urls.py
  pyproject.toml
  terraform/app_service.tf
Labels: deployment-dev, back-end

#1859 Feat: helper script to read KeyVault secrets
  .devcontainer/Dockerfile
  .env.sample
  benefits/secrets.py
  benefits/sentry.py
  benefits/settings.py
  benefits/urls.py
  docs/configuration/environment-variables.md
  docs/getting-started/README.md
  pyproject.toml
  tests/pytest/test_secrets.py
  tests/pytest/test_settings.py
Labels: deployment-dev, back-end

#1874 Refactor: model secret fields
  .env.sample
  .github/workflows/tests-cypress.yml
  .github/workflows/tests-ui.yml
  benefits/core/migrations/0001_initial.py
  benefits/core/migrations/0002_data.py
  benefits/core/models.py
  benefits/secrets.py
  terraform/app_service.tf
  tests/pytest/conftest.py
  tests/pytest/core/test_models.py
  tests/pytest/test_secrets.py
Labels: tests, back-end, security, migrations

#1885 Update .pages remove design style guide page
  docs/product-and-design/.pages
Labels: documentation

#1890 Secrets: update guidance and parsing for local multiline env vars
  .env.sample
  benefits/secrets.py
  docs/configuration/environment-variables.md
  tests/pytest/test_secrets.py
Labels: documentation

#1886 Feat: configure Azure file share backup
  docs/deployment/infrastructure.md
  terraform/.terraform.lock.hcl
  terraform/storage.tf
  terraform/terraform.tfvars.sample
Labels: documentation, infrastructure

#1872 Low-income use case
  docs/enrollment-pathways/low-income.md
Labels: documentation

#1889 Refactor: use cal-itp/littlepay to check API access
  .github/workflows/check-api.yml
Labels: actions

#1891 Update README.md removed directive from Mermaid chart
  docs/enrollment-pathways/README.md
Labels: documentation

#1893 fix(docs): clean up front-matter
  docs/enrollment-pathways/README.md
Labels: documentation

#1892 Update low-income.md changed ordered list markdown to all 1s
  docs/enrollment-pathways/low-income.md
Labels: documentation

#1894 docs(roadmap): use an image for now
  docs/enrollment-pathways/README.md
  docs/enrollment-pathways/img/roadmap.png
Labels: documentation

#1881 Refactor: Django admin always enabled
  .devcontainer/devcontainer.json
  .env.sample
  .github/workflows/tests-cypress.yml
  .gitignore
  benefits/core/admin.py
  benefits/core/migrations/0002_data.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/migrations/sample_agency.json
  benefits/settings.py
  benefits/urls.py
  bin/init.sh
  bin/makemigrations.sh
  bin/reset_db.sh
  bin/test_start.sh
  docs/README.md
  docs/configuration/README.md
  docs/configuration/data.md
  docs/configuration/environment-variables.md
  docs/deployment/README.md
  docs/development/i18n.md
  docs/development/models-migrations.md
  docs/getting-started/README.md
  docs/tests/automated-tests.md
  terraform/app_service.tf
  tests/cypress/fixtures/README.md
  tests/cypress/fixtures/transit-agencies.js
  tests/pytest/core/test_admin.py
  tests/pytest/core/test_settings.py
Labels: documentation, tests, back-end, infrastructure

#1904 Fix: correct Google SSO secret names
  terraform/app_service.tf
Labels: bug, infrastructure

#1910 Fix: check for existing preview comment before adding one
  .github/workflows/mkdocs.yml
Labels: documentation, actions

#1911 added low-income pathway to table within supported enrollment pathways
  docs/README.md
Labels: documentation

#1914 Fix: sample env and reset_db helper
  .env.sample
  bin/reset_db.sh
Labels: bug, deployment-dev
