Repository cal-itp/benefits, pull requests merged in 2024-04, with the labels that each got.

#1968 Feat: CalFresh enrollment index
  benefits/core/migrations/0007_eligibilitytype_enrollment_index_template.py
  benefits/core/models.py
  benefits/core/templates/core/base.html
  benefits/core/templates/core/includes/alert-box.html
  benefits/enrollment/templates/enrollment/includes/alert-box--warning--calfresh.html
  benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index--calfresh.html
  benefits/enrollment/templates/enrollment/index--calfresh.html
  benefits/enrollment/templates/enrollment/index.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
  tests/pytest/core/test_models.py
  tests/pytest/enrollment/test_views.py
Labels: deployment-dev, tests, front-end, back-end, migrations

#1989 Feat: enrollments can expire
  benefits/enrollment/templates/enrollment/reenrollment-error.html
  benefits/enrollment/views.py
  benefits/settings.py
  tests/pytest/conftest.py
  tests/pytest/enrollment/test_views.py
Labels: deployment-dev, tests, back-end

#1998 Updated initial agency launch date for MST
  docs/README.md
Labels: documentation

#2017 fix(docker): remove platform attribute from server service
  compose.yml
Labels: docker

#2018 Updates to Cal-ITP Benefits product roadmap
  docs/enrollment-pathways/README.md
Labels: documentation

#2020 Q2 Benefits product roadmap updates
  docs/enrollment-pathways/README.md
Labels: documentation

#2027 fix(devcontainer): configure git to install pre-commit
  .devcontainer/postAttach.sh
Labels: docker

#2037 Fix: unnecessary space on required form field label
  benefits/core/templates/core/includes/form.html
Labels: deployment-dev

#2023 Feat: update eligibility index copy for improved UX
  benefits/eligibility/forms.py
  benefits/eligibility/templates/eligibility/includes/selection-label--mst-courtesy-card.html
  benefits/eligibility/templates/eligibility/includes/selection-label--sbmtd-mobility-pass.html
  benefits/eligibility/templates/eligibility/index--mst.html
  benefits/eligibility/templates/eligibility/index--sbmtd.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/cypress/plugins/helpers.js
Labels: deployment-dev, front-end, i18n

#2043 Fix: update param name for expiry
  benefits/enrollment/views.py
  tests/pytest/enrollment/test_views.py
Labels: bug, tests, back-end

#2039 Chore: update 500 error page
  benefits/core/templates/core/includes/button--index.html
  benefits/core/templates/core/includes/button--origin.html
  benefits/core/templates/core/includes/nocookies.html
  benefits/core/templates/core/includes/noscript.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/templates/500.html
  benefits/templates/error.html
Labels: deployment-dev, front-end, i18n

#2040 Chore: update enrollment retry page
  benefits/enrollment/templates/enrollment/retry.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/enrollment/test_views.py
Labels: tests, front-end, back-end, i18n

#2026 Feat: eligibility confirm copy and UX
  benefits/core/templates/core/base.html
  benefits/core/templates/core/includes/form.html
  benefits/eligibility/forms.py
  benefits/eligibility/templates/eligibility/confirm.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
Labels: deployment-dev, back-end, i18n

#2042 Feat: eligibility start update copy
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--mst-courtesy-card.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--sbmtd-mobility-pass.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end

#2045 Feat(eligibility/form): custom validation message for index and confirm fields
  benefits/core/templates/core/includes/form.html
  benefits/eligibility/forms.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/eligibility/test_forms.py
Labels: deployment-dev, front-end, back-end, i18n

#2052 Revert "Feat: enrollments can expire (#1989)"
  benefits/enrollment/templates/enrollment/reenrollment-error.html
  benefits/enrollment/views.py
  benefits/settings.py
  tests/pytest/conftest.py
  tests/pytest/enrollment/test_views.py
Labels: deployment-dev, tests, front-end, back-end

#2047 Feat: enrollment index update copy
  benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
  benefits/enrollment/templates/enrollment/index.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/cypress/specs/courtesy-cards.cy.js
Labels: deployment-dev
