Repository cal-itp/benefits, pull requests merged in 2024-05, with the labels that each got.

#2056 Feat: add properties for UTM codes
  benefits/core/analytics.py
  tests/pytest/core/test_analytics.py
Labels: deployment-dev, back-end, analytics

#2053 Refactor: agency card eligibility error
  benefits/core/migrations/0008_eligibilityverifier_unverified_template.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  benefits/eligibility/templates/eligibility/unverified--mst-courtesy-card.html
  benefits/eligibility/templates/eligibility/unverified--sbmtd-mobility-pass.html
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/cypress/specs/courtesy-cards.cy.js
  tests/pytest/eligibility/test_views.py
Labels: tests, front-end, back-end

#1992 Feat: CalFresh re-enrollment error
  benefits/core/migrations/0009_eligibilitytype_reenrollment_error_template.py
  benefits/core/models.py
  benefits/enrollment/templates/enrollment/reenrollment-error--calfresh.html
  benefits/enrollment/templates/enrollment/reenrollment-error-base.html
  benefits/enrollment/urls.py
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/conftest.py
  tests/pytest/core/test_models.py
  tests/pytest/enrollment/test_views.py
Labels: tests, i18n, migrations

#2069 Feat: CalFresh Spanish updates
  benefits/core/templates/core/includes/help--calfresh.html
  benefits/eligibility/templates/eligibility/includes/modal--calfresh.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end, i18n

#2070 Feat: CalFresh Spanish updates
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end, i18n

#2071 Feat: CalFresh Spanish updates
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end, i18n

#2078 Fix: model cleanups for the Admin
  benefits/core/models.py
  tests/pytest/core/test_models.py
Labels: deployment-dev, migrations

#2079 Fix: enrollment index headline
  benefits/core/migrations/local_fixtures.json
  benefits/enrollment/templates/enrollment/index--agency-card.html
  benefits/enrollment/templates/enrollment/index.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end, i18n

#2083 CI: initialize Dependabot PR effort to 1
  .github/workflows/add-to-project-dependabot.yml
Labels: chore, actions

#2090 Fix: correct syntax in field update step
  .github/workflows/add-to-project-dependabot.yml
Labels: bug, actions

#2091 Fix: allow mkdocs preview job to write comments on PRs
  .github/workflows/mkdocs.yml
Labels: bug, documentation, actions

#2086 Chore: update eligibilityverifier and pemdata migrations
  benefits/core/migrations/0010_alter_secret_name_field_blank.py
Labels: deployment-dev, back-end, migrations

#2093 Feat: Spanish translations for Agency Card Eligibility Error page
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, i18n

#2095 Feat: Spanish translations for 500, user enrollment error
  benefits/enrollment/templates/enrollment/retry.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end, i18n

#2094 Feat: Agency Card Eligibility Confirm Spanish translations
  benefits/enrollment/templates/enrollment/retry.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, i18n

#2099 Prepare Release 2024.05.1
  pyproject.toml
Labels: deployment-dev

#2106 Roadmap revisions
  docs/enrollment-pathways/README.md
Labels: documentation

#2067 Feat: enrollment success
  benefits/core/migrations/0011_move_enrollment_success_template_field.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  benefits/enrollment/templates/enrollment/success--mst-courtesy-card.html
  benefits/enrollment/templates/enrollment/success--mst.html
  benefits/enrollment/templates/enrollment/success--sacrt.html
  benefits/enrollment/templates/enrollment/success--sbmtd-mobility-pass.html
  benefits/enrollment/templates/enrollment/success--sbmtd.html
  benefits/enrollment/templates/enrollment/success.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/conftest.py
  tests/pytest/core/test_models.py
  tests/pytest/enrollment/test_views.py
Labels: deployment-dev, front-end

#2088 Feat: system enrollment error - 500 error when linking
  benefits/enrollment/templates/enrollment/system_error.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
  benefits/templates/error.html
  tests/pytest/enrollment/test_views.py
Labels: deployment-dev, front-end, back-end

#2111 CI: deploy Azure Web App with GitHub Actions
  .github/workflows/deploy.yml
Labels: actions, infrastructure

#2089 Feat: system enrollment error - 500 error during /token
  benefits/enrollment/analytics.py
  benefits/enrollment/templates/enrollment/index.html
  benefits/enrollment/urls.py
  benefits/enrollment/views.py
  tests/pytest/enrollment/test_analytics.py
  tests/pytest/enrollment/test_views.py
Labels: front-end, back-end

#2104 Chore: update docs on tagging a release
  docs/deployment/release.md
Labels: documentation, infrastructure

#2116 Refactor: use integer claims in OAuth
  benefits/oauth/views.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev, back-end

#2122 CI: check for up-to-date migrations
  .github/workflows/check-makemigrations.yml
Labels: actions

#2127 Fix: test assertions for missing claim on AuthProvider
  tests/pytest/conftest.py
  tests/pytest/eligibility/test_verify.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/enrollment/test_views.py
  tests/pytest/oauth/test_analytics.py
  tests/pytest/oauth/test_middleware_authverifier_required.py
  tests/pytest/oauth/test_views.py
Labels: bug, tests
