Repository cal-itp/benefits, pull requests merged in 2024-01, with the labels that each got.

#1840 Docs: fix small typo
  docs/README.md
Labels: documentation

#1842 Docs: update landing page
  docs/README.md
Labels: documentation

#1845 Feat: docs site previews for Pull Requests
  .github/workflows/mkdocs.yml
Labels: documentation, actions

#1846 docs(analytics): add table for default user props
  docs/product-and-design/analytics.md
Labels: documentation

#1857 Skip to main content link
  benefits/core/templates/core/base.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
Labels: front-end, i18n

#1862 Fix: update GitHub branch for sample eligibility server config
  .devcontainer/server/settings.py
  benefits/core/migrations/0002_data.py
Labels: bug, back-end, docker, migrations

#1866 Chore: add steps/notes for smoke testing to release plan template
  .github/ISSUE_TEMPLATE/release.yml
Labels: chore, tests

#1868 Chore: bump version for 2024.01.1
  pyproject.toml
Labels: deployment-dev
