Repository cal-itp/benefits, pull requests merged in 2024-08, with the labels that each got.

#2262 Refactor: `PaymentProcessor` to `TransitProcessor`
  .env.sample
  benefits/core/admin.py
  benefits/core/migrations/0016_refactor_paymentprocessor_transitprocessor.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  benefits/enrollment/analytics.py
  benefits/enrollment/views.py
  docs/README.md
  docs/configuration/data.md
  docs/configuration/transit-agency.md
  docs/development/application-logic.md
  docs/enrollment-pathways/low-income.md
  docs/enrollment-pathways/veterans.md
  docs/product-and-design/use-cases/enrollment-use-cases.md
  tests/pytest/conftest.py
  tests/pytest/core/test_models.py
Labels: deployment-dev, tests, back-end, migrations

#2256 Refactor: `AuthProvider` to `ClaimsProvider`
  .env.sample
  benefits/core/admin.py
  benefits/core/context_processors.py
  benefits/core/middleware.py
  benefits/core/migrations/0017_refactor_authprovider_claimsprovider.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  benefits/eligibility/verify.py
  benefits/eligibility/views.py
  benefits/enrollment/views.py
  benefits/oauth/analytics.py
  benefits/oauth/client.py
  benefits/oauth/middleware.py
  benefits/oauth/views.py
  docs/README.md
  docs/configuration/oauth.md
  docs/configuration/transit-agency.md
  tests/pytest/conftest.py
  tests/pytest/core/test_middleware_login_required.py
  tests/pytest/core/test_models.py
  tests/pytest/eligibility/test_verify.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/enrollment/test_views.py
  tests/pytest/oauth/test_analytics.py
  tests/pytest/oauth/test_client.py
  tests/pytest/oauth/test_middleware_authverifier_required.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev, back-end, migrations

#2275 Roadmap update
  docs/enrollment-pathways/README.md
Labels: documentation

#2272 Refactor: rename `EligibilityVerifier` eligibility fields
  benefits/core/admin.py
  benefits/core/migrations/0018_rename_eligibility_api_fields.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  benefits/eligibility/verify.py
  benefits/eligibility/views.py
  benefits/oauth/middleware.py
  docs/configuration/transit-agency.md
  tests/pytest/conftest.py
  tests/pytest/core/test_models.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/oauth/test_middleware_authverifier_required.py
Labels: tests, back-end, migrations

#2277 Fix: Eligibility Confirm - Unnest explanatory-text-wrapper div
  benefits/core/templates/core/base.html
Labels: deployment-dev

#2289 Fix: Elig Index - Wrap explanatory text in centered row
  benefits/eligibility/templates/eligibility/index.html
Labels: deployment-dev, front-end

#2280 Refactor: `TransitAgency` Eligibility API fields
  benefits/core/admin.py
  benefits/core/migrations/0019_refactor_transitagency.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  benefits/core/views.py
  benefits/eligibility/verify.py
  tests/pytest/conftest.py
  tests/pytest/core/test_views.py
Labels: deployment-dev, tests, back-end, migrations

#2291 Refactor: move IdG config to EligibilityVerifier
  benefits/core/admin.py
  benefits/core/migrations/0020_refactor_idg_config_eligibilityverifier.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  benefits/eligibility/verify.py
  benefits/oauth/client.py
  benefits/oauth/views.py
  docs/configuration/oauth.md
  tests/pytest/conftest.py
  tests/pytest/core/test_models.py
  tests/pytest/eligibility/test_verify.py
  tests/pytest/oauth/test_client.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev, migrations

#2293 Refactor: rename `EligibilityVerifier` to `EnrollmentFlow`
  .env.sample
  benefits/core/admin.py
  benefits/core/analytics.py
  benefits/core/context_processors.py
  benefits/core/middleware.py
  benefits/core/migrations/0014_staff_group_view_permissions.py
  benefits/core/migrations/0016_refactor_paymentprocessor_transitprocessor.py
  benefits/core/migrations/0017_refactor_authprovider_claimsprovider.py
  benefits/core/migrations/0021_rename_eligibilityverifier_enrollmentflow.py
  benefits/core/migrations/__init__.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  benefits/core/session.py
  benefits/core/templates/core/widgets/flow-radio-select-option.html
  benefits/core/templates/core/widgets/flow-radio-select.html
  benefits/core/widgets.py
  benefits/eligibility/forms.py
  benefits/eligibility/verify.py
  benefits/eligibility/views.py
  benefits/enrollment/views.py
  benefits/oauth/analytics.py
  benefits/oauth/client.py
  benefits/oauth/middleware.py
  benefits/oauth/views.py
  docs/configuration/oauth.md
  docs/configuration/transit-agency.md
  docs/development/commits-branches-merging.md
  tests/cypress/specs/benefit-select.cy.js
  tests/pytest/conftest.py
  tests/pytest/core/test_analytics.py
  tests/pytest/core/test_middleware_login_required.py
  tests/pytest/core/test_middleware_verifier_required.py
  tests/pytest/core/test_models.py
  tests/pytest/core/test_session.py
  tests/pytest/core/test_views.py
  tests/pytest/eligibility/conftest.py
  tests/pytest/eligibility/test_verify.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/enrollment/test_views.py
  tests/pytest/oauth/test_analytics.py
  tests/pytest/oauth/test_client.py
  tests/pytest/oauth/test_middleware.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev, tests, front-end, migrations

#2300 Feat: introduce separate app for in-person eligibility / enrollment
  benefits/in_person/__init__.py
  benefits/in_person/apps.py
  benefits/in_person/templates/in_person/eligibility.html
  benefits/in_person/templates/in_person/enrollment.html
  benefits/in_person/urls.py
  benefits/in_person/views.py
  benefits/settings.py
  benefits/urls.py
  tests/pytest/in_person/test_views.py
Labels: deployment-dev, front-end, back-end

#2304 Hide native Django login fields
  benefits/settings.py
Labels: deployment-dev, back-end

#2306 Create medicare-cardholders use case
  docs/enrollment-pathways/medicare-cardholders.md
Labels: documentation

#2299 Refactor: move EligibilityType fields to EnrollmentFlow
  benefits/core/admin.py
  benefits/core/analytics.py
  benefits/core/context_processors.py
  benefits/core/migrations/0022_refactor_EligibilityType_EnrollmentFlow.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  benefits/core/session.py
  benefits/eligibility/analytics.py
  benefits/eligibility/verify.py
  benefits/eligibility/views.py
  benefits/enrollment/views.py
  benefits/oauth/middleware.py
  docs/configuration/transit-agency.md
  tests/pytest/conftest.py
  tests/pytest/core/test_analytics.py
  tests/pytest/core/test_context_processors.py
  tests/pytest/core/test_models.py
  tests/pytest/core/test_session.py
  tests/pytest/eligibility/test_analytics.py
  tests/pytest/eligibility/test_verify.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/enrollment/test_views.py
Labels: deployment-dev, back-end, migrations

#2253 Adding Medicare cardholders
  docs/README.md
Labels: documentation

#2307 Feat: transit agency user group
  benefits/core/migrations/0023_transitagency_staff_group.py
  benefits/core/models.py
  tests/pytest/core/test_models.py
Labels: deployment-dev, tests, back-end

#2309 Fix: getting a group's transit agency
  benefits/core/models.py
  tests/pytest/core/test_models.py
Labels: tests

#2308 Refactor: centralize management of Django routes
  benefits/core/context_processors.py
  benefits/core/middleware.py
  benefits/core/models.py
  benefits/core/session.py
  benefits/core/templates/core/agency-index.html
  benefits/core/templates/core/base.html
  benefits/core/templates/core/includes/button--index.html
  benefits/core/templates/core/includes/button--sign-out--login-gov.html
  benefits/core/templates/core/includes/link--sign-out.html
  benefits/core/templates/core/includes/nocookies.html
  benefits/core/templates/core/includes/noscript.html
  benefits/core/urls.py
  benefits/core/views.py
  benefits/eligibility/forms.py
  benefits/eligibility/templates/eligibility/confirm.html
  benefits/eligibility/templates/eligibility/index.html
  benefits/eligibility/templates/eligibility/start--calfresh.html
  benefits/eligibility/templates/eligibility/start--cst-agency-card.html
  benefits/eligibility/templates/eligibility/start--mst-courtesy-card.html
  benefits/eligibility/templates/eligibility/start--sbmtd-mobility-pass.html
  benefits/eligibility/templates/eligibility/start--senior.html
  benefits/eligibility/templates/eligibility/start--veteran.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/eligibility/urls.py
  benefits/eligibility/views.py
  benefits/enrollment/forms.py
  benefits/enrollment/templates/enrollment/index.html
  benefits/enrollment/templates/enrollment/system_error.html
  benefits/enrollment/urls.py
  benefits/enrollment/views.py
  benefits/in_person/urls.py
  benefits/in_person/views.py
  benefits/oauth/middleware.py
  benefits/oauth/redirects.py
  benefits/oauth/urls.py
  benefits/oauth/views.py
  benefits/routes.py
  benefits/settings.py
  tests/pytest/core/test_context_processors.py
  tests/pytest/core/test_middleware_healthcheck_user_agent.py
  tests/pytest/core/test_middleware_login_required.py
  tests/pytest/core/test_session.py
  tests/pytest/core/test_views.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/enrollment/test_views.py
  tests/pytest/in_person/test_views.py
  tests/pytest/oauth/test_middleware.py
  tests/pytest/oauth/test_redirects.py
  tests/pytest/oauth/test_views.py
  tests/pytest/test_routes.py
Labels: chore, tests, front-end, back-end, migrations

#2315 Admin: Test that transit user does not get added to calitp group
  tests/pytest/core/test_admin.py
Labels: tests

#2318 Create newsletter-archive.md
  docs/product-and-design/.pages
  docs/product-and-design/newsletter-archive.md
Labels: documentation

#2312 Feat: Agency card direct route
  benefits/core/models.py
  benefits/core/urls.py
  benefits/core/views.py
  benefits/eligibility/urls.py
  benefits/eligibility/views.py
  benefits/routes.py
  tests/cypress/plugins/helpers.js
  tests/cypress/specs/spanish.cy.js
  tests/pytest/conftest.py
  tests/pytest/core/test_models.py
  tests/pytest/core/test_views.py
  tests/pytest/eligibility/test_verify.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/enrollment/test_views.py
  tests/pytest/oauth/test_views.py
Labels: back-end, migrations

#2313 Feat: transit agency home dashboard
  benefits/admin.py
  benefits/apps.py
  benefits/core/admin.py
  benefits/settings.py
  benefits/static/css/admin/styles.css
  benefits/static/css/styles.css
  benefits/static/css/variables.css
  benefits/templates/admin/agency-dashboard-index.html
  tests/pytest/core/test_admin.py
  tests/pytest/test_admin.py
Labels: deployment-dev, front-end, back-end

#2323 Feat: create base template for in-person eligibility
  benefits/templates/admin/agency-base.html
  benefits/templates/admin/agency-dashboard-index.html
Labels: deployment-dev, front-end

#2324 Feat: implement the top-right usertools block
  benefits/static/css/admin/styles.css
  benefits/static/img/icon/box-arrow-right.svg
  benefits/templates/admin/agency-base.html
Labels: deployment-dev, front-end

#2325 Feat: automatically associate user to agency
  benefits/admin.py
  benefits/core/admin.py
  benefits/core/migrations/0024_transitagency_sso_domain_customer_service.py
  benefits/core/models.py
  benefits/templates/admin/agency-dashboard-index.html
  tests/pytest/core/test_admin.py
  tests/pytest/test_admin.py
Labels: deployment-dev, tests, back-end, migrations

#2329 Chore: Admin - Add jQuery to agency base template
  benefits/templates/admin/agency-base.html
Labels: deployment-dev, front-end
