Repository cal-itp/benefits, pull requests merged in 2024-10, with the labels that each got.

#2401 Refactor: analytics for `claims_provider`
  benefits/eligibility/analytics.py
  benefits/eligibility/views.py
  benefits/in_person/views.py
  benefits/oauth/analytics.py
  docs/development/application-logic.md
  docs/product-and-design/analytics.md
  tests/pytest/eligibility/test_views.py
  tests/pytest/oauth/test_analytics.py
Labels: documentation, deployment-dev, tests

#2403 Refactor Enrollment Flow for consistent labeling across apps
  benefits/core/admin.py
  benefits/core/migrations/0028_remove_transitagency_enrollment_flows_and_more.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  tests/pytest/conftest.py
  tests/pytest/core/test_models.py
  tests/pytest/core/test_views.py
  tests/pytest/in_person/test_views.py
Labels: deployment-dev

#2420 Eligibility: Filter enrollment flows by supported method
  benefits/eligibility/forms.py
  benefits/in_person/forms.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/in_person/test_views.py
Labels: tests, back-end

#2424 Chore: move in-person enrollment template
  benefits/in_person/templates/in_person/enrollment/index.html
  benefits/in_person/views.py
  tests/pytest/in_person/test_views.py
Labels: deployment-dev, front-end, back-end

#2422 Refactor: test name clean-up and assertions for in-person analytics
  tests/pytest/in_person/test_views.py
Labels: tests

#2438 Fix: remove extra "have" from English Medicare copy
  benefits/core/templates/core/includes/help--medicare.html
  benefits/eligibility/templates/eligibility/includes/modal--medicare.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, i18n

#2430 Chore: extract common Admin overrides
  benefits/templates/admin/agency-base.html
  benefits/templates/admin/includes/bootstrap.html
  benefits/templates/admin/includes/branding-login.html
  benefits/templates/admin/includes/favicon.html
  benefits/templates/admin/includes/style-admin.html
  benefits/templates/admin/includes/usertools.html
  benefits/templates/admin/login.html
  benefits/templates/registration/logged_out.html
Labels: deployment-dev, front-end

#2447 Chore: remove "Change password" link from admin interface for now
  benefits/templates/admin/includes/usertools.html
Labels: front-end

#2450 Refactor: rename the finished card tokenization event
  benefits/enrollment/templates/enrollment/index.html
  benefits/in_person/templates/in_person/enrollment/index.html
  docs/development/application-logic.md
  docs/product-and-design/analytics.md
Labels: documentation, front-end, analytics

#2446 Fix: add to CSP_FRAME_SRC
  benefits/settings.py
Labels: bug, deployment-dev, back-end

#2456 Enrollment Index: Remove space after Littlepay
  benefits/enrollment/templates/enrollment/includes/media-item--bankcardcheck--index.html
Labels: deployment-dev, front-end

#2457 Docs: add note about Compiler to both READMEs
  README.md
  docs/README.md
Labels: documentation

#2461 Update status of low-income pathway
  docs/README.md
Labels: documentation

#2392 Refactor: Multi-stage Docker build for app image
  .devcontainer/Dockerfile
  .dockerignore
  appcontainer/Dockerfile
  pyproject.toml
Labels: deployment-dev, docker

#2460 Footer: Add Compiler line
  benefits/core/templates/core/base.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end, i18n

#2455 Enrollment Success: Reduce h1 parent container width for readability
  benefits/enrollment/templates/enrollment/success.html
Labels: deployment-dev, front-end

#2453 Chore: setup Nevada County Connects in `test`
  benefits/core/templates/core/index--nevco.html
  benefits/eligibility/templates/eligibility/index--nevco.html
  benefits/enrollment/templates/enrollment/success--nevco.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/img/agencies/nevco-lg.svg
  benefits/static/img/agencies/nevco-sm.svg
Labels: deployment-dev, front-end

#2465 Feat: add Slack thread to Release issues
  .github/ISSUE_TEMPLATE/release.yml
Labels: chore

#2466 Docs: update copy delivery process documentation
  docs/product-and-design/copy-delivery.md
  docs/product-and-design/img/ditto-import-components.png
  docs/product-and-design/img/figma-ditto-plugin.png
Labels: documentation

#2463 Feat: process multiple claims on a flow
  benefits/core/migrations/0029_add_extra_claims.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  benefits/core/session.py
  benefits/eligibility/verify.py
  benefits/eligibility/views.py
  benefits/oauth/views.py
  tests/pytest/conftest.py
  tests/pytest/core/test_models.py
  tests/pytest/core/test_session.py
  tests/pytest/eligibility/test_verify.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev, tests, back-end, migrations

#2473 Updates to Agency Adoption table
  docs/README.md
Labels: documentation

#2481 Eligibility + Docs: U.S. not US
  benefits/core/migrations/local_fixtures.json
  benefits/eligibility/templates/eligibility/includes/selection-label--veteran.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  docs/enrollment-pathways/veterans.md
  docs/product-and-design/copy-style.md
Labels: documentation, deployment-dev, front-end, i18n

#2480 Error pages: Make text area narrower for better legibility
  benefits/templates/error.html
Labels: deployment-dev, front-end

#2486 Eligibility page: Use Agency Cardholder, not Agency Card
  benefits/core/migrations/local_fixtures.json
  benefits/eligibility/templates/eligibility/includes/selection-label--cst-agency-card.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end, migrations

#2495 Chore: update SacRT logo files
  benefits/static/img/agencies/sacrt-lg.svg
  benefits/static/img/agencies/sacrt-sm.svg
Labels: deployment-dev, front-end

#2479 Feat: analytics for multiple claims on a flow
  benefits/core/migrations/0030_enrollmentevent_extra_claims.py
  benefits/core/models.py
  benefits/core/session.py
  benefits/enrollment/analytics.py
  benefits/enrollment/views.py
  benefits/oauth/views.py
  tests/pytest/conftest.py
  tests/pytest/core/test_session.py
  tests/pytest/enrollment/test_analytics.py
  tests/pytest/enrollment/test_views.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev, tests
