Repository cal-itp/benefits, pull requests merged in 2024-06, with the labels that each got.

#2117 Feat: server error - 400 errors / other exceptions during /token
  benefits/core/urls.py
  benefits/core/views.py
  benefits/enrollment/templates/enrollment/index.html
  benefits/enrollment/views.py
  tests/pytest/enrollment/test_views.py
Labels: tests, back-end

#2131 Chore: remove obsolete Compose version key
  compose.yml
Labels: chore, docker

#2128 Docs: deployment process to Azure Web App
  docs/deployment/README.md
Labels: documentation, infrastructure

#2132 CI: remove path filters from migration check
  .github/workflows/check-makemigrations.yml
Labels: actions

#2123 Refactor: terraform app service deployment
  docs/deployment/README.md
  docs/deployment/infrastructure.md
  docs/deployment/workflows.md
  terraform/app_service.tf
Labels: documentation, infrastructure

#2137 CI: guard against empty language array for CodeQL runs
  .github/workflows/codeql.yml
Labels: chore, actions

#2140 Fix: correct invalid syntax in CodeQL
  .github/workflows/codeql.yml
Labels: chore, actions

#2138 Refactor: delete app setting meant for refreshing secrets
  terraform/app_service.tf
Labels: infrastructure

#2141 Fix: terraform source control block
  terraform/app_service.tf
Labels: infrastructure

#2125 Feat: analytics for auth claims flow
  benefits/oauth/analytics.py
  benefits/oauth/views.py
  tests/pytest/oauth/test_analytics.py
  tests/pytest/oauth/test_views.py
Labels: tests, back-end

#2144 Chore: QA Spanish translations for agency card
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, i18n

#2146 Chore: update Terraform version in pipeline
  terraform/pipeline/deploy.yml
Labels: infrastructure

#2148 Chore: update version
  pyproject.toml
Labels: deployment-dev

#2154 Refactor(tests): Update eligibility type enrollment index template test
  tests/pytest/core/test_models.py
Labels: tests

#2155 Feat: check makemessages
  .github/workflows/check-migrations-and-messages.yml
Labels: actions

#2139 Docs: overview of the application logic
  docs/development/.pages
  docs/development/application-logic.md
Labels: documentation

#2156 Refactor: move the application directory up a level
  .devcontainer/devcontainer.json
  .devcontainer/postAttach.sh
  appcontainer/Dockerfile
  appcontainer/nginx.conf
  compose.yml
  terraform/app_service.tf
Labels: chore, docker, infrastructure

#2158 Feat: default dependabot PR status to In review
  .github/workflows/add-to-project-dependabot.yml
Labels: actions

#2152 Refactor(oauth): resolve RuntimeWarning
  benefits/oauth/apps.py
  benefits/oauth/client.py
  benefits/oauth/views.py
  docs/configuration/oauth.md
  tests/pytest/oauth/test_app.py
  tests/pytest/oauth/test_client.py
Labels: chore, back-end

#2160 Fix: terraform source control block
  terraform/app_service.tf
Labels: infrastructure

#2163 Revert "fix(terraform): turn on manual integration"
  terraform/app_service.tf
Labels: infrastructure

#2162 Roadmap updates
  docs/enrollment-pathways/README.md
Labels: documentation

#2159 Docs: clean up / reorganize Infrastructure documentation
  docs/deployment/infrastructure.md
Labels: documentation, infrastructure

#2166 Feat: enable app service storage
  terraform/app_service.tf
Labels: infrastructure

#2169 Fix: verifier help templates
  benefits/core/context_processors.py
Labels: deployment-dev, back-end

#2171 CI: add pre-commit PRs to project
  .github/workflows/add-to-project-dependabot.yml
Labels: chore, actions

#2165 Feat: enrollments can expire
  benefits/core/migrations/local_fixtures.json
  benefits/enrollment/views.py
  benefits/settings.py
  tests/pytest/conftest.py
  tests/pytest/enrollment/test_views.py
Labels: deployment-dev, tests, back-end

#2180 Refactor: consolidate Login.gov media item templates
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--login-gov.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--senior.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--veteran.html
  benefits/eligibility/templates/eligibility/start--calfresh.html
  benefits/eligibility/templates/eligibility/start--senior.html
  benefits/eligibility/templates/eligibility/start--veteran.html
Labels: deployment-dev, front-end

#2179 Fix: changing languages on the enrollment success page
  benefits/core/templates/core/includes/lang-selector.html
  benefits/enrollment/views.py
Labels: deployment-dev, back-end
