Repository cal-itp/benefits, pull requests merged in 2024-07, with the labels that each got.

#2185 Fix: oauth client not registered exception in logout
  benefits/oauth/views.py
Labels: deployment-dev, back-end

#2193 Chore: bump version for 2024.07.1
  pyproject.toml
Labels: deployment-dev

#2194 Deploy 2024.07.1 to test
  .github/workflows/deploy.yml
  .github/workflows/tests-ui.yml
  .pre-commit-config.yaml
  benefits/core/migrations/local_fixtures.json
  benefits/core/templates/core/includes/lang-selector.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--login-gov.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--senior.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--veteran.html
  benefits/eligibility/templates/eligibility/start--calfresh.html
  benefits/eligibility/templates/eligibility/start--senior.html
  benefits/eligibility/templates/eligibility/start--veteran.html
  benefits/enrollment/views.py
  benefits/oauth/views.py
  benefits/settings.py
  docs/requirements.txt
  pyproject.toml
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/pytest/conftest.py
  tests/pytest/enrollment/test_views.py
Labels: tests, front-end, actions

#2196 Release 2024.07.1
  .github/workflows/deploy.yml
  .github/workflows/tests-ui.yml
  .pre-commit-config.yaml
  benefits/core/migrations/local_fixtures.json
  benefits/core/templates/core/includes/lang-selector.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--login-gov.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--senior.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--veteran.html
  benefits/eligibility/templates/eligibility/start--calfresh.html
  benefits/eligibility/templates/eligibility/start--senior.html
  benefits/eligibility/templates/eligibility/start--veteran.html
  benefits/enrollment/views.py
  benefits/oauth/views.py
  benefits/settings.py
  docs/requirements.txt
  pyproject.toml
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/pytest/conftest.py
  tests/pytest/enrollment/test_views.py
Labels: tests, front-end, back-end, actions, migrations

#2197 Feat: templates and copy for California State Transit
  benefits/core/templates/core/includes/help--cst-agency-card.html
  benefits/core/templates/core/index--cst.html
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--cst-agency-card.html
  benefits/eligibility/templates/eligibility/includes/selection-label--cst-agency-card.html
  benefits/eligibility/templates/eligibility/index--cst.html
  benefits/eligibility/templates/eligibility/start--cst-agency-card.html
  benefits/eligibility/templates/eligibility/unverified--cst-agency-card.html
  benefits/enrollment/templates/enrollment/success--cst-agency-card.html
  benefits/enrollment/templates/enrollment/success--cst.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/img/agencies/cst-lg.svg
  benefits/static/img/agencies/cst-sm.svg
Labels: deployment-dev, front-end

#2204 Q3 Benefits Roadmap Update
  docs/enrollment-pathways/README.md
Labels: documentation

#2202 Chore: Rename `dev` branch to `main`
  .github/ISSUE_TEMPLATE/release.yml
  .github/workflows/codeql.yml
  .github/workflows/deploy.yml
  .github/workflows/labeler-deploy-dev.yml
  .github/workflows/labeler-docs.yml
  .github/workflows/labeler-infrastructure.yml
  .github/workflows/mkdocs.yml
  .github/workflows/tests-ui.yml
  benefits/secrets.py
  docs/configuration/README.md
  docs/configuration/data.md
  docs/configuration/oauth.md
  docs/deployment/README.md
  docs/deployment/infrastructure.md
  docs/deployment/release.md
  docs/deployment/workflows.md
  docs/development/README.md
  docs/development/application-logic.md
  docs/development/commits-branches-merging.md
  docs/development/i18n.md
  docs/development/models-migrations.md
  docs/getting-started/README.md
  docs/getting-started/documentation.md
  docs/product-and-design/analytics.md
  docs/product-and-design/copy-delivery.md
  docs/tests/automated-tests.md
  terraform/azure-pipelines.yml
  terraform/pipeline/deploy.yml
  terraform/pipeline/workspace.py
Labels: tests, actions

#2205 Fix: CST templates
  benefits/eligibility/forms.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/eligibility/test_forms.py
Labels: deployment-dev, i18n

#2209 Deploy CST templates to test
  .github/ISSUE_TEMPLATE/release.yml
  .github/workflows/codeql.yml
  .github/workflows/deploy.yml
  .github/workflows/labeler-deploy-dev.yml
  .github/workflows/labeler-docs.yml
  .github/workflows/labeler-infrastructure.yml
  .github/workflows/mkdocs.yml
  .github/workflows/tests-ui.yml
  benefits/core/templates/core/includes/help--cst-agency-card.html
  benefits/core/templates/core/index--cst.html
  benefits/eligibility/forms.py
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--cst-agency-card.html
  benefits/eligibility/templates/eligibility/includes/selection-label--cst-agency-card.html
  benefits/eligibility/templates/eligibility/index--cst.html
  benefits/eligibility/templates/eligibility/start--cst-agency-card.html
  benefits/eligibility/templates/eligibility/unverified--cst-agency-card.html
  benefits/enrollment/templates/enrollment/success--cst-agency-card.html
  benefits/enrollment/templates/enrollment/success--cst.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/secrets.py
  benefits/static/img/agencies/cst-lg.svg
  benefits/static/img/agencies/cst-sm.svg
  docs/configuration/README.md
  docs/configuration/data.md
  docs/configuration/oauth.md
  docs/deployment/README.md
  docs/deployment/infrastructure.md
  docs/deployment/release.md
  docs/deployment/workflows.md
  docs/development/README.md
  docs/development/application-logic.md
  docs/development/commits-branches-merging.md
  docs/development/i18n.md
  docs/development/models-migrations.md
  docs/enrollment-pathways/README.md
  docs/getting-started/README.md
  docs/getting-started/documentation.md
  docs/product-and-design/analytics.md
  docs/product-and-design/copy-delivery.md
  docs/requirements.txt
  docs/tests/automated-tests.md
  pyproject.toml
  terraform/azure-pipelines.yml
  terraform/pipeline/deploy.yml
  terraform/pipeline/workspace.py
  tests/cypress/package-lock.json
  tests/cypress/package.json
  tests/pytest/eligibility/test_forms.py
Labels: tests, front-end, back-end, i18n, actions

#2212 Remove unused merchant_id field
  benefits/core/migrations/0012_remove_transitagency_merchant_id.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  tests/pytest/conftest.py
Labels: deployment-dev, tests, back-end, migrations

#2207 Fix: Eligibility Index - Clicking on modal backdrop should not click radio button
  benefits/eligibility/templates/eligibility/index.html
Labels: deployment-dev, front-end

#2217 Update Benefits Project Overview
  docs/README.md
Labels: documentation

#2214 Chore: Clean up localfixtures, env, Cypress tests to only have CST
  .env.sample
  benefits/core/migrations/local_fixtures.json
  tests/cypress/plugins/helpers.js
  tests/cypress/specs/agency-cards.cy.js
  tests/cypress/specs/benefit-select.cy.js
  tests/cypress/specs/rate-limit.cy.js
Labels: deployment-dev, migrations

#2213 Refactor: implement tag-based deployment
  .devcontainer/Dockerfile
  .devcontainer/postAttach.sh
  .dockerignore
  .github/workflows/check-migrations-and-messages.yml
  .github/workflows/deploy.yml
  .github/workflows/tests-cypress.yml
  .github/workflows/tests-pytest.yml
  .github/workflows/tests-ui.yml
  appcontainer/Dockerfile
  pyproject.toml
  terraform/azure-pipelines.yml
  terraform/pipeline/deploy.yml
  terraform/pipeline/tag.py
  terraform/pipeline/workspace.py
  tests/pytest/test_version.py
Labels: actions

#2224 Feat: Cal-ITP staff can view configuration values
  benefits/core/admin.py
  benefits/core/migrations/0014_staff_group_view_permissions.py
Labels: back-end, migrations

#2226 Feat: Cal-ITP staff edit
  benefits/core/admin.py
  benefits/core/migrations/0015_staff_group_edit_permissions.py
Labels: back-end, migrations

#2227 Feat: handle OAuth errors
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/oauth/analytics.py
  benefits/oauth/middleware.py
  benefits/oauth/redirects.py
  benefits/oauth/templates/oauth/system_error.html
  benefits/oauth/urls.py
  benefits/oauth/views.py
  tests/pytest/oauth/test_analytics.py
  tests/pytest/oauth/test_middleware_authverifier_required.py
  tests/pytest/oauth/test_redirects.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev, tests, front-end, back-end, i18n

#2239 Chore: update local fixtures with sample CalFresh AuthProvider
  benefits/core/migrations/local_fixtures.json
Labels: migrations

#2232 Fix: terraform plan and apply conditions
  terraform/azure-pipelines.yml
  terraform/pipeline/deploy.yml
  terraform/pipeline/tag.py
Labels: bug, infrastructure

#2250 Feat: set language code on Littlepay overlay
  benefits/enrollment/templates/enrollment/index.html
  benefits/enrollment/views.py
  tests/pytest/enrollment/test_views.py
Labels: deployment-dev, front-end

#2254 Chore: normalize lines for tag_type
  terraform/pipeline/deploy.yml
  terraform/pipeline/tag.py
Labels: infrastructure
