Repository cal-itp/benefits, pull requests merged in 2024-09, with the labels that each got.

#2317 Admin: Eligibility View
  benefits/in_person/forms.py
  benefits/in_person/templates/in_person/eligibility.html
  benefits/in_person/views.py
  benefits/routes.py
  benefits/static/css/admin/styles.css
  tests/pytest/in_person/test_views.py
Labels: deployment-dev, front-end

#2338 Refactor: introduce enrollment module
  benefits/enrollment/enrollment.py
  benefits/enrollment/views.py
  tests/pytest/enrollment/test_enrollment.py
  tests/pytest/enrollment/test_views.py
Labels: deployment-dev, tests, back-end

#2347 Admin test: Use settings instead of mocker
  tests/pytest/core/test_admin.py
Labels: tests

#2348 Refactor: enrollment token logic
  benefits/enrollment/enrollment.py
  benefits/enrollment/views.py
  tests/pytest/enrollment/test_enrollment.py
  tests/pytest/enrollment/test_views.py
Labels: deployment-dev, tests, back-end

#2360 Enrollment success: All flows now have same success headline copy
  benefits/enrollment/templates/enrollment/success--cst-agency-card.html
  benefits/enrollment/templates/enrollment/success--mst-courtesy-card.html
  benefits/enrollment/templates/enrollment/success--sbmtd-mobility-pass.html
  benefits/enrollment/templates/enrollment/success.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, front-end, i18n

#2361 Feat: customize the login form using an environment variable
  benefits/settings.py
  terraform/app_service.tf
Labels: deployment-dev, back-end, infrastructure

#2362 Refactor: use client to test the BenefitsAdminSite view
  tests/pytest/test_admin.py
Labels: tests

#2340 Feat: in-person enrollment view
  benefits/in_person/forms.py
  benefits/in_person/templates/in_person/enrollment.html
  benefits/in_person/templates/in_person/enrollment/reenrollment_error.html
  benefits/in_person/templates/in_person/enrollment/retry.html
  benefits/in_person/templates/in_person/enrollment/server_error.html
  benefits/in_person/templates/in_person/enrollment/success.html
  benefits/in_person/templates/in_person/enrollment/system_error.html
  benefits/in_person/urls.py
  benefits/in_person/views.py
  benefits/routes.py
  benefits/settings.py
  benefits/static/css/admin/styles.css
  tests/pytest/in_person/test_views.py
Labels: tests, front-end

#2366 Medicare: Eligibility Index - Modal and Radio Button Label
  benefits/core/migrations/local_fixtures.json
  benefits/eligibility/templates/eligibility/includes/modal--medicare.html
  benefits/eligibility/templates/eligibility/includes/selection-label--medicare.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/cypress/specs/benefit-select.cy.js
Labels: i18n, migrations

#2368 Feat: Medicare cardholder eligibility start template
  benefits/eligibility/templates/eligibility/includes/media-item--idcardcheck--start--medicare.html
  benefits/eligibility/templates/eligibility/start--medicare.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, tests, front-end, i18n, migrations

#2367 Feat: model and capture local `EnrollmentEvent`
  benefits/core/admin.py
  benefits/core/migrations/0026_enrollmentevent.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  benefits/enrollment/views.py
  benefits/in_person/views.py
  benefits/settings.py
  tests/pytest/conftest.py
  tests/pytest/core/test_models.py
  tests/pytest/enrollment/test_views.py
  tests/pytest/in_person/test_views.py
  tests/pytest/test_admin.py
Labels: deployment-dev, tests, back-end, migrations

#2371 Admin: Log in page
  benefits/static/css/admin/styles.css
  benefits/templates/admin/agency-base.html
  benefits/templates/admin/login.html
Labels: front-end, back-end

#2378 Feat: success template for in-person enrollment
  benefits/in_person/templates/in_person/enrollment/success.html
  benefits/in_person/views.py
  benefits/static/css/admin/styles.css
  benefits/static/img/icon/check-circle-fill.svg
Labels: front-end, back-end

#2382 Feat: error templates for in-person enrollment
  benefits/in_person/templates/error-base.html
  benefits/in_person/templates/in_person/enrollment/reenrollment_error.html
  benefits/in_person/templates/in_person/enrollment/retry.html
  benefits/in_person/templates/in_person/enrollment/server_error.html
  benefits/in_person/templates/in_person/enrollment/system_error.html
  benefits/in_person/views.py
  benefits/static/css/admin/styles.css
  benefits/static/img/icon/exclamation-circle-fill.svg
  tests/pytest/in_person/test_views.py
Labels: front-end, back-end

#2379 Refactor: analytics for `EnrollmentFlow`
  benefits/core/analytics.py
  benefits/core/models.py
  benefits/eligibility/analytics.py
  benefits/eligibility/views.py
  benefits/enrollment/views.py
  docs/product-and-design/analytics.md
  tests/pytest/core/test_analytics.py
  tests/pytest/core/test_models.py
  tests/pytest/eligibility/test_analytics.py
Labels: documentation, deployment-dev, back-end

#2383 Add `supported_methods` field to `EnrollmentFlow`
  benefits/core/migrations/0027_enrollmentflow_supported_methods.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models.py
  pyproject.toml
  tests/pytest/core/test_models.py
Labels: deployment-dev, tests, back-end, migrations

#2400 Added link to the September newsletter
  docs/product-and-design/newsletter-archive.md
Labels: documentation

#2391 Refactor: analytics for PaymentProcessor
  benefits/enrollment/analytics.py
  benefits/enrollment/templates/enrollment/index.html
  docs/development/application-logic.md
  docs/product-and-design/analytics.md
Labels: documentation, deployment-dev, back-end

#2397 Admin: Log out page styled
  benefits/templates/registration/logged_out.html
Labels: deployment-dev, front-end

#2405 Refactor: remove "Go back" button from in-person enrollment
  benefits/in_person/templates/in_person/enrollment.html
Labels: deployment-dev, front-end

#2409 Admin: Use "log" not "sign"
  benefits/settings.py
  benefits/templates/admin/agency-base.html
Labels: deployment-dev, back-end

#2406 Medicare: Add Medicare copy for Spanish
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: deployment-dev, i18n

#2413 Status update for Medicare cardholders
  docs/README.md
Labels: documentation

#2415 Feat: add help template for Medicare
  benefits/core/migrations/local_fixtures.json
  benefits/core/templates/core/includes/help--medicare.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
Labels: front-end, migrations

#2417 End of Q3 roadmap updates
  docs/enrollment-pathways/README.md
Labels: documentation

#2410 Admin: Update admin page titles
  benefits/admin.py
  benefits/in_person/templates/error-base.html
  benefits/in_person/templates/in_person/eligibility.html
  benefits/in_person/templates/in_person/enrollment.html
  benefits/in_person/templates/in_person/enrollment/success.html
  benefits/in_person/views.py
  benefits/templates/admin/agency-base.html
  benefits/templates/admin/agency-dashboard-index.html
  benefits/templates/admin/login.html
  benefits/templates/registration/logged_out.html
  tests/pytest/in_person/test_views.py
Labels: deployment-dev, front-end, back-end
