Repository cal-itp/benefits, pull requests merged in 2025-03, with the labels that each got.

#2717 docs: roadmap updates
  docs/enrollment-pathways/README.md
Labels: documentation

#2735 docs: marking nevada county live
  docs/README.md
Labels: documentation

#2700 Refactor: IdG sign out to use client_id
  benefits/core/session.py
  benefits/oauth/redirects.py
  benefits/oauth/views.py
  tests/pytest/conftest.py
  tests/pytest/core/test_middleware_login_required.py
  tests/pytest/core/test_session.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/oauth/test_redirects.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev, back-end

#2705 Refactor: simplify Eligibility Index templates
  benefits/core/admin/transit.py
  benefits/core/migrations/0037_remove_transitagency_eligibility_index_template_override.py
  benefits/core/models/transit.py
  benefits/eligibility/context/__init__.py
  benefits/eligibility/context/agency.py
  benefits/eligibility/templates/eligibility/index--cst.html
  benefits/eligibility/templates/eligibility/index--mst.html
  benefits/eligibility/templates/eligibility/index--nevco.html
  benefits/eligibility/templates/eligibility/index--sacrt.html
  benefits/eligibility/templates/eligibility/index--sbmtd.html
  benefits/eligibility/templates/eligibility/index.html
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/conftest.py
  tests/pytest/core/admin/test_transit.py
  tests/pytest/core/context/__init__.py
  tests/pytest/core/models/test_transit.py
  tests/pytest/eligibility/context/__init__.py
  tests/pytest/eligibility/context/test_agency.py
  tests/pytest/eligibility/test_views.py
Labels: deployment-dev, tests, front-end, back-end, i18n, migrations

#2747 Refactor: install cdt_identity app
  benefits/settings.py
  pyproject.toml
Labels: deployment-dev, back-end

#2750 Docs: remove reference to `index_template` and `eligibility_index_template`
  docs/configuration/transit-agency.md
Labels: documentation

#2752 docs: update to mermaid diagram
  docs/enrollment-pathways/medicare-cardholders.md
Labels: documentation

#2748 Admin: Disable sidebar
  benefits/admin.py
Labels: deployment-dev, back-end

#2726 Refactor: simplify Eligibility Start templates
  benefits/core/admin/enrollment.py
  benefits/core/migrations/0038_remove_enrollmentflow_eligibility_start_template_override.py
  benefits/core/models/enrollment.py
  benefits/eligibility/context/__init__.py
  benefits/eligibility/context/flow.py
  benefits/eligibility/templates/eligibility/start--calfresh.html
  benefits/eligibility/templates/eligibility/start--cst-agency-card.html
  benefits/eligibility/templates/eligibility/start--medicare.html
  benefits/eligibility/templates/eligibility/start--mst-agency-card.html
  benefits/eligibility/templates/eligibility/start--sbmtd-agency-card.html
  benefits/eligibility/templates/eligibility/start--senior.html
  benefits/eligibility/templates/eligibility/start--veteran.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  docs/configuration/transit-agency.md
  tests/pytest/conftest.py
  tests/pytest/core/admin/test_enrollment.py
  tests/pytest/core/models/test_enrollment.py
  tests/pytest/eligibility/context/test_flow.py
  tests/pytest/eligibility/test_views.py
Labels: front-end, back-end

#2753 Refactor: Flow help templates
  benefits/core/admin/enrollment.py
  benefits/core/context/__init__.py
  benefits/core/context/flow.py
  benefits/core/context_processors.py
  benefits/core/migrations/0039_remove_enrollmentflow_help_template.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models/enrollment.py
  benefits/core/templates/core/help.html
  benefits/core/templates/core/includes/help--calfresh.html
  benefits/core/templates/core/includes/help--cst-agency-card.html
  benefits/core/templates/core/includes/help--medicare.html
  benefits/core/templates/core/includes/help--mst-courtesy-card.html
  benefits/core/templates/core/includes/help--sbmtd-mobility-pass.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  docs/configuration/transit-agency.md
  tests/pytest/core/admin/test_enrollment.py
Labels: deployment-dev, i18n, migrations

#2761 docs: link to march benefits newsletter
  docs/product-and-design/newsletter-archive.md
Labels: documentation

#2757 Feat: OAuth hooks for `login` view
  benefits/oauth/hooks.py
  tests/pytest/oauth/test_hooks.py
Labels: deployment-dev, tests, back-end

#2772 docs: changes to agency adoption table
  docs/README.md
Labels: documentation

#2762 Refactor: Unverified agency card templates
  benefits/core/admin/enrollment.py
  benefits/core/migrations/0040_remove_enrollmentflow_eligibility_unverified_template_override.py
  benefits/core/models/enrollment.py
  benefits/eligibility/context/__init__.py
  benefits/eligibility/context/flow.py
  benefits/eligibility/templates/eligibility/unverified--cst-agency-card.html
  benefits/eligibility/templates/eligibility/unverified--mst-agency-card.html
  benefits/eligibility/templates/eligibility/unverified--sbmtd-agency-card.html
  benefits/eligibility/templates/eligibility/unverified-error-agency-base.html
  benefits/eligibility/templates/eligibility/unverified.html
  benefits/eligibility/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/conftest.py
  tests/pytest/core/admin/test_enrollment.py
  tests/pytest/core/models/test_enrollment.py
  tests/pytest/eligibility/context/test_flow.py
Labels: deployment-dev, back-end, i18n, migrations

#2768 Feat: OAuth hooks for `cancel` view
  benefits/oauth/hooks.py
  tests/pytest/oauth/test_hooks.py
Labels: tests

#2769 Feat: OAuth hooks for `logout` view
  benefits/oauth/hooks.py
  tests/pytest/oauth/test_hooks.py
Labels: tests, back-end

#2770 Feat: OAuth hooks for `post_logout` view
  benefits/oauth/hooks.py
  tests/pytest/oauth/test_hooks.py
Labels: tests, back-end

#2774 Refactor: remove eligibility item templates
  benefits/core/templates/core/includes/eligibility-item.html
  benefits/eligibility/context/flow.py
  benefits/eligibility/templates/eligibility/includes/eligibility-item--contactless-card--start.html
  benefits/eligibility/templates/eligibility/includes/eligibility-item--identification--start--cst-agency-card.html
  benefits/eligibility/templates/eligibility/includes/eligibility-item--identification--start--login-gov.html
  benefits/eligibility/templates/eligibility/includes/eligibility-item--identification--start--medicare.html
  benefits/eligibility/templates/eligibility/includes/eligibility-item--identification--start--mst-agency-card.html
  benefits/eligibility/templates/eligibility/includes/eligibility-item--identification--start--sbmtd-agency-card.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/eligibility/context/test_flow.py
Labels: deployment-dev, front-end, back-end

#2758 Refactor: use `IdentityGatewayConfig` model from `cdt_identity`
  benefits/core/admin/__init__.py
  benefits/core/admin/claims.py
  benefits/core/admin/enrollment.py
  benefits/core/context_processors.py
  benefits/core/migrations/0041_oauth_refactor_identitygatewayconfig.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models/__init__.py
  benefits/core/models/claims.py
  benefits/core/models/enrollment.py
  benefits/enrollment/views.py
  benefits/oauth/analytics.py
  benefits/oauth/client.py
  benefits/oauth/views.py
  docs/configuration/oauth.md
  tests/pytest/conftest.py
  tests/pytest/core/admin/test_claims.py
  tests/pytest/core/admin/test_enrollment.py
  tests/pytest/core/models/test_claims.py
  tests/pytest/core/models/test_enrollment.py
  tests/pytest/core/test_middleware_login_required.py
  tests/pytest/enrollment/test_views.py
  tests/pytest/oauth/test_analytics.py
  tests/pytest/oauth/test_client.py
  tests/pytest/oauth/test_middleware.py
Labels: deployment-dev, tests, back-end

#2785 Fix: `EnrollmentFlowForm` test and validation
  benefits/core/admin/enrollment.py
  tests/pytest/core/admin/test_enrollment.py
Labels: deployment-dev, tests, back-end

#2776 Refactor: simplify Enrollment Success templates
  benefits/core/admin/enrollment.py
  benefits/core/migrations/0042_remove_enrollmentflow_enrollment_success_template_override.py
  benefits/core/models/enrollment.py
  benefits/enrollment/context/__init__.py
  benefits/enrollment/context/flow.py
  benefits/enrollment/templates/enrollment/success--cst-agency-card.html
  benefits/enrollment/templates/enrollment/success--cst.html
  benefits/enrollment/templates/enrollment/success--mst-agency-card.html
  benefits/enrollment/templates/enrollment/success--mst.html
  benefits/enrollment/templates/enrollment/success--nevco.html
  benefits/enrollment/templates/enrollment/success--sacrt.html
  benefits/enrollment/templates/enrollment/success--sbmtd-agency-card.html
  benefits/enrollment/templates/enrollment/success--sbmtd.html
  benefits/enrollment/templates/enrollment/success.html
  benefits/enrollment/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  docs/configuration/transit-agency.md
  tests/pytest/conftest.py
  tests/pytest/core/admin/test_enrollment.py
  tests/pytest/core/models/test_enrollment.py
  tests/pytest/enrollment/test_views.py
Labels: documentation, deployment-dev, tests, front-end, back-end, migrations

#2782 Refactor: use `ClaimsVerificationRequest` model from `cdt_identity`
  benefits/core/admin/enrollment.py
  benefits/core/migrations/0043_enrollmentflow_claims_request.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models/enrollment.py
  benefits/core/session.py
  benefits/eligibility/verify.py
  benefits/oauth/client.py
  benefits/oauth/views.py
  tests/pytest/conftest.py
  tests/pytest/core/admin/test_enrollment.py
  tests/pytest/core/models/test_enrollment.py
  tests/pytest/core/test_session.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev, tests, migrations

#2773 Admin: Header theme, remove darkmode toggle & breadcrumb theme
  benefits/static/css/admin/styles.css
  benefits/static/css/admin/theme.css
  benefits/templates/admin/agency-base.html
  benefits/templates/admin/agency-dashboard-index.html
  benefits/templates/admin/base.html
  benefits/templates/admin/base_site.html
  benefits/templates/admin/flow-base.html
  benefits/templates/admin/includes/branding-login.html
  benefits/templates/admin/includes/branding.html
  benefits/templates/admin/includes/favicon.html
  benefits/templates/admin/includes/style-admin.html
  benefits/templates/admin/includes/usertools.html
  benefits/templates/admin/login.html
  benefits/templates/registration/logged_out.html
Labels: deployment-dev, front-end

#2767 Feat: OAuth hooks for `authorize` view
  benefits/eligibility/verify.py
  benefits/eligibility/views.py
  benefits/oauth/hooks.py
  tests/pytest/eligibility/test_verify.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/oauth/test_hooks.py
Labels: deployment-dev, tests

#2795 Feat(session): set config for cdt_identity when setting flow
  benefits/core/session.py
  tests/pytest/core/test_session.py
Labels: back-end

#2797 Chore: re-enable BuildKit for Mac devs
  bin/build.sh
Labels: deployment-dev

#2783 Refactor: use cdt_identity `authorize` view
  benefits/core/session.py
  benefits/eligibility/views.py
  benefits/oauth/hooks.py
  benefits/oauth/urls.py
  benefits/oauth/views.py
  tests/pytest/conftest.py
  tests/pytest/core/test_middleware_login_required.py
  tests/pytest/core/test_session.py
  tests/pytest/eligibility/test_views.py
  tests/pytest/enrollment/test_analytics.py
  tests/pytest/oauth/test_hooks.py
  tests/pytest/oauth/test_views.py
Labels: deployment-dev, back-end
