Repository cal-itp/benefits, pull requests merged in 2025-02, with the labels that each got.

#2659 Test: introduce admin conftest to use for testing `add` permissions
  tests/pytest/core/admin/conftest.py
  tests/pytest/core/admin/test_users.py
Labels: tests

#2558 Feat: Playwright headed mode
  compose.yml
  docs/tests/automated-tests.md
  docs/tests/img/playwright-inspector.png
Labels: docker

#2667 Feat: field/add permissions for Transit models
  benefits/core/admin/transit.py
  tests/pytest/core/admin/test_transit.py
Labels: deployment-dev, back-end

#2656 Fix: port forwarding in VS Code
  .devcontainer/devcontainer.json
Labels: chore, docker

#2677 Chore: add fixture for Cal-ITP Staff account
  benefits/core/migrations/local_fixtures.json
Labels: deployment-dev, migrations

#2674 Refactor: simplify Agency Index templates
  benefits/core/admin/transit.py
  benefits/core/context.py
  benefits/core/migrations/0034_transit_agency_index_context.py
  benefits/core/models/transit.py
  benefits/core/templates/core/index--agency.html
  benefits/core/templates/core/index--cst.html
  benefits/core/templates/core/index--mst.html
  benefits/core/templates/core/index--nevco.html
  benefits/core/templates/core/index--sacrt.html
  benefits/core/templates/core/index--sbmtd.html
  benefits/core/views.py
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  tests/pytest/conftest.py
  tests/pytest/core/admin/test_transit.py
  tests/pytest/core/models/test_transit.py
  tests/pytest/core/test_views.py
Labels: deployment-dev, tests, front-end, back-end, i18n, migrations

#2671 Feat: field/add permissions for ClaimsProvider model
  benefits/core/admin/claims.py
  tests/pytest/core/admin/test_claims.py
Labels: deployment-dev, back-end

#2654 Feat: Cal-ITP staff can add EnrollmentFlow
  benefits/core/admin/enrollment.py
  benefits/core/models/enrollment.py
  benefits/core/models/transit.py
  tests/pytest/core/admin/test_enrollment.py
  tests/pytest/core/models/test_enrollment.py
  tests/pytest/core/models/test_transit.py
  tests/pytest/eligibility/test_views.py
Labels: tests, back-end

#2673 Feat: field/add permissions for PemData model
  benefits/core/admin/common.py
  tests/pytest/core/admin/test_common.py
Labels: tests, back-end

#2687 Chore: unnecessary read-only field in EnrollmentEventAdmin
  benefits/core/admin/enrollment.py
  tests/pytest/core/admin/test_enrollment.py
Labels: deployment-dev, tests, back-end

#2696 Chore: run pre-commit on all files
  benefits/static/css/styles.css
  benefits/static/css/variables.css
Labels: deployment-dev, front-end

#2698 Refactor: choices for EnrollmentFlow.system_name
  benefits/core/context/__init__.py
  benefits/core/context/flow.py
  benefits/core/migrations/0035_enrollmentflow_system_name_choices.py
  benefits/core/models/enrollment.py
  tests/pytest/conftest.py
  tests/pytest/core/admin/test_enrollment.py
  tests/pytest/core/test_views.py
  tests/pytest/eligibility/test_verify.py
Labels: back-end, migrations

#2702 Fix: rename test route to `testerror/`
  benefits/urls.py
Labels: deployment-dev, back-end

#2688 Admin: Front-end for Flow pages
  benefits/in_person/templates/error-base.html
  benefits/in_person/templates/in_person/eligibility.html
  benefits/in_person/templates/in_person/enrollment/index.html
  benefits/in_person/templates/in_person/enrollment/retry.html
  benefits/in_person/templates/in_person/enrollment/success.html
  benefits/in_person/templates/in_person/error-base.html
  benefits/static/css/admin/styles.css
  benefits/templates/admin/agency-dashboard-index.html
  benefits/templates/admin/flow-base.html
  benefits/templates/admin/login.html
Labels: deployment-dev

#2689 Feat: in-person eligibility policies
  benefits/core/migrations/0036_in_person_enrollmentflows.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models/enrollment.py
  benefits/core/templates/core/includes/form.html
  benefits/in_person/context/__init__.py
  benefits/in_person/context/eligibility.py
  benefits/in_person/forms.py
  benefits/in_person/templates/in_person/eligibility.html
  benefits/in_person/templates/in_person/includes/eligibility-form.html
  tests/pytest/core/models/test_enrollment.py
  tests/pytest/in_person/test_views.py
Labels: deployment-dev, front-end, back-end

#2708 Fix: add google recaptcha to connect-src CSP directives
  benefits/settings.py
Labels: deployment-dev, back-end

#2711 docs: updates-to-agency-adoption-table
  docs/README.md
Labels: documentation

#2714 Test: ensure core_context.agency_index contains all AgencySlugs
  tests/pytest/core/context/test_agency.py
Labels: tests

#2715 Chore: remove unused parameter in eligibility_from_oauth
  benefits/eligibility/verify.py
  benefits/eligibility/views.py
  tests/pytest/eligibility/test_verify.py
Labels: deployment-dev, tests, back-end

#2712 docs: embed calfresh video walkthrough
  docs/enrollment-pathways/low-income.md
Labels: documentation
