Repository cal-itp/benefits, pull requests merged in 2025-01, with the labels that each got.

#2600 Agency link focus rings are now rounded
  benefits/core/templates/core/includes/agency-links.html
Labels: deployment-dev, front-end

#2586 reCAPTCHA: Elig Index, Elig Confirm - Add reCAPTCHA text, hide flag
  benefits/core/templates/core/includes/form.html
  benefits/core/templates/core/includes/recaptcha-text.html
  benefits/eligibility/forms.py
  benefits/eligibility/templates/eligibility/confirm.html
  benefits/eligibility/templates/eligibility/index.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
Labels: front-end, i18n

#2588 reCAPTCHA: Spacing and template refactor
  benefits/core/templates/core/base.html
  benefits/core/templates/core/index--agency-base.html
  benefits/core/templates/core/index--cst.html
  benefits/core/templates/core/index--mst.html
  benefits/core/templates/core/index--nevco.html
  benefits/core/templates/core/index--sacrt.html
  benefits/core/templates/core/index--sbmtd.html
  benefits/core/templates/core/index-base.html
  benefits/core/templates/core/index.html
  benefits/core/templates/core/logged-out.html
  benefits/core/views.py
  benefits/eligibility/templates/eligibility/confirm.html
  benefits/eligibility/templates/eligibility/index--cst.html
  benefits/eligibility/templates/eligibility/index--mst.html
  benefits/eligibility/templates/eligibility/index--nevco.html
  benefits/eligibility/templates/eligibility/index--sacrt.html
  benefits/eligibility/templates/eligibility/index--sbmtd.html
  benefits/eligibility/templates/eligibility/index.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/enrollment/templates/enrollment/index--agency-card.html
  benefits/enrollment/templates/enrollment/index--calfresh.html
  benefits/enrollment/templates/enrollment/index.html
  benefits/enrollment/templates/enrollment/success.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
  benefits/templates/error-base.html
  tests/pytest/conftest.py
Labels: front-end, back-end

#2612 Chore(infra): allow reCAPTCHA settings on dev environment
  terraform/app_service.tf
Labels: infrastructure

#2610 CI: workflow checks eligibility server metadata
  .github/workflows/check-metadata.py
  .github/workflows/check-metadata.yml
  .gitignore
Labels: actions

#2614 Fix: check out code first in workflow
  .github/workflows/check-metadata.yml
Labels: bug, actions

#2615 chore: added forwardPorts
  .devcontainer/devcontainer.json
Labels: docker

#2616 Fix: use `server:main` image
  compose.yml
Labels: bug, docker

#2613 Fix: reCAPTCHA-related - Fix Admin form style regression
  benefits/core/templates/core/includes/form.html
  benefits/eligibility/forms.py
  benefits/in_person/forms.py
  benefits/static/css/admin/styles.css
  benefits/static/css/styles.css
Labels: front-end

#2578 CI: update littlepay switch syntax
  .github/workflows/check-api.yml
Labels: actions

#2619 Fix: have Django serve media files even when DEBUG=False
  benefits/urls.py
Labels: deployment-dev, back-end

#2626 docs: adding link to dec 2024 update
  docs/product-and-design/newsletter-archive.md
Labels: documentation

#2609 Refactor: split models into multiple files
  benefits/core/migrations/0033_pemdata_helptext.py
  benefits/core/models/__init__.py
  benefits/core/models/claims.py
  benefits/core/models/common.py
  benefits/core/models/enrollment.py
  benefits/core/models/transit.py
  tests/pytest/conftest.py
  tests/pytest/core/models/__init__.py
  tests/pytest/core/models/conftest.py
  tests/pytest/core/models/test_claims.py
  tests/pytest/core/models/test_common.py
  tests/pytest/core/models/test_enrollment.py
  tests/pytest/core/models/test_transit.py
Labels: deployment-dev, chore, back-end

#2629 Fix: use headline-text for block
  benefits/eligibility/templates/eligibility/start--sbmtd-agency-card.html
Labels: deployment-dev, front-end

#2617 Chore: reformat all templates to 2 spaces
  .gitignore
  .pre-commit-config.yaml
  .vscode/settings.json
  benefits/core/templates/core/base.html
  benefits/core/templates/core/includes/agency-links.html
  benefits/core/templates/core/includes/alert-box.html
  benefits/core/templates/core/includes/eligibility-item.html
  benefits/core/templates/core/includes/help--calfresh.html
  benefits/core/templates/core/includes/help--medicare.html
  benefits/core/templates/core/includes/help--sbmtd-mobility-pass.html
  benefits/core/templates/core/includes/modal--agency-selector.html
  benefits/core/templates/core/includes/modal.html
  benefits/core/templates/core/index--sbmtd.html
  benefits/core/templates/core/widgets/flow-radio-select-option.html
  benefits/eligibility/templates/eligibility/includes/eligibility-item--contactless-card--start.html
  benefits/eligibility/templates/eligibility/includes/eligibility-item--identification--start--sbmtd-agency-card.html
  benefits/eligibility/templates/eligibility/includes/modal--calfresh.html
  benefits/eligibility/templates/eligibility/includes/modal--login-gov-help.html
  benefits/eligibility/templates/eligibility/includes/modal--login-gov-start-help.html
  benefits/eligibility/templates/eligibility/includes/modal--medicare.html
  benefits/eligibility/templates/eligibility/includes/selection-label--calfresh.html
  benefits/eligibility/templates/eligibility/includes/selection-label--cst-agency-card.html
  benefits/eligibility/templates/eligibility/includes/selection-label--medicare.html
  benefits/eligibility/templates/eligibility/includes/selection-label--mst-agency-card.html
  benefits/eligibility/templates/eligibility/includes/selection-label--sbmtd-agency-card.html
  benefits/eligibility/templates/eligibility/includes/selection-label.html
  benefits/eligibility/templates/eligibility/index--sbmtd.html
  benefits/eligibility/templates/eligibility/start--medicare.html
  benefits/eligibility/templates/eligibility/start--sbmtd-agency-card.html
  benefits/eligibility/templates/eligibility/unverified--cst-agency-card.html
  benefits/eligibility/templates/eligibility/unverified--mst-agency-card.html
  benefits/eligibility/templates/eligibility/unverified--sbmtd-agency-card.html
  benefits/enrollment/templates/enrollment/includes/alert-box--warning--calfresh.html
  benefits/enrollment/templates/enrollment/reenrollment-error--calfresh.html
  benefits/enrollment/templates/enrollment/success--sbmtd-agency-card.html
  benefits/enrollment/templates/enrollment/success--sbmtd.html
  benefits/in_person/templates/error-base.html
  benefits/in_person/templates/in_person/eligibility.html
  benefits/in_person/templates/in_person/enrollment/index.html
  benefits/in_person/templates/in_person/enrollment/reenrollment_error.html
  benefits/in_person/templates/in_person/enrollment/retry.html
  benefits/in_person/templates/in_person/enrollment/server_error.html
  benefits/in_person/templates/in_person/enrollment/success.html
  benefits/in_person/templates/in_person/enrollment/system_error.html
  benefits/templates/admin/agency-base.html
  benefits/templates/admin/agency-dashboard-index.html
  benefits/templates/admin/base_site.html
  benefits/templates/admin/includes/branding-login.html
  benefits/templates/admin/includes/usertools.html
  benefits/templates/admin/login.html
  benefits/templates/registration/logged_out.html
Labels: chore, front-end

#2631 Refactor: web perf - load recaptcha script only where it's needed
  benefits/core/templates/core/base.html
  benefits/core/templates/core/includes/form.html
Labels: deployment-dev, front-end

#2640 Perf: load Bootstrap JS asynchronously
  benefits/core/templates/core/base.html
Labels: deployment-dev, front-end

#2644 Fix: Set important to override bootstrap h4
  benefits/static/css/styles.css
Labels: deployment-dev, front-end

#2645 Docs: update syntax for non-markdown numbering
  docs/development/application-logic.md
Labels: bug, documentation

#2646 Refactor: reduce usage of jQuery
  benefits/core/templates/core/base.html
  benefits/core/templates/core/includes/form.html
  benefits/core/templates/core/includes/ready-js.html
  benefits/eligibility/templates/eligibility/index.html
  benefits/enrollment/templates/enrollment/includes/jquery.html
  benefits/enrollment/templates/enrollment/index.html
  benefits/in_person/templates/in_person/enrollment/index.html
  benefits/templates/admin/agency-base.html
Labels: deployment-dev, front-end

#2639 Perf: improve Google Web Font performance
  benefits/core/templates/core/base.html
Labels: deployment-dev, front-end

#2652 Refactor: make `benefits/core/admin.py` into a package
  benefits/core/admin.py
  benefits/core/admin/__init__.py
  benefits/core/admin/claims.py
  benefits/core/admin/common.py
  benefits/core/admin/enrollment.py
  benefits/core/admin/transit.py
  benefits/core/admin/users.py
  benefits/in_person/urls.py
  tests/pytest/core/admin/__init__.py
  tests/pytest/core/admin/test_users.py
Labels: deployment-dev, tests

#2653 Feat: helper function checks if user is staff or superuser
  benefits/core/admin/__init__.py
  benefits/core/admin/enrollment.py
  benefits/core/admin/users.py
  tests/pytest/core/admin/test_users.py
Labels: deployment-dev, tests, back-end
