Repository cal-itp/benefits, pull requests merged in 2025-10, with the labels that each got.

#3204 chore: fix a few typos in the docs and update djlint github url
  .pre-commit-config.yaml
  docs/development/docker-dynamic-ports.md
  docs/development/test-server.md
  docs/getting-started/README.md
Labels: documentation, chore

#3211 chore: Onboarding improvements for new developers
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .env.sample
  .vscode/launch.json
  benefits/core/migrations/local_fixtures.json
  bin/reset_db.sh
  docs/configuration/data.md
  docs/configuration/environment-variables.md
  docs/development/README.md
  docs/development/test-server.md
  docs/getting-started/README.md
  docs/getting-started/documentation.md
  mkdocs.yml
Labels: documentation, migrations

#3206 feat: implement eyebrow text on landing page
  benefits/core/context/agency.py
  benefits/core/templates/core/index-base.html
  benefits/core/templates/core/index.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/static/css/styles.css
Labels: front-end, back-end

#3223 docs: typo fixes
  docs/deployment/README.md
  docs/getting-started/README.md
Labels: documentation, infrastructure

#3225 chore: use prettier@2.x in pre-commit
  .pre-commit-config.yaml
  benefits/static/css/admin/styles.css
  benefits/static/css/admin/theme.css
  benefits/static/css/styles.css
  benefits/static/css/variables.css
Labels: front-end, back-end
