Repository cal-itp/benefits, pull requests merged in 2025-06, with the labels that each got.

#2945 Add Discover, American Express copy under feature flag
  benefits/core/context_processors.py
  benefits/core/templates/core/help.html
  benefits/eligibility/templates/eligibility/includes/modal--contactless.html
  benefits/eligibility/templates/eligibility/start.html
  benefits/enrollment/templates/enrollment/includes/alert-box--warning--calfresh.html
  benefits/enrollment/templates/enrollment/index-base.html
  benefits/locale/en/LC_MESSAGES/django.po
  benefits/locale/es/LC_MESSAGES/django.po
  benefits/settings.py
  tests/pytest/core/test_context_processors.py
Labels: front-end, i18n

#2957 Docs on littlepay-additional-cardtypes variable
  docs/configuration/environment-variables.md
Labels: documentation

#2951 Feat: Littlepay and Switchio API base URLs
  .env.sample
  benefits/core/admin/transit.py
  benefits/core/migrations/0051_remove_transitprocessor_api_base_url.py
  benefits/core/migrations/local_fixtures.json
  benefits/core/models/transit.py
  benefits/enrollment_littlepay/enrollment.py
  benefits/enrollment_littlepay/models.py
  benefits/enrollment_switchio/models.py
  terraform/app_service.tf
  tests/pytest/conftest.py
  tests/pytest/core/admin/test_transit.py
  tests/pytest/enrollment_littlepay/test_enrollment.py
  tests/pytest/enrollment_littlepay/test_models.py
  tests/pytest/enrollment_switchio/test_models.py
Labels: back-end, migrations

#2964 Feat: support additional card types for Littlepay in-person enrollment
  benefits/enrollment_littlepay/enrollment.py
  benefits/enrollment_littlepay/views.py
  benefits/in_person/templates/in_person/enrollment/index.html
  benefits/in_person/views.py
  tests/pytest/enrollment_littlepay/test_enrollment.py
  tests/pytest/enrollment_littlepay/test_views.py
  tests/pytest/in_person/test_views.py
Labels: front-end, back-end

#2960 Feat: error-handling for GatewayUrlView
  benefits/enrollment/analytics.py
  benefits/enrollment_littlepay/views.py
  benefits/enrollment_switchio/enrollment.py
  benefits/enrollment_switchio/views.py
  benefits/in_person/views.py
  tests/pytest/enrollment/test_analytics.py
  tests/pytest/enrollment_littlepay/test_views.py
  tests/pytest/enrollment_switchio/test_enrollment.py
  tests/pytest/enrollment_switchio/test_views.py
  tests/pytest/in_person/test_views.py
Labels: tests, back-end

#2977 Feat: Switchio enrollment redirect
  benefits/enrollment_switchio/enrollment.py
  benefits/enrollment_switchio/templates/enrollment_switchio/index.html
  benefits/enrollment_switchio/views.py
  tests/pytest/enrollment_switchio/test_views.py
Labels: tests, back-end

#2985 docs: adding link for june newsletter
  docs/product-and-design/newsletter-archive.md
Labels: documentation
